# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/bulk_transaction"

module Pokepay::Request
  class BulkCreateTransaction < Request
    def initialize(name, content, request_id, rest_args = {})
      @path = "/transactions" + "/bulk"
      @method = "POST"
      @body_params = { "name" => name,
                       "content" => content,
                       "request_id" => request_id }.merge(rest_args)
      @response_class = Pokepay::Response::BulkTransaction
    end
    attr_reader :response_class
  end
end
