# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/bulk_transaction"

module Pokepay::Request
  class CancelBulkTransaction < Request
    def initialize(bulk_transaction_id)
      @path = "/bulk-transactions" + "/" + bulk_transaction_id + "/cancel"
      @method = "POST"
      @body_params = {  }
      @response_class = Pokepay::Response::BulkTransaction
    end
    attr_reader :response_class
  end
end
