# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/captured_credit_session"

module Pokepay::Request
  class CaptureCreditSession < Request
    def initialize(session_id, rest_args = {})
      @path = "/credit-sessions" + "/" + session_id + "/capture"
      @method = "POST"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::CapturedCreditSession
    end
    attr_reader :response_class
  end
end
