# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/bill"

module Pokepay::Request
  class CreateBill < Request
    def initialize(private_money_id, shop_id, rest_args = {})
      @path = "/bills"
      @method = "POST"
      @body_params = { "private_money_id" => private_money_id,
                       "shop_id" => shop_id }.merge(rest_args)
      @response_class = Pokepay::Response::Bill
    end
    attr_reader :response_class
  end
end
