# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/transaction_group"

module Pokepay::Request
  class CreateTransactionGroup < Request
    def initialize(name)
      @path = "/transaction-groups"
      @method = "POST"
      @body_params = { "name" => name }
      @response_class = Pokepay::Response::TransactionGroup
    end
    attr_reader :response_class
  end
end
