# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/organization_worker_task_webhook"

module Pokepay::Request
  class CreateWebhook < Request
    def initialize(task, url)
      @path = "/webhooks"
      @method = "POST"
      @body_params = { "task" => task,
                       "url" => url }
      @response_class = Pokepay::Response::OrganizationWorkerTaskWebhook
    end
    attr_reader :response_class
  end
end
