# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/transaction"

module Pokepay::Request
  class CreateTransferTransaction < Request
    def initialize(sender_id, receiver_id, private_money_id, amount, rest_args = {})
      @path = "/transactions" + "/transfer"
      @method = "POST"
      @body_params = { "sender_id" => sender_id,
                       "receiver_id" => receiver_id,
                       "private_money_id" => private_money_id,
                       "amount" => amount }.merge(rest_args)
      @response_class = Pokepay::Response::Transaction
    end
    attr_reader :response_class
  end
end
