# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/transaction_detail"

module Pokepay::Request
  class CreateTransactionWithCashtray < Request
    def initialize(cashtray_id, customer_id, rest_args = {})
      @path = "/transactions" + "/cashtray"
      @method = "POST"
      @body_params = { "cashtray_id" => cashtray_id,
                       "customer_id" => customer_id }.merge(rest_args)
      @response_class = Pokepay::Response::TransactionDetail
    end
    attr_reader :response_class
  end
end
