# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/user_device"

module Pokepay::Request
  class CreateUserDevice < Request
    def initialize(user_id, rest_args = {})
      @path = "/user-devices"
      @method = "POST"
      @body_params = { "user_id" => user_id }.merge(rest_args)
      @response_class = Pokepay::Response::UserDevice
    end
    attr_reader :response_class
  end
end
