# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/shop_with_accounts"

module Pokepay::Request
  class CreateShopV2 < Request
    def initialize(name, rest_args = {})
      @path = "/shops-v2"
      @method = "POST"
      @body_params = { "name" => name }.merge(rest_args)
      @response_class = Pokepay::Response::ShopWithAccounts
    end
    attr_reader :response_class
  end
end
