# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/user_card"

module Pokepay::Request
  class CreateCustomerCard < Request
    def initialize(customer_id, token, rest_args = {})
      @path = "/customers" + "/" + customer_id + "/cards"
      @method = "POST"
      @body_params = { "token" => token }.merge(rest_args)
      @response_class = Pokepay::Response::UserCard
    end
    attr_reader :response_class
  end
end
