# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/cvs_authorization"

module Pokepay::Request
  class CreateCvsAuthorization < Request
    def initialize(customer_id, private_money_id, amount, service_option_type, name1, name2, tel, rest_args = {})
      @path = "/cvs"
      @method = "POST"
      @body_params = { "customer_id" => customer_id,
                       "private_money_id" => private_money_id,
                       "amount" => amount,
                       "service_option_type" => service_option_type,
                       "name1" => name1,
                       "name2" => name2,
                       "tel" => tel }.merge(rest_args)
      @response_class = Pokepay::Response::CvsAuthorization
    end
    attr_reader :response_class
  end
end
