# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/cashtray"

module Pokepay::Request
  class CreateCashtray < Request
    def initialize(private_money_id, shop_id, amount, rest_args = {})
      @path = "/cashtrays"
      @method = "POST"
      @body_params = { "private_money_id" => private_money_id,
                       "shop_id" => shop_id,
                       "amount" => amount }.merge(rest_args)
      @response_class = Pokepay::Response::Cashtray
    end
    attr_reader :response_class
  end
end
