# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_with_user"

module Pokepay::Request
  class CreateCustomerAccount < Request
    def initialize(private_money_id, rest_args = {})
      @path = "/accounts" + "/customers"
      @method = "POST"
      @body_params = { "private_money_id" => private_money_id }.merge(rest_args)
      @response_class = Pokepay::Response::AccountWithUser
    end
    attr_reader :response_class
  end
end
