# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/transaction_detail"

module Pokepay::Request
  class CreatePaymentTransactionWithBill < Request
    def initialize(bill_id, customer_id, rest_args = {})
      @path = "/transactions" + "/payment" + "/bill"
      @method = "POST"
      @body_params = { "bill_id" => bill_id,
                       "customer_id" => customer_id }.merge(rest_args)
      @response_class = Pokepay::Response::TransactionDetail
    end
    attr_reader :response_class
  end
end
