# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/coupon_detail"

module Pokepay::Request
  class CreateCoupon < Request
    def initialize(private_money_id, name, starts_at, ends_at, issued_shop_id, rest_args = {})
      @path = "/coupons"
      @method = "POST"
      @body_params = { "private_money_id" => private_money_id,
                       "name" => name,
                       "starts_at" => starts_at,
                       "ends_at" => ends_at,
                       "issued_shop_id" => issued_shop_id }.merge(rest_args)
      @response_class = Pokepay::Response::CouponDetail
    end
    attr_reader :response_class
  end
end
