# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/credit_session_transaction_result"

module Pokepay::Request
  class CreateCreditSessionTransaction < Request
    def initialize(session_id, amount, rest_args = {})
      @path = "/credit-sessions" + "/" + session_id + "/transactions"
      @method = "POST"
      @body_params = { "amount" => amount }.merge(rest_args)
      @response_class = Pokepay::Response::CreditSessionTransactionResult
    end
    attr_reader :response_class
  end
end
