# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/campaign"

module Pokepay::Request
  class CreateCampaign < Request
    def initialize(name, private_money_id, starts_at, ends_at, priority, event, rest_args = {})
      @path = "/campaigns"
      @method = "POST"
      @body_params = { "name" => name,
                       "private_money_id" => private_money_id,
                       "starts_at" => starts_at,
                       "ends_at" => ends_at,
                       "priority" => priority,
                       "event" => event }.merge(rest_args)
      @response_class = Pokepay::Response::Campaign
    end
    attr_reader :response_class
  end
end
