# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_detail"

module Pokepay::Request
  class CreateUserAccount < Request
    def initialize(user_id, private_money_id, rest_args = {})
      @path = "/users" + "/" + user_id + "/accounts"
      @method = "POST"
      @body_params = { "private_money_id" => private_money_id }.merge(rest_args)
      @response_class = Pokepay::Response::AccountDetail
    end
    attr_reader :response_class
  end
end
