# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/card_authorize_result"

module Pokepay::Request
  class CreditCardTopupWithMembership < Request
    def initialize(customer_id, card_uuid, private_money_id, amount, rest_args = {})
      @path = "/customers" + "/" + customer_id + "/card-authorize" + "/topup-with-membership"
      @method = "POST"
      @body_params = { "card_uuid" => card_uuid,
                       "private_money_id" => private_money_id,
                       "amount" => amount }.merge(rest_args)
      @response_class = Pokepay::Response::CardAuthorizeResult
    end
    attr_reader :response_class
  end
end
