# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/organization_worker_task_webhook"

module Pokepay::Request
  class DeleteWebhook < Request
    def initialize(webhook_id)
      @path = "/webhooks" + "/" + webhook_id
      @method = "DELETE"
      @body_params = {  }
      @response_class = Pokepay::Response::OrganizationWorkerTaskWebhook
    end
    attr_reader :response_class
  end
end
