# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_deleted"

module Pokepay::Request
  class DeleteAccount < Request
    def initialize(account_id, rest_args = {})
      @path = "/accounts" + "/" + account_id
      @method = "DELETE"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::AccountDeleted
    end
    attr_reader :response_class
  end
end
