# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/bank_deleted"

module Pokepay::Request
  class DeleteBank < Request
    def initialize(user_device_id, bank_id)
      @path = "/user-devices" + "/" + user_device_id + "/banks"
      @method = "DELETE"
      @body_params = { "bank_id" => bank_id }
      @response_class = Pokepay::Response::BankDeleted
    end
    attr_reader :response_class
  end
end
