# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/customer_card_deleted"

module Pokepay::Request
  class DeleteCustomerCard < Request
    def initialize(customer_id, card_uuid)
      @path = "/customers" + "/" + customer_id + "/cards" + "/delete"
      @method = "POST"
      @body_params = { "card_uuid" => card_uuid }
      @response_class = Pokepay::Response::CustomerCardDeleted
    end
    attr_reader :response_class
  end
end
