# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/shop_with_accounts"

module Pokepay::Request
  class GetShop < Request
    def initialize(shop_id)
      @path = "/shops" + "/" + shop_id
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::ShopWithAccounts
    end
    attr_reader :response_class
  end
end
