# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_private_money_organization_summaries"

module Pokepay::Request
  class GetPrivateMoneyOrganizationSummaries < Request
    def initialize(private_money_id, rest_args = {})
      @path = "/private-moneys" + "/" + private_money_id + "/organization-summaries"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedPrivateMoneyOrganizationSummaries
    end
    attr_reader :response_class
  end
end
