# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/check"

module Pokepay::Request
  class GetCheck < Request
    def initialize(check_id)
      @path = "/checks" + "/" + check_id
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::Check
    end
    attr_reader :response_class
  end
end
