# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_customers"

module Pokepay::Request
  class GetCustomer < Request
    def initialize(private_money_id, rest_args = {})
      @path = "/customers"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedCustomers
    end
    attr_reader :response_class
  end
end
