# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/cashtray_with_result"

module Pokepay::Request
  class GetCashtray < Request
    def initialize(cashtray_id)
      @path = "/cashtrays" + "/" + cashtray_id
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::CashtrayWithResult
    end
    attr_reader :response_class
  end
end
