# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/campaign"

module Pokepay::Request
  class GetCampaign < Request
    def initialize(campaign_id)
      @path = "/campaigns" + "/" + campaign_id
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::Campaign
    end
    attr_reader :response_class
  end
end
