# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_user_cards"

module Pokepay::Request
  class GetCustomerCards < Request
    def initialize(customer_id, rest_args = {})
      @path = "/customers" + "/" + customer_id + "/cards"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedUserCards
    end
    attr_reader :response_class
  end
end
