# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/external_transaction_detail"

module Pokepay::Request
  class GetExternalTransactionByRequestId < Request
    def initialize(request_id)
      @path = "/external-transactions" + "/requests" + "/" + request_id
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::ExternalTransactionDetail
    end
    attr_reader :response_class
  end
end
