# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_detail"

module Pokepay::Request
  class GetAccount < Request
    def initialize(account_id)
      @path = "/accounts" + "/" + account_id
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::AccountDetail
    end
    attr_reader :response_class
  end
end
