# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/admin_user_with_shops_and_private_moneys"

module Pokepay::Request
  class GetUser < Request
    def initialize()
      @path = "/user"
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::AdminUserWithShopsAndPrivateMoneys
    end
    attr_reader :response_class
  end
end
