# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/seven_bank_atm_session"

module Pokepay::Request
  class GetSevenBankATMSession < Request
    def initialize(qr_info)
      @path = "/seven-bank-atm-sessions" + "/" + qr_info
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::SevenBankATMSession
    end
    attr_reader :response_class
  end
end
