# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/bill_with_additional_private_moneys"

module Pokepay::Request
  class GetBill < Request
    def initialize(bill_id)
      @path = "/bills" + "/" + bill_id
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::BillWithAdditionalPrivateMoneys
    end
    attr_reader :response_class
  end
end
