# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_transfer_summary"

module Pokepay::Request
  class GetAccountTransferSummary < Request
    def initialize(account_id, rest_args = {})
      @path = "/accounts" + "/" + account_id + "/transfers" + "/summary"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::AccountTransferSummary
    end
    attr_reader :response_class
  end
end
