# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/cvs_authorization"

module Pokepay::Request
  class GetCvsAuthorization < Request
    def initialize(order_id)
      @path = "/cvs" + "/" + order_id
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::CvsAuthorization
    end
    attr_reader :response_class
  end
end
