# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/private_money_summary"

module Pokepay::Request
  class GetPrivateMoneySummary < Request
    def initialize(private_money_id, rest_args = {})
      @path = "/private-moneys" + "/" + private_money_id + "/summary"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PrivateMoneySummary
    end
    attr_reader :response_class
  end
end
