# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_bulk_transaction_job"

module Pokepay::Request
  class GetBulkTransaction < Request
    def initialize(bulk_transaction_id, rest_args = {})
      @path = "/bulk-transactions" + "/" + bulk_transaction_id + "/jobs"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedBulkTransactionJob
    end
    attr_reader :response_class
  end
end
