# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_checks"

module Pokepay::Request
  class ListChecks < Request
    def initialize(rest_args = {})
      @path = "/checks"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedChecks
    end
    attr_reader :response_class
  end
end
