# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_transaction_v2"

module Pokepay::Request
  class ListTransactionsV2 < Request
    def initialize(rest_args = {})
      @path = "/transactions-v2"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedTransactionV2
    end
    attr_reader :response_class
  end
end
