# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_bill_transaction"

module Pokepay::Request
  class ListBillTransactions < Request
    def initialize(rest_args = {})
      @path = "/transactions" + "/bill"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedBillTransaction
    end
    attr_reader :response_class
  end
end
