# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_organization_worker_task_webhook"

module Pokepay::Request
  class ListWebhooks < Request
    def initialize(rest_args = {})
      @path = "/webhooks"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedOrganizationWorkerTaskWebhook
    end
    attr_reader :response_class
  end
end
