# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_account_balance"

module Pokepay::Request
  class ListAccountExpiredBalances < Request
    def initialize(account_id, rest_args = {})
      @path = "/accounts" + "/" + account_id + "/expired-balances"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedAccountBalance
    end
    attr_reader :response_class
  end
end
