# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_shops"

module Pokepay::Request
  class ListShops < Request
    def initialize(rest_args = {})
      @path = "/shops"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedShops
    end
    attr_reader :response_class
  end
end
