# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_bills"

module Pokepay::Request
  class ListBills < Request
    def initialize(rest_args = {})
      @path = "/bills"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedBills
    end
    attr_reader :response_class
  end
end
