# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_transfers"

module Pokepay::Request
  class ListTransfers < Request
    def initialize(rest_args = {})
      @path = "/transfers"
      @method = "GET"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedTransfers
    end
    attr_reader :response_class
  end
end
