# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/paginated_transaction"

module Pokepay::Request
  class ListCustomerTransactions < Request
    def initialize(private_money_id, rest_args = {})
      @path = "/customers" + "/transactions"
      @method = "GET"
      @body_params = { "private_money_id" => private_money_id }.merge(rest_args)
      @response_class = Pokepay::Response::PaginatedTransaction
    end
    attr_reader :response_class
  end
end
