# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/credit_session"

module Pokepay::Request
  class PostCreditSession < Request
    def initialize(customer_id, private_money_id, card_id, expires_at, rest_args = {})
      @path = "/credit-sessions"
      @method = "POST"
      @body_params = { "customer_id" => customer_id,
                       "private_money_id" => private_money_id,
                       "card_id" => card_id,
                       "expires_at" => expires_at }.merge(rest_args)
      @response_class = Pokepay::Response::CreditSession
    end
    attr_reader :response_class
  end
end
