# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/transaction_detail"

module Pokepay::Request
  class RefundTransaction < Request
    def initialize(transaction_id, rest_args = {})
      @path = "/transactions" + "/" + transaction_id + "/refund"
      @method = "POST"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::TransactionDetail
    end
    attr_reader :response_class
  end
end
