# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/transaction_group"

module Pokepay::Request
  class ShowTransactionGroup < Request
    def initialize(uuid)
      @path = "/transaction-groups" + "/" + uuid
      @method = "GET"
      @body_params = {  }
      @response_class = Pokepay::Response::TransactionGroup
    end
    attr_reader :response_class
  end
end
