# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/user_stats_operation"

module Pokepay::Request
  class TerminateUserStats < Request
    def initialize(operation_id)
      @path = "/user-stats" + "/terminate"
      @method = "POST"
      @body_params = { "operation_id" => operation_id }
      @response_class = Pokepay::Response::UserStatsOperation
    end
    attr_reader :response_class
  end
end
