# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/shop_with_accounts"

module Pokepay::Request
  class UpdateShop < Request
    def initialize(shop_id, rest_args = {})
      @path = "/shops" + "/" + shop_id
      @method = "PATCH"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::ShopWithAccounts
    end
    attr_reader :response_class
  end
end
