# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/cashtray"

module Pokepay::Request
  class UpdateCashtray < Request
    def initialize(cashtray_id, rest_args = {})
      @path = "/cashtrays" + "/" + cashtray_id
      @method = "PATCH"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::Cashtray
    end
    attr_reader :response_class
  end
end
