# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_detail"

module Pokepay::Request
  class UpdateAccount < Request
    def initialize(account_id, rest_args = {})
      @path = "/accounts" + "/" + account_id
      @method = "PATCH"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::AccountDetail
    end
    attr_reader :response_class
  end
end
