# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/organization_worker_task_webhook"

module Pokepay::Request
  class UpdateWebhook < Request
    def initialize(webhook_id, rest_args = {})
      @path = "/webhooks" + "/" + webhook_id
      @method = "PATCH"
      @body_params = {  }.merge(rest_args)
      @response_class = Pokepay::Response::OrganizationWorkerTaskWebhook
    end
    attr_reader :response_class
  end
end
