# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

require 'minitest/autorun'
require 'securerandom'
require "pokepay_partner_ruby_sdk"
require "inifile"

$client = Pokepay::Client.new(File.expand_path("~/.pokepay/test-config.ini"))
$inifile = IniFile.load(File.expand_path("~/.pokepay/test-config.ini"))

class CreateNewCustomerWithAccountTest < Minitest::Test
  def testCreateNewCustomerWithAccount
    user_name = "user-name" + SecureRandom.base64(6)
    account_name = "account-name" + SecureRandom.base64(6)
    customer_account = $client.send(Pokepay::Request::CreateCustomerAccount.new(
      "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
      user_name: user_name,
      account_name: account_name
    ))
    assert_equal(user_name, customer_account.user.name)
    assert_equal(account_name, customer_account.name)
    shop_name = "shop-name" + SecureRandom.base64(6)
    shop = $client.send(Pokepay::Request::CreateShopV2.new(
      shop_name,
      private_money_ids: ["4b138a4c-8944-4f98-a5c4-96d3c1c415eb"],
      can_topup_private_money_ids: ["4b138a4c-8944-4f98-a5c4-96d3c1c415eb"]
    ))
    topup_transaction = $client.send(Pokepay::Request::CreateTopupTransaction.new(
      shop.id,
      customer_account.user.id,
      "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
      money_amount: 1000,
      point_amount: 1000
    ))
    assert_equal(topup_transaction.type, "topup")
    payment_transaction = $client.send(Pokepay::Request::CreatePaymentTransaction.new(
      shop.id,
      customer_account.user.id,
      "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
      100
    ))
    bill = $client.send(Pokepay::Request::CreateBill.new(
      "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
      shop.id
    ))
    bill_updated = $client.send(Pokepay::Request::UpdateBill.new(
      bill.id,
      amount: 200.0
    ))
    bill_payment = $client.send(Pokepay::Request::CreatePaymentTransactionWithBill.new(
      bill.id,
      customer_account.user.id
    ))
    assert_equal(payment_transaction.type, "payment")
    assert_equal(bill_payment.type, "payment")
    transactions = $client.send(Pokepay::Request::ListTransactionsV2.new(private_money_id: "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
      shop_id: shop.id,
      customer_id: customer_account.user.id
    ))
    bill_transactions = $client.send(Pokepay::Request::ListBillTransactions.new(private_money_id: "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
      shop_id: shop.id,
      customer_id: customer_account.user.id
    ))
    assert_equal(transactions.count, 3)
    assert_equal(bill_transactions.count, 1)
  end
end
