# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

require 'minitest/autorun'
require 'securerandom'
require "pokepay_partner_ruby_sdk"
require "inifile"

$client = Pokepay::Client.new(File.expand_path("~/.pokepay/test-config.ini"))
$inifile = IniFile.load(File.expand_path("~/.pokepay/test-config.ini"))

class ListOrganizations < Minitest::Test
  def simple
    response = $client.send(Pokepay::Request::ListOrganizations.new(
      "4b138a4c-8944-4f98-a5c4-96d3c1c415eb"
    ))
    puts response
  end
  def paging
    response = $client.send(Pokepay::Request::ListOrganizations.new(
      "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
      per_page: 3
    ))
    assert_equal(3, response.pagination.per_page)
  end
end
