# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

require 'minitest/autorun'
require 'securerandom'
require "pokepay_partner_ruby_sdk"
require "inifile"

$client = Pokepay::Client.new(File.expand_path("~/.pokepay/test-config.ini"))
$inifile = IniFile.load(File.expand_path("~/.pokepay/test-config.ini"))

class RegisterBankAccount < Minitest::Test
  def testRegisterBankAccount
    customer_name = "customer-name" + SecureRandom.base64(6)
    account_name = "account-name" + SecureRandom.base64(6)
    customer = $client.send(Pokepay::Request::CreateCustomerAccount.new(
      "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
      user_name: customer_name,
      account_name: account_name
    ))
    user_device_metadata = "{\"user_agent\": \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0\"}"
    user_device = $client.send(Pokepay::Request::CreateUserDevice.new(
      customer.user.id,
      metadata: user_device_metadata
    ))
    get_user_device_response = $client.send(Pokepay::Request::GetUserDevice.new(
      user_device.id
    ))
    assert_equal(get_user_device_response.is_active, false)
    user_device_activated = $client.send(Pokepay::Request::ActivateUserDevice.new(
      get_user_device_response.id
    ))
    assert_equal(user_device_activated.is_active, true)
    create_bank = $client.send(Pokepay::Request::CreateBank.new(
      get_user_device_response.id,
      "4b138a4c-8944-4f98-a5c4-96d3c1c415eb",
      "dummy",
      "ポケペイタロウ"
    ))
    bank_accounts_listed = $client.send(Pokepay::Request::ListBanks.new(
      get_user_device_response.id
    ))
    assert_equal(bank_accounts_listed.count, 0)
  end
end
