# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

require 'minitest/autorun'
require "pokepay_partner_ruby_sdk"
require "inifile"

$client = Pokepay::Client.new(File.expand_path("~/.pokepay/test-config.ini"))
$inifile = IniFile.load(File.expand_path("~/.pokepay/test-config.ini"))

class PokepayTest < Minitest::Test

  def test_that_it_has_a_version_number
    refute_nil ::Pokepay::VERSION
  end

  def test_get_ping_0
    response = $client.send(Pokepay::Request::GetPing.new(
    ))
    assert response.code != "400"
  end

  def test_send_echo_0
    response = $client.send(Pokepay::Request::SendEcho.new(
                              "Nl1Bo"
    ))
    assert response.code != "400"
  end

  def test_get_user_0
    response = $client.send(Pokepay::Request::GetUser.new(
    ))
    assert response.code != "400"
  end

  def test_list_user_accounts_0
    response = $client.send(Pokepay::Request::ListUserAccounts.new(
                              "c87f94de-ddab-4472-9581-0726155b9e2c"
    ))
    assert response.code != "400"
  end

  def test_get_account_0
    response = $client.send(Pokepay::Request::GetAccount.new(
                              "7e4f5483-076d-45ce-99dd-0c7b50bdc3b7"
    ))
    assert response.code != "400"
  end

  def test_update_account_0
    response = $client.send(Pokepay::Request::UpdateAccount.new(
                              "b63e1e5b-6f87-4d1d-a47b-0e2a0be252f7"
    ))
    assert response.code != "400"
  end

  def test_update_account_1
    response = $client.send(Pokepay::Request::UpdateAccount.new(
                              "b63e1e5b-6f87-4d1d-a47b-0e2a0be252f7",
                              is_suspended: false
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_0
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "398133bb-9e72-4c9d-a464-fd2c4a685a27"
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_1
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "398133bb-9e72-4c9d-a464-fd2c4a685a27",
                              per_page: 2563
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_2
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "398133bb-9e72-4c9d-a464-fd2c4a685a27",
                              page: 1648,
                              per_page: 6641
    ))
    assert response.code != "400"
  end

  def test_create_customer_account_0
    response = $client.send(Pokepay::Request::CreateCustomerAccount.new(
                              "a2a75eb4-cc83-49ef-9b6c-f50fb89f69fa"
    ))
    assert response.code != "400"
  end

  def test_create_customer_account_1
    response = $client.send(Pokepay::Request::CreateCustomerAccount.new(
                              "a2a75eb4-cc83-49ef-9b6c-f50fb89f69fa",
                              account_name: "RDyUU9m86va7mOYOnUCrif20yKwufMpmFFTdHKWioQpu02xs8evNj1BB86zHdb0RVKycElNVTSfU4OE6V5SCayo3DfyMrT4aaMFWyrc1hERNxTjzQPAoecnRNK8XaENPuqr1c7Y0QIUT19dhkK33D4s2dnTNvAjBoHemftaAK7YEX1r0TJG6eL9lOCcKfYlermnRFHPyV5yNE5WDVtPf7zsnqhlQlgLgRw8hJmMbKj2Ghow1pQ4g11O0f5sjm"
    ))
    assert response.code != "400"
  end

  def test_create_customer_account_2
    response = $client.send(Pokepay::Request::CreateCustomerAccount.new(
                              "a2a75eb4-cc83-49ef-9b6c-f50fb89f69fa",
                              user_name: "cnio6rs2WosaYFDsSenf7EO8YrTkZgo4UcutOHyqd6Q37kCNnvlKiuOGXRA5M10lzJqgTkE380jGHNjtymlBFaYwkaDARQXb89roTvH9hlonrfVuLHtIaDq",
                              account_name: "TjG6qeppzWDefffyegkrXwvRmUM7NdBetJQILswQyyIHyG0cQvyvi3fOp0yKO0hKjbZzDQ3pR6auD3BhoULOjAmeyJW8GOSoPilQGMGCv8agy1xS476vWSRBhNiVCSUAelLKMwm7ahsNHbJMUQMthhy2rrM8msNPEWKXNeiOmf8NQQAq3s33mIE6wduqos2zP7F0wlkJREl7"
    ))
    assert response.code != "400"
  end

  def test_list_bills_0
    response = $client.send(Pokepay::Request::ListBills.new(
    ))
    assert response.code != "400"
  end

  def test_list_bills_1
    response = $client.send(Pokepay::Request::ListBills.new(
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_2
    response = $client.send(Pokepay::Request::ListBills.new(
                              upper_limit_amount: 2603,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_3
    response = $client.send(Pokepay::Request::ListBills.new(
                              lower_limit_amount: 8076,
                              upper_limit_amount: 6525,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_4
    response = $client.send(Pokepay::Request::ListBills.new(
                              shop_id: "9cfb087d-842f-40bc-b803-54be0648d524",
                              lower_limit_amount: 9528,
                              upper_limit_amount: 8864,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_5
    response = $client.send(Pokepay::Request::ListBills.new(
                              shop_name: "PTvTwDHeLVJNQm6zO2n9lQR8CBAZfQb69CFYhenPlyn2dzEogO3iDA8MxBwmPq3z9RkeWCxVfOxAiHdsDAmtUCrNCXNmYd9v2E37pMJwO6ciU024pYDGySqmzpD8PIouf5QFbxEa1bxra0xaxNUVBarBTBBz7xfZyaguQ7QmKg77i78cGTkL",
                              shop_id: "666dea81-e266-439b-923e-60560b7c703f",
                              lower_limit_amount: 6781,
                              upper_limit_amount: 611,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_6
    response = $client.send(Pokepay::Request::ListBills.new(
                              created_to: "2018-02-27T17:05:39.000000+09:00",
                              shop_name: "pbQtZKgDncGnkTXbrvX6T0aAdkINb80R89Le2jQynVpGrj1LPQHBvENizF05bcoiwsYyR8HnlLKyqiYAnQoqWSU7oQH6d4feI7YQTRxRF7RqzsceO93SdKX7vhq3GOJv7yu37D3m5rPxBf13G3psVT0zheSckxETG1JcuOO1nmpAOHrm8jnUVFxnKniD4",
                              shop_id: "877998cc-2221-40f1-9e96-fa7ac6ab3e9f",
                              lower_limit_amount: 7861,
                              upper_limit_amount: 7791,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_7
    response = $client.send(Pokepay::Request::ListBills.new(
                              created_from: "2024-12-05T23:55:53.000000+09:00",
                              created_to: "2017-07-31T15:36:10.000000+09:00",
                              shop_name: "Yrn2xzKyMmj13jslBFtpn1GNGtwvL1xlHuM5atVM32FPHK6FvVacVODnGvcrUM4FKeO36tEGMubuPkOoXeMJmeI3yuZT2fXVJKvmGHyeFdmyqzQig1B7m",
                              shop_id: "91fc15ce-1196-4bd6-828a-29d201bd17b4",
                              lower_limit_amount: 8030,
                              upper_limit_amount: 7290,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_8
    response = $client.send(Pokepay::Request::ListBills.new(
                              description: "fXnWuxM4uaySpSHhpdF3",
                              created_from: "2018-07-15T12:59:54.000000+09:00",
                              created_to: "2022-09-08T23:41:16.000000+09:00",
                              shop_name: "Nkn8RPwjm6Wj65sWxf7VQ1M8HVt71k277fv7jmORdBmM5z7Jvj822JIgdAwx4b8OlNdw9PAuq8KdtCEDt1rnTl",
                              shop_id: "1e8427d1-39cc-49b5-b14d-57b8bc168aae",
                              lower_limit_amount: 6611,
                              upper_limit_amount: 4493,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_9
    response = $client.send(Pokepay::Request::ListBills.new(
                              organization_code: "4W0O",
                              description: "hnv8rFGwMTdVlGP6AenPOPf3",
                              created_from: "2022-01-09T15:55:59.000000+09:00",
                              created_to: "2024-09-22T22:23:42.000000+09:00",
                              shop_name: "Ljf4uVxozLm7xRGH1yzhrjFCkchVk5VyAWDImnQSXPI1xGj5vDymAsxuU8Cp7aq0smbLkU7QGufd2jb9MEiQT4UmcvzlBj795EkR1YrmW95fLdUzNmxF6htbV1S7fnLkPHVtBavJENtWE1sKOxFlIjaaIecYqE3IPUTUYKIYkbYXbj14IhHdgBf6NHUUUwYPsq9noNmspJ7Y1L8hRSahYD56ODinLm9",
                              shop_id: "c7ae8ea6-2ceb-4323-afd4-a22f428a1088",
                              lower_limit_amount: 5639,
                              upper_limit_amount: 2984,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_10
    response = $client.send(Pokepay::Request::ListBills.new(
                              private_money_id: "babcbacf-d1c0-4d83-a1a3-4819d41fb1ef",
                              organization_code: "YsSs-8-7",
                              description: "3FsZxe5mqVKvryNW2BSNSsJziXMKsga9DtMWrTUWBgQFnwzA3ZaUVPjhGi2Jq0ftpXCSxOVS79eW3zYRovvvcCko2ZmKsOXJdGuH3DdVCN09iXGCLwOCqGEWPrHN3JGGJM8F4zXZN5wXVYRG1VrygodEFLgppqeUULFog7tsdXtjqrJspJS7aQu7PSp",
                              created_from: "2021-08-03T17:15:21.000000+09:00",
                              created_to: "2024-06-07T16:45:52.000000+09:00",
                              shop_name: "qX3xSEyymjsHUnXHtJ0VaaSVKiSXxTNdfpj0MkNipnOkrOPkfONCHTd6DnVpQN93kE8LqGT7joHg0VmzbfLYH7RUeltxEPGho5PTRxMzLPZX4bzKgcUfwviT828vzIm8wDgW4bG2EJXZxUsYBvmRIH1CJ0AouW4hXrWX8ZcF3TopkfLYZMbEhWCbUtPGFucEJuUlsfzlnzhh0Ga",
                              shop_id: "cc07a70a-18c9-4c8f-b147-bc4ed06fb536",
                              lower_limit_amount: 9656,
                              upper_limit_amount: 7059,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_11
    response = $client.send(Pokepay::Request::ListBills.new(
                              bill_id: "xjQg",
                              private_money_id: "a036c01c-1018-43a8-bc5e-0dda00ff896b",
                              organization_code: "1--6V-F",
                              description: "Q866af1SHJPAtQzrJwXwD6WjibQA7RCw0DGtHlaab08poystEpf05YQ0IWDvU",
                              created_from: "2018-01-29T23:07:57.000000+09:00",
                              created_to: "2016-09-04T17:51:21.000000+09:00",
                              shop_name: "soyzHUShDT6OF9YTsujjgmyaEQuICGKD7nJBZRwYEvZ0N7qk5xFKmygCxZcOKJEi3soPaxH0W2tUEUkeIrlmidUZHNjRHlhIGVa9LiBfr9CM15ElZ0JFVfKETRHIzjgVVHCtt3raysmP5M7A2F0QIk8YWE12Ys4v3WDc9LQfC9s5BwKTaCZ8AomVmpE",
                              shop_id: "9dba187d-ad50-4413-b561-04595ac2034e",
                              lower_limit_amount: 3480,
                              upper_limit_amount: 1898,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_12
    response = $client.send(Pokepay::Request::ListBills.new(
                              per_page: 1771,
                              bill_id: "M2Nc4Y6fa6",
                              private_money_id: "e49c3c7e-a275-4544-85cb-a4225bbdd7aa",
                              organization_code: "e-W6--7E18f3-2G9",
                              description: "JjAEXr8h0XXU",
                              created_from: "2016-02-13T19:40:46.000000+09:00",
                              created_to: "2023-07-27T12:47:36.000000+09:00",
                              shop_name: "oRvnyQQSadlBCvTqlhI8ax4OjvHFsKHzTK1mRWyiNKX0unkaMGTgoIFVM5SVtdAFKJhfGVnsloVqR6QPfzFclRMY31rz2uOwPeGoOqSvkkz0Ek2y0X1NuwwgUnO0f4hh8WsF1vzSxm22fd8BX5MldZBWndHTpyjseadtkv3LOI0KA",
                              shop_id: "63f2170c-a926-4ec4-85bd-e5aee69f31c0",
                              lower_limit_amount: 4343,
                              upper_limit_amount: 3790,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_13
    response = $client.send(Pokepay::Request::ListBills.new(
                              page: 8295,
                              per_page: 85,
                              bill_id: "fmI4ei",
                              private_money_id: "709a2e5b-0b84-44b4-8b10-f3b73d8255b1",
                              organization_code: "bJiF",
                              description: "otjtsHahjh795f2xf44GZyUldko7lQGVa6fNJYFUnmaS9MQV87BawAJq0gUch",
                              created_from: "2022-09-27T13:55:55.000000+09:00",
                              created_to: "2025-05-27T20:35:31.000000+09:00",
                              shop_name: "pg09gSxRwI0wfh7KmmP61ZII739PFW2YJ1bXf9lg8YFUYEftI2WshTITERhO593V6",
                              shop_id: "3d32fc74-d1bd-4910-9122-ec3299a79a08",
                              lower_limit_amount: 9014,
                              upper_limit_amount: 5362,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_create_check_0
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 2826
    ))
    assert response.code != "400"
  end

  def test_create_check_1
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 3703,
                              description: "7SLcLbW4AxU0wtc5UoSZxvJXZZnXuox751FcqlB97JIz4ZfS74VMYaqP0cchWMub5ubXJiykhX4GuZAuS3ilHM"
    ))
    assert response.code != "400"
  end

  def test_create_check_2
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 4669,
                              is_onetime: false,
                              description: "QLZz"
    ))
    assert response.code != "400"
  end

  def test_create_check_3
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 2929,
                              usage_limit: 447,
                              is_onetime: false,
                              description: "twy2qZO5E5sW0lb7TPIAGyEvNHA3N91E3V5PmVcfezWazEOwtPaX0mzf790Siqv2AT4bCiDmw7bCQhBccpgK0xIl3fXPOn0Qadh1a2GBhIn8nj00b6Xe4ZUWBxjV0ci9XsuVyCI7yjny6oUgA0Nr"
    ))
    assert response.code != "400"
  end

  def test_create_check_4
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 484,
                              expires_at: "2024-01-04T05:51:23.000000+09:00",
                              usage_limit: 8427,
                              is_onetime: true,
                              description: "s4zmIXxyIo7776B2c7VPk73Cy17eXmVcYU0XMg5VAW4tYttRbDiZh1Ruxf5ejwan1KFeK0gIuH9Rt7KpOhUt398AlfetTn5IZkNorp8pniD6TAdtMN6q7q5c7jvnJCrfPZMCwhVmeXHRYsYtMJ7J6GCJbyTXHnD9m4vyBtYsm"
    ))
    assert response.code != "400"
  end

  def test_create_check_5
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 1754,
                              point_expires_at: "2024-01-06T03:31:04.000000+09:00",
                              expires_at: "2016-07-29T00:28:42.000000+09:00",
                              usage_limit: 9218,
                              is_onetime: false,
                              description: "j247nx1zMfzeC7jwHGrN6CbkGBBdJF0GOGvgkwtOi11uwP6W61bzuR6thpMmnE2tO4LJPotpVrwVk4XqQ7Fm7zJC48QxAs7R7"
    ))
    assert response.code != "400"
  end

  def test_create_check_6
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 8167,
                              point_expires_in_days: 9719,
                              point_expires_at: "2017-04-17T20:56:19.000000+09:00",
                              expires_at: "2019-11-10T20:04:17.000000+09:00",
                              usage_limit: 950,
                              is_onetime: true,
                              description: "zAGD79A5FCZa3E05RYUA40KpjAcARsEygDODVbmXFKntZL4TfMBN0rNdDTuq2rRQff89ug3zUIkr8NolX"
    ))
    assert response.code != "400"
  end

  def test_create_check_7
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 3777,
                              bear_point_account: "c259c3c0-b8cc-4631-b61a-44703efe21d1",
                              point_expires_in_days: 9569,
                              point_expires_at: "2019-02-20T10:27:40.000000+09:00",
                              expires_at: "2016-05-26T05:43:31.000000+09:00",
                              usage_limit: 7760,
                              is_onetime: true,
                              description: "mcs5UihcsbuF8ztvw"
    ))
    assert response.code != "400"
  end

  def test_create_check_8
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 9062,
                              point_amount: 6308
    ))
    assert response.code != "400"
  end

  def test_create_check_9
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 8008,
                              point_amount: 1991,
                              description: "5"
    ))
    assert response.code != "400"
  end

  def test_create_check_10
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 2755,
                              point_amount: 419,
                              is_onetime: true,
                              description: "EQiMMp0LltA9Y6uwO1xvpeUf8ntiGoxSjetCgOdIPOyZFSQErk96iimk9fFcyJZJF0dVOT3PEFA8YEq9VUl8baWmMvwuktkzSXRUXGCGj7hauiNt0X"
    ))
    assert response.code != "400"
  end

  def test_create_check_11
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 9571,
                              point_amount: 8417,
                              usage_limit: 6507,
                              is_onetime: false,
                              description: "Pf5NXHcEbr4HBzFAygFhNFTgzU0p9Y8mUupIGMevwnbrrm6cysDAEEOVoUfR1oOvBmKT0EDGA6BHgdoixjbW87gqrK0aMPukspyIXzfkCD"
    ))
    assert response.code != "400"
  end

  def test_create_check_12
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 708,
                              point_amount: 4110,
                              expires_at: "2018-02-09T04:08:35.000000+09:00",
                              usage_limit: 4417,
                              is_onetime: false,
                              description: "T7EFhBuonZmb0SVWPnGR0xLuDSMpEp3lIGSIthhQ5ayRUJoHyWFGGXbp3k6HcuYjofEYSZ0tAzD2KDzl69OWSJ1"
    ))
    assert response.code != "400"
  end

  def test_create_check_13
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 6389,
                              point_amount: 871,
                              point_expires_at: "2020-03-23T01:20:10.000000+09:00",
                              expires_at: "2023-02-18T05:39:22.000000+09:00",
                              usage_limit: 2206,
                              is_onetime: false,
                              description: "7EuhmvfgujCmvMFpPPwoRoI35E5EV8VXCw8DVeo5qRpcdGbP"
    ))
    assert response.code != "400"
  end

  def test_create_check_14
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 5108,
                              point_amount: 6006,
                              point_expires_in_days: 3781,
                              point_expires_at: "2025-03-02T21:38:28.000000+09:00",
                              expires_at: "2025-05-02T02:54:57.000000+09:00",
                              usage_limit: 4233,
                              is_onetime: true,
                              description: "wTy7LRMXZdfdR3TE4Fkug5MKNNOh86Nn8iI8cZTmeIRxYnenc8BpoKYbdf34JwduLpqspNhmrEOQhl8bs3uLWUBL5oF7v2kX4Gk2ycNapsTi6zw33Gb2A5qWNHaZOPC3pdhrSTrMnseWjsiLYwCjozJnoYJOm7w131o1WVCGHQh8XffC3IG08dLmD4T4LladirjXLl"
    ))
    assert response.code != "400"
  end

  def test_create_check_15
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              money_amount: 1450,
                              point_amount: 7863,
                              bear_point_account: "20ed2617-4612-446f-bcf4-cb8ad6e9f7ab",
                              point_expires_in_days: 6578,
                              point_expires_at: "2016-10-30T11:28:00.000000+09:00",
                              expires_at: "2024-05-05T13:16:58.000000+09:00",
                              usage_limit: 21,
                              is_onetime: true,
                              description: "4OPi8dV6Mksg9d1MnoTF4YDXB0fi8KmsRmZlc114zQ6YQmQRLoBgzou5xnQ8HtmEZVyXdtDvvikAZ5P4hN2TfroskaGPOaSEmOwAkhWSuoRLjibcdyh0viArPqgSQK2q9WCzZsiLWg60pqqTOI3GQ7n"
    ))
    assert response.code != "400"
  end

  def test_create_check_16
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              point_amount: 4133
    ))
    assert response.code != "400"
  end

  def test_create_check_17
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              point_amount: 3710,
                              description: "QaUkEwOI9d8ywgbNMiCrRucfKEgoVMUC1gponZ9Y5cJkSH8RvXFJ6QFyF4P5mZDcckCg1Ly7dMIiklrMl6OV9HaHAq7vrqjYNP"
    ))
    assert response.code != "400"
  end

  def test_create_check_18
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              point_amount: 5484,
                              is_onetime: false,
                              description: "2KEymCCaUrtCbSWeZMJbzm1uF2FvQvJKQOVxVojpWvCMAWgwous9IHMsBo7Oga7kNSv"
    ))
    assert response.code != "400"
  end

  def test_create_check_19
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              point_amount: 8575,
                              usage_limit: 4762,
                              is_onetime: true,
                              description: "98WoNbSLPQIbwLxMLsuRVCqRuyYwFrsNOlu3PCYfKnG9hKNSnQIwk0gudf9gpUfeQTatPFyNdRtz7C5Pgr1LrfT2nw6gjuyCmuXaMpSvGSDd8aEO1nqGkPiGfviPJOqxxhGGsg54j3vgKIFuRWjqPBNHMJgW"
    ))
    assert response.code != "400"
  end

  def test_create_check_20
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              point_amount: 4046,
                              expires_at: "2022-07-21T15:22:36.000000+09:00",
                              usage_limit: 8302,
                              is_onetime: false,
                              description: "opQ9JomyVLVE7SjhyB08cDzzWPlHsn0p7sbR0THSA2LsAI0DqP52Epbpswy0Y2VRdOo03LUvaOQNrtW2k9kwnyZZhsVGU11UNc4Lp43EywSmr16MgQuJGPwdTrqMdDvQ4UDEOFSRjG20XrRgEghOA"
    ))
    assert response.code != "400"
  end

  def test_create_check_21
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              point_amount: 1292,
                              point_expires_at: "2021-08-14T05:23:55.000000+09:00",
                              expires_at: "2023-08-23T02:26:35.000000+09:00",
                              usage_limit: 924,
                              is_onetime: true,
                              description: "RYSdC8IP8m8g9pgQVj186rzZ09KHrL0cDBcuZbCd5Zgn6JlKWqVwcQhaSSW9DuTPmTDBE7iEbjlpLfPW8lXbGB4iOaNyK9XvluKLBYxGBv35o6uqv6M760fHDPiWiBQ9"
    ))
    assert response.code != "400"
  end

  def test_create_check_22
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              point_amount: 4140,
                              point_expires_in_days: 5825,
                              point_expires_at: "2022-09-26T06:16:01.000000+09:00",
                              expires_at: "2018-10-02T16:24:14.000000+09:00",
                              usage_limit: 8650,
                              is_onetime: false,
                              description: "0osmiiY2x6KccravMg1CNqvF3lAJ6HwrMLQQqcd4doxnvegmXCVQnM0eP073wujKPptvpURiBykeyH0Qp5Pmt2EUUQiUzpr8dmu7nIgbHpnZsB9KbDnsEmd20bFBPurh3YFWHmzMQm4hkybgK2ABdcquuFFJygjVNNV03ttLDh9z0FOktbIRx5id3NkI"
    ))
    assert response.code != "400"
  end

  def test_create_check_23
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "7f6f0a51-ae80-4fee-a18e-b0d33731736e",
                              point_amount: 4958,
                              bear_point_account: "72f910f9-6d90-4d95-a501-de0f6685ba82",
                              point_expires_in_days: 8489,
                              point_expires_at: "2021-06-19T20:52:44.000000+09:00",
                              expires_at: "2016-05-04T11:32:00.000000+09:00",
                              usage_limit: 1543,
                              is_onetime: true,
                              description: "95GJKoUICTfpapN0pZkFHTeJirbdkPCxzTbSKVjW8UALFFZsZtc3tTF5R3BgYieUMIRUY9cjp3lE3R7uegkhWl0P2OnSopFUeAtT1lsTZgdSlqeTsNGuxDK3o0UcASWDGKOdQE3rUJL7sL4duIg6smxwzNQuGCIB40RmOn9ZBgi6ljQbVTy"
    ))
    assert response.code != "400"
  end

  def test_list_transactions_0
    response = $client.send(Pokepay::Request::ListTransactions.new(
    ))
    assert response.code != "400"
  end

  def test_list_transactions_1
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              types: ["exchange_outflow", "payment", "topup", "exchange_inflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_2
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              is_modified: false,
                              types: ["payment", "exchange_inflow", "exchange_outflow", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_3
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              private_money_id: "6aba2900-b77a-4ad8-9bd3-3309e29116c6",
                              is_modified: true,
                              types: ["topup", "exchange_outflow", "exchange_inflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_4
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              organization_code: "f7--h--g5----29Tc-1Ui",
                              private_money_id: "93e85ab6-6f38-43af-85f6-d44858149f30",
                              is_modified: true,
                              types: ["exchange_inflow", "payment", "topup", "exchange_outflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_5
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              transaction_id: "4e0230f7-6aaa-43a6-ab5f-084c289716ee",
                              organization_code: "---9Z3-S-hZ5dz5p",
                              private_money_id: "4e2061e2-af4a-4e33-aa0f-918aec97c0a0",
                              is_modified: true,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_6
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              terminal_id: "1c11526e-314a-4df4-8185-e45b923674c9",
                              transaction_id: "e69f92ec-9a33-48d3-bdc8-b1e51be732bd",
                              organization_code: "2-99RWQhP0",
                              private_money_id: "6ad70707-b7ac-492b-a79e-a53ffb4c8e4d",
                              is_modified: false,
                              types: ["topup", "payment", "exchange_inflow", "exchange_outflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_7
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              customer_name: "JLPseAOuneEeyaFtTL",
                              terminal_id: "77713bd4-6e4f-425b-a926-c2ad5fd492a6",
                              transaction_id: "17ae69e7-d3d2-4d40-8cd3-f752e10aeca6",
                              organization_code: "uL-x-JZFu9--1-8t1fw5-L-ez-7bE-93",
                              private_money_id: "2588fd52-93ca-424a-b7b8-3d95b72e5c0b",
                              is_modified: true,
                              types: ["exchange_outflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_8
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              customer_id: "2f976423-1037-40bc-ab49-cf28c0484d7d",
                              customer_name: "Xi40xKboOpwMBA6q2Kq0tZyiUADbVC5RlkJaJYoDAx0qsmOw7PHNnFExkxpvXAUYuDOojIgTFGfzftBIB9n3ML28plPczoapwx0oKJi422pTgRpCnTqjs4ltQ42WYsD2EiQHH",
                              terminal_id: "4bc0aba8-1f52-4ad0-a194-0ffaad6ec15d",
                              transaction_id: "a5afc0d6-7b19-4e4f-a083-c11dd19f737f",
                              organization_code: "1-l2-5-f-Qab-696-P0J2-93",
                              private_money_id: "a45a40a4-87ae-4891-8ee1-69d8e8ec32e0",
                              is_modified: false,
                              types: ["topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_9
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              shop_id: "11848c03-cf15-4958-bc72-f061e33be87c",
                              customer_id: "f1875a2b-5012-4612-ac55-bf5f154a18a7",
                              customer_name: "w6Q03NBpunlH27fuwS062dyUhdaauFK05G7j7DtbQlQj7uhdvBC8SNV9N06DcicsW7T4v75EcsFZhLW08CtfQJbeMeGrfLI8vhe2bLsFowO0DGDYLDm9MOt4SL8Y7PvjarsyCv3xwpYdvLUHw6pAUTSY6OF22aUfYlDkx",
                              terminal_id: "1c002f3b-3105-4669-aed4-bf38c422d58b",
                              transaction_id: "338a1fd5-2f16-4506-827d-aca8fa334d58",
                              organization_code: "Tmq83-4VT-uBs-w1HpN0E-q-Lj",
                              private_money_id: "c637883d-8a85-445d-8b2d-1bc79cf8752d",
                              is_modified: true,
                              types: ["payment", "exchange_outflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_10
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              per_page: 5431,
                              shop_id: "05a6565b-dcf7-4ac6-abd2-7da45ab93431",
                              customer_id: "c2283c17-3acb-4eba-b681-3751d7256c8b",
                              customer_name: "upYBfVKGcpxdNEwr6YTyPgcFAf5nehWoZL5txQnKJuh9KqEqUue1EEC2hyAjzmh2hFVxJeSk4lbF4AlWuhFbretUaOqrQnOLMWnPZ1de5nTQdD9cc87uKKgOIKl17TVT6HoOGDPOgRpiltjusOIBmoJaNF7Mk6CEwIWFXevBiuHTMQVh4IZisV3GKFtSGoh1xFZ8XXPOeH1ehKijrC7bAqneUdmAzA4Y",
                              terminal_id: "c333d9fc-9c83-4b89-a394-c7bbc90b8310",
                              transaction_id: "32f9b257-c31f-474e-a824-de63d9a01961",
                              organization_code: "",
                              private_money_id: "21340506-02a6-44b3-8299-19ce57a168e0",
                              is_modified: true,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_11
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              page: 1056,
                              per_page: 2218,
                              shop_id: "0248de81-a6cd-41c3-b43f-b697234bf800",
                              customer_id: "e58d32bd-2769-4edf-912f-2a2b4a82e018",
                              customer_name: "esHiiZMVLYAPy5uJhalG3DP56TxLzzYo0HiQWqDGuWNbgBe8Dky1Jz5vn8xQKoD2vspqjVtIHassozWItV35n2bY6KlC",
                              terminal_id: "6a102401-8ac6-4079-a226-737afbb239d4",
                              transaction_id: "fcedda1d-ee01-470a-a11a-cbf1e6d6f950",
                              organization_code: "X4kk4mkX--JfS-i-X-1r3-R273Bk60-",
                              private_money_id: "8646287a-3ec0-4aa4-bcb9-a6b4a636ae0d",
                              is_modified: true,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_12
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              to: "2016-08-14T13:51:09.000000+09:00",
                              page: 7020,
                              per_page: 7968,
                              shop_id: "b54409d6-c9f1-4dd6-9d1d-0d2fafbe1826",
                              customer_id: "e385317a-5249-4dba-88fd-cc2c167dccce",
                              customer_name: "ekGvAku3blVA3s8WIMQFXX2s0hPQMwcfbWgol8t7zOcYd6DlEg0jznRVL7FFJpolZuRDa5K4RWMZ0KfZico0mEW8HqEhjjDsMer67YSb3XxZL1t4eBblolqVRGqcj4nqMRchU",
                              terminal_id: "37eb8295-7776-4646-b92d-2557b18cd91a",
                              transaction_id: "15fb2a70-abd2-4f11-b595-d7c716f3a009",
                              organization_code: "-",
                              private_money_id: "d58396e2-8104-46c4-a469-a45723366545",
                              is_modified: false,
                              types: ["exchange_inflow", "exchange_outflow", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_13
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              from: "2016-09-18T12:00:14.000000+09:00",
                              to: "2023-08-20T05:08:23.000000+09:00",
                              page: 1705,
                              per_page: 8326,
                              shop_id: "be28142e-c12d-46f2-95c0-fbd2994f0369",
                              customer_id: "5e654608-abc1-42e1-842c-92be336148c9",
                              customer_name: "v9I9PYGh96eqzDfhyMDSWh0rCeVTWDZoWJ3VMe0C1pHAzJlGhMtsrNJdc4sL8YXU7i9RN63mAbkwxHvX9ctXsfSBInkCdh39VgubWAworbLsl2hqqw0hZksK6UysTgxiMn9HsgMuNuHHOHOHV50MYeOHWlOJRZrHUukBcOS7OKCR98W",
                              terminal_id: "2f26cc2a-55d0-49eb-92da-469340770887",
                              transaction_id: "e8921989-44ef-4019-b169-1bc9aaab9f14",
                              organization_code: "hw666TG-eao0h9M",
                              private_money_id: "7635b012-4831-4b95-8870-7609731bdf7e",
                              is_modified: true,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_create_transaction_0
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "6cedea7b-9006-46fa-8159-e4edc2c8b122",
                              "19c5a776-465c-4512-8dbb-f722d5f8ef10",
                              "253b5855-0f84-4310-8076-34afefe3cdbc"
    ))
    assert response.code != "400"
  end

  def test_create_transaction_1
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "6cedea7b-9006-46fa-8159-e4edc2c8b122",
                              "19c5a776-465c-4512-8dbb-f722d5f8ef10",
                              "253b5855-0f84-4310-8076-34afefe3cdbc",
                              description: "CSx7JtgU5Xt71arodxPMBhietTf9N6j013qZFuqs6Rml2teD0LlEFVjHuG6UyixNLTeNqWfqNBx94UqwSvEGgDecmd6BsjFmkEOsvaoxOII4avIAZBLs2YWRyAxy2F4ZivQ8HR8gCDU7GCuPAwzlsTJXxgArj8vCadn2ighhI"
    ))
    assert response.code != "400"
  end

  def test_create_transaction_2
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "6cedea7b-9006-46fa-8159-e4edc2c8b122",
                              "19c5a776-465c-4512-8dbb-f722d5f8ef10",
                              "253b5855-0f84-4310-8076-34afefe3cdbc",
                              point_amount: 941,
                              description: "9PZQYj1eCvzqja6lshw9nhgXqtykRaZkwwVODjPQU04ix39qJHQs15gIsZemqNjfdFSubc95K2Iry0FJhV0QzAhvOLMSkMqm65JCPjAyQd3i5HXos0G4r7HWK5UFsageAjEWKkx760ay3zuZfjuEebwfE59ryOrJAXZM2MywGdQOjeA"
    ))
    assert response.code != "400"
  end

  def test_create_transaction_3
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "6cedea7b-9006-46fa-8159-e4edc2c8b122",
                              "19c5a776-465c-4512-8dbb-f722d5f8ef10",
                              "253b5855-0f84-4310-8076-34afefe3cdbc",
                              money_amount: 5209,
                              point_amount: 9894,
                              description: "uYVcAmC1FGtO6DlpjZJxY2SNmEaiUnvh3w7pVB0aK9iBSGMC9ANwY9SOT43pqMv02WEtGB9nq5b"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_0
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "9610ac87-205e-4591-8431-378c5452ec33",
                              "5594973f-9351-428d-b06e-d16d78caa476",
                              "a07d6090-4b0e-451d-b0da-989aa2220446"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_1
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "9610ac87-205e-4591-8431-378c5452ec33",
                              "5594973f-9351-428d-b06e-d16d78caa476",
                              "a07d6090-4b0e-451d-b0da-989aa2220446",
                              description: "DDbtyHlynbfGS1uit1IcHJAepTAA4H4QzT2A5wkYnSqdDIiEOPbW0rfbazTi1JimphX5I3USIjvequex31s46WxbH2MpKXk4PxBzrDeQ2em0ZtlKS5ZP9kQ8Qw9gNdZDHDENxEZjFq89zPN"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_2
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "9610ac87-205e-4591-8431-378c5452ec33",
                              "5594973f-9351-428d-b06e-d16d78caa476",
                              "a07d6090-4b0e-451d-b0da-989aa2220446",
                              point_amount: 3941,
                              description: "sfypA6jdOdVB5NtSJezfmHNymvaniQKnfijXuemNFBrFJr7II1SdYYxI1hw1LunDjZrI6XvPy8JTVCVXwIx1DnDmcgCX7qjnuR3jIZapxw7FfYehKJUmVV2hpxk8cNv3L6Ltu0vpwW5ZztmNio0Ue"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_3
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "9610ac87-205e-4591-8431-378c5452ec33",
                              "5594973f-9351-428d-b06e-d16d78caa476",
                              "a07d6090-4b0e-451d-b0da-989aa2220446",
                              money_amount: 5834,
                              point_amount: 1623,
                              description: "wZN"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_4
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "9610ac87-205e-4591-8431-378c5452ec33",
                              "5594973f-9351-428d-b06e-d16d78caa476",
                              "a07d6090-4b0e-451d-b0da-989aa2220446",
                              bear_point_shop_id: "53d7511d-9230-4071-bc44-0326ebf85ff9",
                              money_amount: 8697,
                              point_amount: 622,
                              description: "LsVui9vfdcmt8anGvMqN4t"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_with_check_0
    response = $client.send(Pokepay::Request::CreateTopupTransactionWithCheck.new(
                              "5e4c7751-15a9-4ba3-a162-9a21a098aaab",
                              "b4ac900b-085c-4431-879c-b93d794512ad"
    ))
    assert response.code != "400"
  end

  def test_create_payment_transaction_0
    response = $client.send(Pokepay::Request::CreatePaymentTransaction.new(
                              "72c9bee1-88dd-4754-b3c8-be8a20f2a720",
                              "94b45a3c-c7cf-4d7a-934f-2fe87f670457",
                              "169a0ac6-e766-409a-ac4e-c9a3af996bba",
                              8369
    ))
    assert response.code != "400"
  end

  def test_create_payment_transaction_1
    response = $client.send(Pokepay::Request::CreatePaymentTransaction.new(
                              "72c9bee1-88dd-4754-b3c8-be8a20f2a720",
                              "94b45a3c-c7cf-4d7a-934f-2fe87f670457",
                              "169a0ac6-e766-409a-ac4e-c9a3af996bba",
                              8369,
                              description: "gkJegIUjInsH3qvZrJyAzIHZYxt0ojqC1NmE7i7ajiwCJ4lIpjT8wkCyzHu8WG60xVBUPoQHiVLCTAZy35qIeQOU0sxyQTKZ6zd5qHr3WJw6zB3Z79M6LzNeNjWnnQccEfWHc7fuUeoTVhqFDGe0fib1hEeOde11HUgJMSDhnCzjS7BXhheDsvbNTNP"
    ))
    assert response.code != "400"
  end

  def test_create_transfer_transaction_0
    response = $client.send(Pokepay::Request::CreateTransferTransaction.new(
                              "15508114-e18c-4324-9900-e9d2b3fe03c2",
                              "78c36a6f-9886-468d-a38b-4ca15185d77c",
                              "24ad8ba5-bf85-4714-93e3-fc893314fbd5",
                              1845
    ))
    assert response.code != "400"
  end

  def test_create_transfer_transaction_1
    response = $client.send(Pokepay::Request::CreateTransferTransaction.new(
                              "15508114-e18c-4324-9900-e9d2b3fe03c2",
                              "78c36a6f-9886-468d-a38b-4ca15185d77c",
                              "24ad8ba5-bf85-4714-93e3-fc893314fbd5",
                              1845,
                              description: "xdvGKxpeI0RgN8AHIgFSqAwfleuSFm3A3lRVacITpf4WjuOg90rwpGXEvJbMCWjomS7VWRpAOvOPzpWeySTgq1p9plDMERIYcDLlUSYEOlAwnHrxdKGIVj"
    ))
    assert response.code != "400"
  end

  def test_create_exchange_transaction_0
    response = $client.send(Pokepay::Request::CreateExchangeTransaction.new(
                              "f910b9ee-7aa9-4e08-8ada-a2dd002475e6",
                              "badd4aa5-aaf2-476e-a2b8-50e64cd241e5",
                              "00f84502-cdc9-4abf-98ca-6974b7e84ae2",
                              8828
    ))
    assert response.code != "400"
  end

  def test_create_exchange_transaction_1
    response = $client.send(Pokepay::Request::CreateExchangeTransaction.new(
                              "f910b9ee-7aa9-4e08-8ada-a2dd002475e6",
                              "badd4aa5-aaf2-476e-a2b8-50e64cd241e5",
                              "00f84502-cdc9-4abf-98ca-6974b7e84ae2",
                              8828,
                              description: "KHVgaNdFeedRzzEg57KfQuP9PUmhoY3qG3sASix7yGZCOHf3PJQaAmeXt8NA1mIn9O"
    ))
    assert response.code != "400"
  end

  def test_get_transaction_0
    response = $client.send(Pokepay::Request::GetTransaction.new(
                              "4754354b-57f6-4ce2-822b-d9c2b57c8af1"
    ))
    assert response.code != "400"
  end

  def test_refund_transaction_0
    response = $client.send(Pokepay::Request::RefundTransaction.new(
                              "728e0521-3f3a-42cb-9914-d00b38cd8715"
    ))
    assert response.code != "400"
  end

  def test_refund_transaction_1
    response = $client.send(Pokepay::Request::RefundTransaction.new(
                              "728e0521-3f3a-42cb-9914-d00b38cd8715",
                              description: "Lwaxyq9ygIm77eMQWVoSi5LVcqYMNfKNfNDHgB4qiFjkW74bzcmPbWwHr4SR5PIeVsjaVExnLWQrBytYUUmtnwkjzllN01yXeD3c5OmZMAet8PgInR39RUe18hs5u8S5lQL5zkn3JrEecd33KQl2"
    ))
    assert response.code != "400"
  end

  def test_list_transfers_0
    response = $client.send(Pokepay::Request::ListTransfers.new(
    ))
    assert response.code != "400"
  end

  def test_list_transfers_1
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              transfer_types: ["transfer", "exchange", "payment", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_2
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              transaction_types: ["exchange", "topup", "payment"],
                              transfer_types: ["topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_3
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              is_modified: false,
                              transaction_types: ["exchange", "payment"],
                              transfer_types: ["transfer", "exchange", "payment", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_4
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              private_money_id: "a92d48e9-ef24-4e75-a957-1f1cee8fb82b",
                              is_modified: true,
                              transaction_types: [],
                              transfer_types: ["transfer", "exchange", "payment", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_5
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              transaction_id: "1ca3cc47-390c-4000-ac75-3848f64028fa",
                              private_money_id: "b8016fcf-0232-4671-a0de-faa71b6653b4",
                              is_modified: true,
                              transaction_types: ["payment"],
                              transfer_types: ["exchange", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_6
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              customer_name: "PHURuyBNIOzCdPLzRa0VnHi80UbGG6iHJMRpttSUoetbBifDml5PaxvUUv2zhL22OcCHM9iiESAxdg9fAVMBcHhKiCOYR0NFbwO2XSCoNMLrVjfhx38Ud9kf8Xkc76hVvOn2wxvatlfOEvQBri1gsd5Kl4TKxNKCELBYkeD81lV21RRcJUBzh8FedRHdRGO7FoP9KN1DiDR8RxTbALm0jHS4l",
                              transaction_id: "63e6730b-3920-4b22-8a37-e3490fd5b9d4",
                              private_money_id: "9c62ff73-c14d-45cc-bfbf-c87cb545395c",
                              is_modified: false,
                              transaction_types: ["transfer", "topup"],
                              transfer_types: []
    ))
    assert response.code != "400"
  end

  def test_list_transfers_7
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              customer_id: "67dd26a4-43db-44d6-873d-4e567ec5954f",
                              customer_name: "uecgxaXHfi3CCJNFdTEPP78dVEPSlJZ96pZwD3QmjHzfYLFeQhBEh5RslrI02TQhAUzQUnxTL3w9DksmksoORk08RYMhDbRWAAMnZxXbyABe6Qo6vDpoeQZhulYg1P",
                              transaction_id: "40aefc2f-20f9-4503-bbed-49ab317370d6",
                              private_money_id: "ccfab54a-fc26-40b3-aab5-9a22014738ba",
                              is_modified: false,
                              transaction_types: ["transfer", "exchange", "payment"],
                              transfer_types: ["exchange", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_8
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              shop_name: "bJO0SmLo2MOIL6DQMRHhj0IWO3SBTHYo6hMHhmN5pq6WSxPX2tN48dynYpeqdBOwQyWHD3DlUIPHQAZAdLRcrWWr1EnuT0S1YKaV8cknoXfUnLyrKYNf7Ej5JpuuM1bG2qBk6oQTMDmmP8nbHoXJqatZfMSG8QEGDdZ7W1esKZXNL3t6kUwAeF4mbCHkxnWx",
                              customer_id: "753aada6-476f-4c62-85de-868930fd89f0",
                              customer_name: "DsoC8yAWmLo7AVTp",
                              transaction_id: "41ccbb02-8f85-4fd2-a398-97b078427cdb",
                              private_money_id: "693c1732-ef29-4b3b-a672-9c8bc75fd7ef",
                              is_modified: false,
                              transaction_types: ["payment", "transfer", "topup", "exchange"],
                              transfer_types: ["transfer", "exchange", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_9
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              shop_id: "4a091fbc-d5ee-46e6-9c96-c10bcd020dda",
                              shop_name: "WDWpn1cOI6lv64aPDi7jLv12fL0JjCcy2HKEOCKura5gEE2TI8Vlgi5FjDwYnkYOjUhLiOKQTYu4xSgy6AZAVHRC9XDKYHqggReARvYPMtqcHtUm28ChPNURqNPsGKRIY22pcz",
                              customer_id: "e4f0a096-3c94-49ed-a805-2d3239c24540",
                              customer_name: "QsFjLC",
                              transaction_id: "806feee8-3851-4501-872b-0c5ae4979084",
                              private_money_id: "e557dc93-0b16-4aac-b806-87eaf1ea6374",
                              is_modified: false,
                              transaction_types: ["exchange", "transfer", "payment"],
                              transfer_types: []
    ))
    assert response.code != "400"
  end

  def test_list_transfers_10
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              per_page: 879,
                              shop_id: "698462e4-315a-424c-bcf7-6707474a2298",
                              shop_name: "r38RJyhNfMHtFsamtnKQl8KVcf8HlR7oznQCLTLQyJy72Jj1P3TI5Rl8QGsojaG4zFyGZhFxSSJt0WDBf1NZIKrNC0A5sKYjB446AHzx",
                              customer_id: "8fe4f57f-0e66-4fda-97a6-3595742ddf11",
                              customer_name: "MTZfNnKi7sYiDArZxwfJoSWVnDw2ZboEyvpOtGcwZkcVUEZcnKZHa05QzfKmvb4EkDZ9TG2yBJKLGfRdXH8uIfayG5YtEPP4vaNiJevr0nGmzoCJ6wEyyN4hD0IcD5suO8GTCv4aRmLNRzLnZjd2undIkNl9IhLbd3YIWES03BQEWMaTXV8mj847GI9vdw9LDNUZp6z2QTJ8ZgbN64MKOy1BvI2wdQVsu1K",
                              transaction_id: "2cebc271-e0f8-4cbd-b473-66068e505b75",
                              private_money_id: "55c17801-429f-4a63-9147-c203691d7451",
                              is_modified: false,
                              transaction_types: ["topup", "transfer", "exchange"],
                              transfer_types: ["exchange"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_11
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              page: 802,
                              per_page: 968,
                              shop_id: "2e7bf881-6152-48e5-9db0-2896892eca87",
                              shop_name: "xs2PijIqO9ycYtwsTPpKP3ktIEHjl6u08TAtMWu17Qj2puufOrgdikwhgrv4ACImaPXEBxyc59xBAWA487dEEIHUgrho35GhR7uPLdbJhvLuuTyyYuJmK7awz3JFxQ5VpH2kZB3OKvwu7jyjwadHcpu3bWB",
                              customer_id: "271a540b-e1ee-4ea1-83ae-3f1bc77d0c97",
                              customer_name: "dA6xGHCytNN8ZbWzHj5cn9xVMhJ8zGV9Tc0OxG0grojHBvqqE2wbFNDiPZ5hhOl7O9f8t28fL3x32mfrOJtrSaXpWxTaaiOAM8uWf3kB2jRPnQkWUlE6htHjMZNEQ99v8Kd6xJzi4CR8Covrb9GTBIv2ufwd96nQesVQZrmjDOdwJNQs28XN4puQHbahZ3B1Kz5vgUXMDGutcQodPO1kZm3rwCZqMRT",
                              transaction_id: "2972813d-377c-433f-a73e-b069f8501b5c",
                              private_money_id: "68b9445f-2d2b-43f5-bff9-e5a23a670748",
                              is_modified: false,
                              transaction_types: ["topup"],
                              transfer_types: ["exchange", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_12
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              to: "2022-10-21T21:34:08.000000+09:00",
                              page: 1341,
                              per_page: 5330,
                              shop_id: "baa88e21-7467-4029-90e0-a8388a55e5aa",
                              shop_name: "aQxZ6Ae1aDw1PfXPHKafogdsZiqmnWvAbdwC2qGi0TMOCaDkiNBbdNvnH3qOSfYgLolA7OqEe2aRMc74WPcRXgT0vgolzXqVddWlygSLDIb9O17CEr1xUYvitdKc6tFbTBvlax7sdGm8FgzI250z4hH9TnhfmDFiO4ku9QB3vNrB1TcWopVp8",
                              customer_id: "a0346818-b1ad-44e2-b202-4442dc1da3d5",
                              customer_name: "HaXAc9KeCNGoGNBcHT27QbaNJgLbf6jn2lZHjfNGlA7n8VXJIISvIkelumKA6TZO6qaQ8W998JCj1FB1BacPw2JdLzPnn27P3FTy0SmvWZB7i7w2VF9o952oMuJ7dz9OHu9vbTEMUKVks8ZAv2Js9B6SwWg898kojuFKlypJJfFSCoUT999ChfqYMJhF31UYnF2EPpPHebrOK93uMOq0lnqY0u90z",
                              transaction_id: "f527c775-3c21-46df-beda-8f8bdbac561d",
                              private_money_id: "eaf39117-3297-4799-a390-1e7ca6359af2",
                              is_modified: false,
                              transaction_types: ["transfer", "exchange", "payment", "topup"],
                              transfer_types: ["exchange"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_13
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              from: "2018-05-18T20:15:08.000000+09:00",
                              to: "2022-10-03T22:51:45.000000+09:00",
                              page: 9992,
                              per_page: 8106,
                              shop_id: "de4e44db-4f3c-49cc-8271-179248a92e93",
                              shop_name: "aCMVSxbwu7yped4xE7ed5ZXppRjgNVVvvT8XZjeFoLsDN7wZyVCgGDZfQxC9PCmEKYJ6ZM9maV7E7oZ",
                              customer_id: "91eb4123-43fb-4cfd-bd6c-d73c3b3b723e",
                              customer_name: "Yjte955tACiV2RO5Gdcv1CFKk3yLn0MouP4OKuMPxDINpgRygQfddSS3YsNYGu3JcUrmdpMPHJmmorLyQ77Szm4YyP827eF",
                              transaction_id: "e7cd53d6-99b7-49d1-b97e-be699bd417da",
                              private_money_id: "df21574d-561b-4c8e-baac-c49d57b37874",
                              is_modified: false,
                              transaction_types: ["exchange", "payment", "topup"],
                              transfer_types: []
    ))
    assert response.code != "400"
  end

  def test_create_organization_0
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "JMa0ooImAYC1hyal1",
                              "hows4nThdzS0B1izbNEUviCdQnmNtIHnoSYv3h6kEA8DsJAvsM1hNyqhxGswxkzrcov63mC0gkM6p5BHcTk5FsevKpNab25lIBO7OGSWsvmzY7uoxIl7LXTMyR6TpwUrQidnlSgjS3m7qscxxuC5KDgmC4netplhv3cSSPrt9Nmqng9uJoPckKT1H2PyRZJOT7jFk6oKYpbHFrJ8TXs9EMwZJYyI8zypwcBga2nofDphBhsfxPDiwrm3Y3J2Yu2",
                              ["c0ae550f-23e1-490f-950d-3c4e961a5a74", "4773e974-992c-4bcd-86c4-848a9cd13e72", "7a6361ea-2c5d-4adc-801e-7a36defe7f96", "fbcba7e4-803c-400d-b70f-11e251689694", "468f34c2-8f7f-44ac-8343-ded81a590265", "c7009b81-19a5-4c44-accd-784c993ffdfb", "b89e3904-ff10-45b6-8efb-cb8b469db2c4", "e807d42b-8628-4c02-b96c-23266a58fb49", "149f7024-2ed3-434c-8698-c8aba25e251e", "fe8e0937-3222-4fe6-ab10-59850b92cb03"],
                              "0Yp5wiNSBK@e1ON.com",
                              "LqdftAsYYY@VkCU.com"
    ))
    assert response.code != "400"
  end

  def test_create_organization_1
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "JMa0ooImAYC1hyal1",
                              "hows4nThdzS0B1izbNEUviCdQnmNtIHnoSYv3h6kEA8DsJAvsM1hNyqhxGswxkzrcov63mC0gkM6p5BHcTk5FsevKpNab25lIBO7OGSWsvmzY7uoxIl7LXTMyR6TpwUrQidnlSgjS3m7qscxxuC5KDgmC4netplhv3cSSPrt9Nmqng9uJoPckKT1H2PyRZJOT7jFk6oKYpbHFrJ8TXs9EMwZJYyI8zypwcBga2nofDphBhsfxPDiwrm3Y3J2Yu2",
                              ["c0ae550f-23e1-490f-950d-3c4e961a5a74", "4773e974-992c-4bcd-86c4-848a9cd13e72", "7a6361ea-2c5d-4adc-801e-7a36defe7f96", "fbcba7e4-803c-400d-b70f-11e251689694", "468f34c2-8f7f-44ac-8343-ded81a590265", "c7009b81-19a5-4c44-accd-784c993ffdfb", "b89e3904-ff10-45b6-8efb-cb8b469db2c4", "e807d42b-8628-4c02-b96c-23266a58fb49", "149f7024-2ed3-434c-8698-c8aba25e251e", "fe8e0937-3222-4fe6-ab10-59850b92cb03"],
                              "0Yp5wiNSBK@e1ON.com",
                              "LqdftAsYYY@VkCU.com",
                              contact_name: "3DcEBNgTqlLFzglIi9gAX2qWkeG3nrHMUjIWpiHe43yaApDvtuABbIErjI3mzpMZp4MZ5rb7Pph3dr3zTts5bdpt18m9Gw5G8LO2K7kKw8tOeRfx6H1bJZwys4mgtizwHZs5aEWeGZZzwWWy2b3ZKpBtHziGm8rBreuKzsr3UQxED0fXRtiFgUPkgrV5ivI8xTCi0x9m1LqmwhZa1sX82y7CxWpPXKVZzT6YHPBNSbse1HhvcC"
    ))
    assert response.code != "400"
  end

  def test_create_organization_2
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "JMa0ooImAYC1hyal1",
                              "hows4nThdzS0B1izbNEUviCdQnmNtIHnoSYv3h6kEA8DsJAvsM1hNyqhxGswxkzrcov63mC0gkM6p5BHcTk5FsevKpNab25lIBO7OGSWsvmzY7uoxIl7LXTMyR6TpwUrQidnlSgjS3m7qscxxuC5KDgmC4netplhv3cSSPrt9Nmqng9uJoPckKT1H2PyRZJOT7jFk6oKYpbHFrJ8TXs9EMwZJYyI8zypwcBga2nofDphBhsfxPDiwrm3Y3J2Yu2",
                              ["c0ae550f-23e1-490f-950d-3c4e961a5a74", "4773e974-992c-4bcd-86c4-848a9cd13e72", "7a6361ea-2c5d-4adc-801e-7a36defe7f96", "fbcba7e4-803c-400d-b70f-11e251689694", "468f34c2-8f7f-44ac-8343-ded81a590265", "c7009b81-19a5-4c44-accd-784c993ffdfb", "b89e3904-ff10-45b6-8efb-cb8b469db2c4", "e807d42b-8628-4c02-b96c-23266a58fb49", "149f7024-2ed3-434c-8698-c8aba25e251e", "fe8e0937-3222-4fe6-ab10-59850b92cb03"],
                              "0Yp5wiNSBK@e1ON.com",
                              "LqdftAsYYY@VkCU.com",
                              bank_account_holder_name: "/",
                              contact_name: "fCPPOOlGnXuhftuEWRtVAcQSyxnpseWeCdbT1vG7NRh8oWT8srSlZzvpMHSQuXz9II5PwW6FTnFbIQTrErYkaG"
    ))
    assert response.code != "400"
  end

  def test_create_organization_3
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "JMa0ooImAYC1hyal1",
                              "hows4nThdzS0B1izbNEUviCdQnmNtIHnoSYv3h6kEA8DsJAvsM1hNyqhxGswxkzrcov63mC0gkM6p5BHcTk5FsevKpNab25lIBO7OGSWsvmzY7uoxIl7LXTMyR6TpwUrQidnlSgjS3m7qscxxuC5KDgmC4netplhv3cSSPrt9Nmqng9uJoPckKT1H2PyRZJOT7jFk6oKYpbHFrJ8TXs9EMwZJYyI8zypwcBga2nofDphBhsfxPDiwrm3Y3J2Yu2",
                              ["c0ae550f-23e1-490f-950d-3c4e961a5a74", "4773e974-992c-4bcd-86c4-848a9cd13e72", "7a6361ea-2c5d-4adc-801e-7a36defe7f96", "fbcba7e4-803c-400d-b70f-11e251689694", "468f34c2-8f7f-44ac-8343-ded81a590265", "c7009b81-19a5-4c44-accd-784c993ffdfb", "b89e3904-ff10-45b6-8efb-cb8b469db2c4", "e807d42b-8628-4c02-b96c-23266a58fb49", "149f7024-2ed3-434c-8698-c8aba25e251e", "fe8e0937-3222-4fe6-ab10-59850b92cb03"],
                              "0Yp5wiNSBK@e1ON.com",
                              "LqdftAsYYY@VkCU.com",
                              bank_account: "290463",
                              bank_account_holder_name: "0",
                              contact_name: "nKGF3nNlNVKYO2cbnh1nVwLkNRoCntEEp2XA0RMM1siT7scCcNcM5F9Cy2PtoWfxcD3tgc4jw8X37FFbHjlTIoYawmxyPONITceqwn7tmS9Y7GAL9D2fwTu02mA77v9BSbtJo6"
    ))
    assert response.code != "400"
  end

  def test_create_organization_4
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "JMa0ooImAYC1hyal1",
                              "hows4nThdzS0B1izbNEUviCdQnmNtIHnoSYv3h6kEA8DsJAvsM1hNyqhxGswxkzrcov63mC0gkM6p5BHcTk5FsevKpNab25lIBO7OGSWsvmzY7uoxIl7LXTMyR6TpwUrQidnlSgjS3m7qscxxuC5KDgmC4netplhv3cSSPrt9Nmqng9uJoPckKT1H2PyRZJOT7jFk6oKYpbHFrJ8TXs9EMwZJYyI8zypwcBga2nofDphBhsfxPDiwrm3Y3J2Yu2",
                              ["c0ae550f-23e1-490f-950d-3c4e961a5a74", "4773e974-992c-4bcd-86c4-848a9cd13e72", "7a6361ea-2c5d-4adc-801e-7a36defe7f96", "fbcba7e4-803c-400d-b70f-11e251689694", "468f34c2-8f7f-44ac-8343-ded81a590265", "c7009b81-19a5-4c44-accd-784c993ffdfb", "b89e3904-ff10-45b6-8efb-cb8b469db2c4", "e807d42b-8628-4c02-b96c-23266a58fb49", "149f7024-2ed3-434c-8698-c8aba25e251e", "fe8e0937-3222-4fe6-ab10-59850b92cb03"],
                              "0Yp5wiNSBK@e1ON.com",
                              "LqdftAsYYY@VkCU.com",
                              bank_account_type: "other",
                              bank_account: "2293211",
                              bank_account_holder_name: "｣",
                              contact_name: "NPArKMmJlP3tLCzFvhy9m3FnEcdgHLZBvglZF086tZ1ZUnxhWCsS4NMO8YsVreymolyLulVMkZR5d3XoAhb2PsuRFxt3mXXzHmDK4WEEWFylbhLPY9MqlHRwvW5QOeY5q7LO3jY9F3hbvJdr"
    ))
    assert response.code != "400"
  end

  def test_create_organization_5
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "JMa0ooImAYC1hyal1",
                              "hows4nThdzS0B1izbNEUviCdQnmNtIHnoSYv3h6kEA8DsJAvsM1hNyqhxGswxkzrcov63mC0gkM6p5BHcTk5FsevKpNab25lIBO7OGSWsvmzY7uoxIl7LXTMyR6TpwUrQidnlSgjS3m7qscxxuC5KDgmC4netplhv3cSSPrt9Nmqng9uJoPckKT1H2PyRZJOT7jFk6oKYpbHFrJ8TXs9EMwZJYyI8zypwcBga2nofDphBhsfxPDiwrm3Y3J2Yu2",
                              ["c0ae550f-23e1-490f-950d-3c4e961a5a74", "4773e974-992c-4bcd-86c4-848a9cd13e72", "7a6361ea-2c5d-4adc-801e-7a36defe7f96", "fbcba7e4-803c-400d-b70f-11e251689694", "468f34c2-8f7f-44ac-8343-ded81a590265", "c7009b81-19a5-4c44-accd-784c993ffdfb", "b89e3904-ff10-45b6-8efb-cb8b469db2c4", "e807d42b-8628-4c02-b96c-23266a58fb49", "149f7024-2ed3-434c-8698-c8aba25e251e", "fe8e0937-3222-4fe6-ab10-59850b92cb03"],
                              "0Yp5wiNSBK@e1ON.com",
                              "LqdftAsYYY@VkCU.com",
                              bank_branch_code: "",
                              bank_account_type: "saving",
                              bank_account: "683",
                              bank_account_holder_name: "X",
                              contact_name: "xgpTLQNxLSeiu5v9pU2iFdHxtnwLpXyvQIshxiODeaVPOLhLu17TWFNsulsZ9oHBoiXfB4Tm3MyRixm1yle6iHCeJLDMNWpefZqqJI5mSBXs2sQHgqXOapnMypm0qwIUZZ28sp5CgcHV9geFGLA42slHGX4P6rnjyi0rTo8H1hcQAwGJNaowviFZO41Mu25psJQ18XfLVaP9D3RE8InHIBQuLzbm41TWL6dHQNdeRTuQsPOqaUMFQ3"
    ))
    assert response.code != "400"
  end

  def test_create_organization_6
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "JMa0ooImAYC1hyal1",
                              "hows4nThdzS0B1izbNEUviCdQnmNtIHnoSYv3h6kEA8DsJAvsM1hNyqhxGswxkzrcov63mC0gkM6p5BHcTk5FsevKpNab25lIBO7OGSWsvmzY7uoxIl7LXTMyR6TpwUrQidnlSgjS3m7qscxxuC5KDgmC4netplhv3cSSPrt9Nmqng9uJoPckKT1H2PyRZJOT7jFk6oKYpbHFrJ8TXs9EMwZJYyI8zypwcBga2nofDphBhsfxPDiwrm3Y3J2Yu2",
                              ["c0ae550f-23e1-490f-950d-3c4e961a5a74", "4773e974-992c-4bcd-86c4-848a9cd13e72", "7a6361ea-2c5d-4adc-801e-7a36defe7f96", "fbcba7e4-803c-400d-b70f-11e251689694", "468f34c2-8f7f-44ac-8343-ded81a590265", "c7009b81-19a5-4c44-accd-784c993ffdfb", "b89e3904-ff10-45b6-8efb-cb8b469db2c4", "e807d42b-8628-4c02-b96c-23266a58fb49", "149f7024-2ed3-434c-8698-c8aba25e251e", "fe8e0937-3222-4fe6-ab10-59850b92cb03"],
                              "0Yp5wiNSBK@e1ON.com",
                              "LqdftAsYYY@VkCU.com",
                              bank_branch_name: "NqcUV3Fs8jYw6Kv7j3C0byLfNDc6eWDqX228w9y88F7Nxz1JBTxCDk",
                              bank_branch_code: "779",
                              bank_account_type: "current",
                              bank_account: "99",
                              bank_account_holder_name: "/",
                              contact_name: "SsAQvVhChZxzZNE9CQGHBOKKK1P91KgZgVr6cA8x03rp3EiK1aI6Y3qnCO4DM6hK6H175Z2VJLYZFFMOpSNuPlritQqpeZ60HLgl7PQubQXfsIiEGNdGG4t3KEhNnTm9NTvpPxKTLPCgEkZIBbkvmgOOZoDXzK37X8cNluTsfyx4BH23QFgvjIoOX14zOPuBvZl"
    ))
    assert response.code != "400"
  end

  def test_create_organization_7
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "JMa0ooImAYC1hyal1",
                              "hows4nThdzS0B1izbNEUviCdQnmNtIHnoSYv3h6kEA8DsJAvsM1hNyqhxGswxkzrcov63mC0gkM6p5BHcTk5FsevKpNab25lIBO7OGSWsvmzY7uoxIl7LXTMyR6TpwUrQidnlSgjS3m7qscxxuC5KDgmC4netplhv3cSSPrt9Nmqng9uJoPckKT1H2PyRZJOT7jFk6oKYpbHFrJ8TXs9EMwZJYyI8zypwcBga2nofDphBhsfxPDiwrm3Y3J2Yu2",
                              ["c0ae550f-23e1-490f-950d-3c4e961a5a74", "4773e974-992c-4bcd-86c4-848a9cd13e72", "7a6361ea-2c5d-4adc-801e-7a36defe7f96", "fbcba7e4-803c-400d-b70f-11e251689694", "468f34c2-8f7f-44ac-8343-ded81a590265", "c7009b81-19a5-4c44-accd-784c993ffdfb", "b89e3904-ff10-45b6-8efb-cb8b469db2c4", "e807d42b-8628-4c02-b96c-23266a58fb49", "149f7024-2ed3-434c-8698-c8aba25e251e", "fe8e0937-3222-4fe6-ab10-59850b92cb03"],
                              "0Yp5wiNSBK@e1ON.com",
                              "LqdftAsYYY@VkCU.com",
                              bank_code: "7046",
                              bank_branch_name: "TxqUMI17RiQnI5SNCKzyALRJFqkyuoYXDJys2csqwW45FeS",
                              bank_branch_code: "317",
                              bank_account_type: "saving",
                              bank_account: "789326",
                              bank_account_holder_name: "0",
                              contact_name: "Uf0BNjNcnQySqgwFP9h69RLwHIafYEk2GUMViKl4qYfWCWCjidaiO4FiMoxVGxqpan0twvhs2se3XE9ts73rl1otsotmiNtdCBRxiJ0SqgIsMi90lMESxzmU8hjuJquWj"
    ))
    assert response.code != "400"
  end

  def test_create_organization_8
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "JMa0ooImAYC1hyal1",
                              "hows4nThdzS0B1izbNEUviCdQnmNtIHnoSYv3h6kEA8DsJAvsM1hNyqhxGswxkzrcov63mC0gkM6p5BHcTk5FsevKpNab25lIBO7OGSWsvmzY7uoxIl7LXTMyR6TpwUrQidnlSgjS3m7qscxxuC5KDgmC4netplhv3cSSPrt9Nmqng9uJoPckKT1H2PyRZJOT7jFk6oKYpbHFrJ8TXs9EMwZJYyI8zypwcBga2nofDphBhsfxPDiwrm3Y3J2Yu2",
                              ["c0ae550f-23e1-490f-950d-3c4e961a5a74", "4773e974-992c-4bcd-86c4-848a9cd13e72", "7a6361ea-2c5d-4adc-801e-7a36defe7f96", "fbcba7e4-803c-400d-b70f-11e251689694", "468f34c2-8f7f-44ac-8343-ded81a590265", "c7009b81-19a5-4c44-accd-784c993ffdfb", "b89e3904-ff10-45b6-8efb-cb8b469db2c4", "e807d42b-8628-4c02-b96c-23266a58fb49", "149f7024-2ed3-434c-8698-c8aba25e251e", "fe8e0937-3222-4fe6-ab10-59850b92cb03"],
                              "0Yp5wiNSBK@e1ON.com",
                              "LqdftAsYYY@VkCU.com",
                              bank_name: "K0llEVJbOWbfhYc6oDtFrg",
                              bank_code: "",
                              bank_branch_name: "S2spAaEaPHJU5T",
                              bank_branch_code: "",
                              bank_account_type: "current",
                              bank_account: "007",
                              bank_account_holder_name: ")",
                              contact_name: "AJNvunuifi8NARpWPILnHUpE078MrEMbN7ZxHa18GyZF52y9znUZfFDcVGCdL91FmCNYnjEAYQMfsE4NCtdfMWjpjdHClTjjOWsX5G8ZpOj66I0UPtHyu16Axug0M5xKBdPTCSroXS0VwVmEPyxzW6SxDuNFehkhzLM091mXeGD6VzE1RbelxPkGKaphOnEMW"
    ))
    assert response.code != "400"
  end

  def test_list_shops_0
    response = $client.send(Pokepay::Request::ListShops.new(
    ))
    assert response.code != "400"
  end

  def test_list_shops_1
    response = $client.send(Pokepay::Request::ListShops.new(
                              per_page: 7213
    ))
    assert response.code != "400"
  end

  def test_list_shops_2
    response = $client.send(Pokepay::Request::ListShops.new(
                              page: 9303,
                              per_page: 9761
    ))
    assert response.code != "400"
  end

  def test_list_shops_3
    response = $client.send(Pokepay::Request::ListShops.new(
                              private_money_id: "b9f6bc30-779b-47d3-9879-b431dee24db8",
                              page: 262,
                              per_page: 9050
    ))
    assert response.code != "400"
  end

  def test_list_shops_4
    response = $client.send(Pokepay::Request::ListShops.new(
                              organization_code: "e41wOyq-ocV64-D",
                              private_money_id: "d1378ed6-5da0-4c3f-9587-a63cdf2facb5",
                              page: 4931,
                              per_page: 4176
    ))
    assert response.code != "400"
  end

  def test_create_shop_0
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "e0qA3vdnMJlloTaK9Fb89YWJ6IR8rvY8sOhrQf4qmbu8DUkbQt1gJATZzdtI6SVJq8A5eTLF8WH0jv"
    ))
    assert response.code != "400"
  end

  def test_create_shop_1
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "e0qA3vdnMJlloTaK9Fb89YWJ6IR8rvY8sOhrQf4qmbu8DUkbQt1gJATZzdtI6SVJq8A5eTLF8WH0jv",
                              organization_code: "22-W--Xa4-Z-p950-f-P-i-AA-Br"
    ))
    assert response.code != "400"
  end

  def test_create_shop_2
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "e0qA3vdnMJlloTaK9Fb89YWJ6IR8rvY8sOhrQf4qmbu8DUkbQt1gJATZzdtI6SVJq8A5eTLF8WH0jv",
                              shop_external_id: "CfQAVYSTLICMKHAwssfSmABZ0v",
                              organization_code: "-CEX-KH-G1-Z55dKZ-"
    ))
    assert response.code != "400"
  end

  def test_create_shop_3
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "e0qA3vdnMJlloTaK9Fb89YWJ6IR8rvY8sOhrQf4qmbu8DUkbQt1gJATZzdtI6SVJq8A5eTLF8WH0jv",
                              shop_email: "LqdwaLsvk5@fvRA.com",
                              shop_external_id: "FvQn2cqqAiK6YPzb8",
                              organization_code: "I-"
    ))
    assert response.code != "400"
  end

  def test_create_shop_4
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "e0qA3vdnMJlloTaK9Fb89YWJ6IR8rvY8sOhrQf4qmbu8DUkbQt1gJATZzdtI6SVJq8A5eTLF8WH0jv",
                              shop_tel: "038-3903816",
                              shop_email: "1OaOVuQRFy@IUpj.com",
                              shop_external_id: "WrzturcXffwOP9NpeS95pzNRYU00zlZeE4gH",
                              organization_code: "aURy7zMyTEJb--UP-eh-YoY"
    ))
    assert response.code != "400"
  end

  def test_create_shop_5
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "e0qA3vdnMJlloTaK9Fb89YWJ6IR8rvY8sOhrQf4qmbu8DUkbQt1gJATZzdtI6SVJq8A5eTLF8WH0jv",
                              shop_address: "p5aJaGYTOsQtodSWhcrnVWqOkoipKZOJqZFkF9k7yjlmHN5kXaKu0xJoYssqzKPgTQ9yUkVByYhfUC0X1rTdRbRz8PD2Y6pCfCG4mNYKlg4paHhmYP",
                              shop_tel: "022492-564",
                              shop_email: "OBa7r0ooKr@4Ijy.com",
                              shop_external_id: "6RRz",
                              organization_code: "7R"
    ))
    assert response.code != "400"
  end

  def test_create_shop_6
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "e0qA3vdnMJlloTaK9Fb89YWJ6IR8rvY8sOhrQf4qmbu8DUkbQt1gJATZzdtI6SVJq8A5eTLF8WH0jv",
                              shop_postal_code: "406-7794",
                              shop_address: "2mt9eDahLN85EAwxgkRP7fAz09PV22z2SlOw6wYwxuK0xWzPZ4KsBxU71lK2AZecxWmXzJMZ7Dg5qB3hBW5rXmlNlWe9TNjdPQLzUTQ7O3y12YoCw8qG84wc05jizfHOCGisgQAoSUPLms1pVwfQFOHwOMNwQHftU4u20gqbLydSSjw1apGFJN8cbvuPwMUrp3W8FXjPHwKUp4kS3BrKPeYsbNRlUbrgS78aDUybw3P7grs5NrVg1QFnbXdCbd",
                              shop_tel: "08-579530",
                              shop_email: "3p6xwtjTsW@SEfm.com",
                              shop_external_id: "L2L",
                              organization_code: "v--PO-6-9bm"
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_0
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "d83e344b-f2a2-4d56-b688-f6b5f8d19363"
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_1
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "d83e344b-f2a2-4d56-b688-f6b5f8d19363",
                              page: 331
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_2
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "d83e344b-f2a2-4d56-b688-f6b5f8d19363",
                              per_page: 442,
                              page: 8222
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_3
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "d83e344b-f2a2-4d56-b688-f6b5f8d19363",
                              from: "2024-03-24T16:09:32.000000+09:00",
                              to: "2019-04-27T10:33:09.000000+09:00"
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_4
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "d83e344b-f2a2-4d56-b688-f6b5f8d19363",
                              from: "2024-07-30T01:54:42.000000+09:00",
                              to: "2018-08-03T05:22:56.000000+09:00",
                              page: 3426
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_5
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "d83e344b-f2a2-4d56-b688-f6b5f8d19363",
                              from: "2017-06-09T22:59:02.000000+09:00",
                              to: "2021-11-11T00:30:05.000000+09:00",
                              per_page: 3864,
                              page: 9689
    ))
    assert response.code != "400"
  end

end
