# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

require 'minitest/autorun'
require "pokepay_partner_ruby_sdk"
require "inifile"

$client = Pokepay::Client.new(File.expand_path("~/.pokepay/test-config.ini"))
$inifile = IniFile.load(File.expand_path("~/.pokepay/test-config.ini"))

class PokepayTest < Minitest::Test

  def test_that_it_has_a_version_number
    refute_nil ::Pokepay::VERSION
  end

  def test_get_ping_0
    response = $client.send(Pokepay::Request::GetPing.new(
    ))
    assert response.code != "400"
  end

  def test_send_echo_0
    response = $client.send(Pokepay::Request::SendEcho.new(
                              "acDgdY"
    ))
    assert response.code != "400"
  end

  def test_get_user_0
    response = $client.send(Pokepay::Request::GetUser.new(
    ))
    assert response.code != "400"
  end

  def test_list_user_accounts_0
    response = $client.send(Pokepay::Request::ListUserAccounts.new(
                              "f7badafa-54a1-4511-b337-e4aa1c1fe652"
    ))
    assert response.code != "400"
  end

  def test_get_account_0
    response = $client.send(Pokepay::Request::GetAccount.new(
                              "7c419418-aa59-4e5c-bbdc-7d8d6bf88c31"
    ))
    assert response.code != "400"
  end

  def test_update_account_0
    response = $client.send(Pokepay::Request::UpdateAccount.new(
                              "1cca797a-a4ae-4807-a9ad-4bab80f00988"
    ))
    assert response.code != "400"
  end

  def test_update_account_1
    response = $client.send(Pokepay::Request::UpdateAccount.new(
                              "1cca797a-a4ae-4807-a9ad-4bab80f00988",
                              is_suspended: true
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_0
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "cc450cba-668f-4380-854c-2e6dae6d9426"
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_1
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "cc450cba-668f-4380-854c-2e6dae6d9426",
                              direction: "desc"
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_2
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "cc450cba-668f-4380-854c-2e6dae6d9426",
                              expires_at_to: "2023-12-04T19:51:42.000000+09:00",
                              direction: "desc"
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_3
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "cc450cba-668f-4380-854c-2e6dae6d9426",
                              expires_at_from: "2023-01-15T03:20:22.000000+09:00",
                              expires_at_to: "2016-07-18T17:09:40.000000+09:00",
                              direction: "asc"
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_4
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "cc450cba-668f-4380-854c-2e6dae6d9426",
                              per_page: 2394,
                              expires_at_from: "2025-01-10T04:46:02.000000+09:00",
                              expires_at_to: "2024-05-11T03:04:24.000000+09:00",
                              direction: "asc"
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_5
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "cc450cba-668f-4380-854c-2e6dae6d9426",
                              page: 5477,
                              per_page: 8394,
                              expires_at_from: "2022-03-09T11:53:53.000000+09:00",
                              expires_at_to: "2019-09-12T11:19:03.000000+09:00",
                              direction: "desc"
    ))
    assert response.code != "400"
  end

  def test_list_account_expired_balances_0
    response = $client.send(Pokepay::Request::ListAccountExpiredBalances.new(
                              "c3851eee-c081-4e48-9428-8ce6203ac303"
    ))
    assert response.code != "400"
  end

  def test_list_account_expired_balances_1
    response = $client.send(Pokepay::Request::ListAccountExpiredBalances.new(
                              "c3851eee-c081-4e48-9428-8ce6203ac303",
                              direction: "desc"
    ))
    assert response.code != "400"
  end

  def test_list_account_expired_balances_2
    response = $client.send(Pokepay::Request::ListAccountExpiredBalances.new(
                              "c3851eee-c081-4e48-9428-8ce6203ac303",
                              expires_at_to: "2023-10-14T15:41:08.000000+09:00",
                              direction: "desc"
    ))
    assert response.code != "400"
  end

  def test_list_account_expired_balances_3
    response = $client.send(Pokepay::Request::ListAccountExpiredBalances.new(
                              "c3851eee-c081-4e48-9428-8ce6203ac303",
                              expires_at_from: "2016-02-07T23:51:43.000000+09:00",
                              expires_at_to: "2023-06-26T07:13:08.000000+09:00",
                              direction: "desc"
    ))
    assert response.code != "400"
  end

  def test_list_account_expired_balances_4
    response = $client.send(Pokepay::Request::ListAccountExpiredBalances.new(
                              "c3851eee-c081-4e48-9428-8ce6203ac303",
                              per_page: 1280,
                              expires_at_from: "2017-09-19T20:56:50.000000+09:00",
                              expires_at_to: "2021-05-01T18:07:44.000000+09:00",
                              direction: "desc"
    ))
    assert response.code != "400"
  end

  def test_list_account_expired_balances_5
    response = $client.send(Pokepay::Request::ListAccountExpiredBalances.new(
                              "c3851eee-c081-4e48-9428-8ce6203ac303",
                              page: 7954,
                              per_page: 183,
                              expires_at_from: "2017-07-15T07:24:12.000000+09:00",
                              expires_at_to: "2018-02-11T05:24:08.000000+09:00",
                              direction: "desc"
    ))
    assert response.code != "400"
  end

  def test_create_customer_account_0
    response = $client.send(Pokepay::Request::CreateCustomerAccount.new(
                              "7f94c950-6ed6-47a1-b8d4-2c8895d41b68"
    ))
    assert response.code != "400"
  end

  def test_create_customer_account_1
    response = $client.send(Pokepay::Request::CreateCustomerAccount.new(
                              "7f94c950-6ed6-47a1-b8d4-2c8895d41b68",
                              account_name: "RcEAVa4JmfjoJZ9ajsO39BqxPDSP5BpfA0dYcuMmHpa4aDHWm32hBFhI0DxRhz83lKq4Wp1hKlNvpHM0s7Dd9Uu6qWqC0qUtLag9adxARTcCtKjz1M2kusM3cVDMOGMtpxWNvKR6Gcp6PWCiNymBaUIu6lQIyVNDYRttS46oTXBYnbHbMuAdnXANiixumuncg7eg"
    ))
    assert response.code != "400"
  end

  def test_create_customer_account_2
    response = $client.send(Pokepay::Request::CreateCustomerAccount.new(
                              "7f94c950-6ed6-47a1-b8d4-2c8895d41b68",
                              user_name: "c7L05i8jkZ1Waa6h6AAgB9jXehhbgsnyiHZ1n3qwk3r3QhfSXAhy6Q6NsE0G4ETHn0hBw4No1YXyGaN9eZjSIQORsTn19Lt83IRfp6apsZzwHUgb2qqrLtRpMZnFJMuPuuYDxHZdnikAchiJbVP3ZTnJxIJTqpbj9hQa29LtqbzIUCtrgI5GH6wQi2f3OojTDEk0fitYgKzfXu0N7ZPQ6Ey6Tu3BU56A0DovC2AWlgsj8AO1bqHH9NHpq",
                              account_name: "wH1tkpyNDcuWxfr4xKRRC5UPfddKJfLPJmxAhDpkltxfpGBgKzLBWMCYifXDXPCbHnT3R8fCd8115VzfSNwUPij0JCe"
    ))
    assert response.code != "400"
  end

  def test_list_bills_0
    response = $client.send(Pokepay::Request::ListBills.new(
    ))
    assert response.code != "400"
  end

  def test_list_bills_1
    response = $client.send(Pokepay::Request::ListBills.new(
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_2
    response = $client.send(Pokepay::Request::ListBills.new(
                              upper_limit_amount: 2055,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_3
    response = $client.send(Pokepay::Request::ListBills.new(
                              lower_limit_amount: 2546,
                              upper_limit_amount: 4783,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_4
    response = $client.send(Pokepay::Request::ListBills.new(
                              shop_id: "245c67ff-0e24-4b77-8960-3c0008983206",
                              lower_limit_amount: 8742,
                              upper_limit_amount: 2701,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_5
    response = $client.send(Pokepay::Request::ListBills.new(
                              shop_name: "ct5VctC8ahSG576Yk267hNuqsd2aOEu5ugI0fcKmGRUw7sMhCFW8ODbHkZSUPXBsmObvnHUjDTSSciw3PX7II",
                              shop_id: "6a1e2620-9d8d-4013-adeb-8276d175d1ff",
                              lower_limit_amount: 7806,
                              upper_limit_amount: 134,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_6
    response = $client.send(Pokepay::Request::ListBills.new(
                              created_to: "2016-02-09T21:59:59.000000+09:00",
                              shop_name: "CAHh7QD95u0YIcm0Sp2RluFOAxJTKKlkJp5ENq52OLTcJlnsa7zuy1tusdwen7Z1wrrgdxWfKkMLwrBpORQ9LHlnKRmCd4nadmeyKnqGyqpn3W7S36l34SSSOxW72gqSjd8QPzbjt0rt7UmerReZGbvGgvAZbyLJ1Lea6an4P1AnQALadFsAzgfKjbtuXgZDedIJqTHGgnOhGiwZBj5AvHdO2AtfcLabY2vDzXzQx3sP8V6IT9VFC5b",
                              shop_id: "424fb511-d46f-4330-938a-d53f04707e4b",
                              lower_limit_amount: 344,
                              upper_limit_amount: 4198,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_7
    response = $client.send(Pokepay::Request::ListBills.new(
                              created_from: "2017-10-06T00:37:12.000000+09:00",
                              created_to: "2022-10-15T14:09:50.000000+09:00",
                              shop_name: "8jPQ0hMJ4nPgNJOUuVI3xkUSOX0vTgyFK1FOp7pl9MWii2exAarzlUllrgsQZQAnUYeKIbZQuPYAKNLvTyMcIYlLoYSz5jRHNPv9LO3MtPyt1wTnktL8AYkBvD7caRgncONv8Kje2pUTWzADND",
                              shop_id: "195e4ee5-eb1d-4906-b8b7-82efe5592669",
                              lower_limit_amount: 193,
                              upper_limit_amount: 7876,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_8
    response = $client.send(Pokepay::Request::ListBills.new(
                              description: "B6ZsUUsk6umIdkjysmBoCy1Ud1e5PrxfXmPZX1V",
                              created_from: "2025-06-28T06:22:12.000000+09:00",
                              created_to: "2022-10-09T02:35:10.000000+09:00",
                              shop_name: "ebv0ckwSJ4e9e0pY47yGoAwg28Msl4sq96mAewFZHEg2RF0uEHwK5Jbwu9JRSn5a7ymUxn4mfvD7ycun86BZW4IWD5GZy4J15w0ovSrq2HjQnZoVWhOdLDSpe9mEjTApY38vZyrfHaX2ePxiTIXhf26BicGgC0Q3onqPmyIzFPAF7SEHME8DlS2m5Kv5IbgTWsj7MinGr0IGEeLzU5ms0HjwVmUqLVvuFmzvx3MioePO7gkONN",
                              shop_id: "4faa4393-bfc1-4501-bb6a-b042c64b79ab",
                              lower_limit_amount: 1219,
                              upper_limit_amount: 729,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_9
    response = $client.send(Pokepay::Request::ListBills.new(
                              organization_code: "AsqS2Z-V79-dtNkY7",
                              description: "xuQUV",
                              created_from: "2023-06-24T23:35:38.000000+09:00",
                              created_to: "2022-08-08T06:45:21.000000+09:00",
                              shop_name: "ZD3LHlYNS3c0MUvvhZyFdpqg4zFLwpBAFUZ73GCZjYfwcSTcjOL0y0KRT0zFenF09DVyQoaELlrJk6MRPKi62IzWH9emhQ0CqvNNBrhyRg9xxzNXJhnMZrEqyRqPCGzbSmOoYCMUQNjvF4AYLzd022rwQVNfYYCfZZWpAcyBWwWi1DgvTt4hTTZowFPycMflfcbIe",
                              shop_id: "515d81cf-56c9-4e2d-8b3e-fcaf1c1fe59d",
                              lower_limit_amount: 4965,
                              upper_limit_amount: 6298,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_10
    response = $client.send(Pokepay::Request::ListBills.new(
                              private_money_id: "864ea212-382c-493b-9df3-443f4fd60db0",
                              organization_code: "Q0--Vm51xP51j-Uc-1fe-3Z-e---",
                              description: "TscHpgaN0j8ZeP1HDPDTHzzRIdWxHjKy82N74miDUcOuIVqRIEU93kljq1Q8TjukgNdosrcsbqXkWqVhxkWkSbCcQV2KWKaXCJgJ38wW32AKvILX828FihWZQyqSbK0FMXzQI3K0upT8cYYAuEa7VHyo1Pr6ZXG8JSWzel5X6ggilnbIikjMsDt",
                              created_from: "2019-04-11T19:02:55.000000+09:00",
                              created_to: "2016-03-28T17:19:29.000000+09:00",
                              shop_name: "Hs8kXaVldBOvstCOu5vNtx3bBib1BS1IIGWD4mpTYqNNFPcbcfJ8JMK49acle",
                              shop_id: "54afd3d6-a852-4a73-bc70-69e31ba6b2ec",
                              lower_limit_amount: 868,
                              upper_limit_amount: 2036,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_11
    response = $client.send(Pokepay::Request::ListBills.new(
                              bill_id: "5tmURvImdn",
                              private_money_id: "ed6fdaa7-91e9-45e5-9b29-8dec29b3be0c",
                              organization_code: "DoRXh-Y-9SWD-l-fv-u",
                              description: "Ys7Yv5K",
                              created_from: "2016-09-06T09:57:24.000000+09:00",
                              created_to: "2023-02-14T22:10:18.000000+09:00",
                              shop_name: "cz7zjgazoph",
                              shop_id: "e79838f5-c921-4023-9669-1143c81ef931",
                              lower_limit_amount: 9302,
                              upper_limit_amount: 3548,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_12
    response = $client.send(Pokepay::Request::ListBills.new(
                              per_page: 447,
                              bill_id: "XiXW8JGdO",
                              private_money_id: "5050d80d-c7ba-4f99-ad8b-b975c78d25bf",
                              organization_code: "z",
                              description: "uwMI02c6YHU8uGe8qGNvTmA",
                              created_from: "2021-03-11T17:24:05.000000+09:00",
                              created_to: "2024-02-26T23:31:28.000000+09:00",
                              shop_name: "H06f3cpkGDNNhHR4jcwCrCwplpzKOK41muEKIO2q9f6dQ5BvDAnz25uvrmGGKjRYVWTh4n3trK0bvzHyQJ1u0mKrSXl5b4zkBhHXIiOwN14umNbs9HzTMzg2AFGgoFwChMKyFjnp6NWuVTvukHEJJxjvwAaSkrlPscgFZA7kgmnQGh0g7xEy0gjIfqsy3qqeO2uL3gmJXocI00jDfhi9nkYKzlD45lOs5FqPThDPFGAn6g717B9KA",
                              shop_id: "e1400ce0-47d7-451c-9618-89c8bbd88a9a",
                              lower_limit_amount: 2172,
                              upper_limit_amount: 8069,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_13
    response = $client.send(Pokepay::Request::ListBills.new(
                              page: 5228,
                              per_page: 6990,
                              bill_id: "aQT0YWfQtg",
                              private_money_id: "aa0d8a40-f689-4fdb-b8d6-736898ef5371",
                              organization_code: "-4V-k1D8HboK--w-uW",
                              description: "LerXQe8LjF8Q6qvpD5ZbBwXFvQ1skGDixXFJczCMVyjlRecAjobCopZKV",
                              created_from: "2024-12-05T21:24:47.000000+09:00",
                              created_to: "2021-12-15T16:10:53.000000+09:00",
                              shop_name: "9UiV0XEmtc9iB2syyuELfawMoOZtkTktpas3rTKhS7CSUreJUtTC5W6xtdNcZmGzg6LOAwdB03Wi69g5bppku3R9lJVdDaUu8gKI7uxlsX8tJTVN1o4Avhi0fX5dozKzovfXQ3PHUhjHLVEtSIaxZ8O9N2SLzG35Urh2rbZx2aArvrKFEW0caD1nqOz",
                              shop_id: "ef491acb-060a-4810-910f-e7adbe43b402",
                              lower_limit_amount: 2666,
                              upper_limit_amount: 8542,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_create_bill_0
    response = $client.send(Pokepay::Request::CreateBill.new(
                              "10b38e5a-a0a2-4643-b978-0431d3fe12c5",
                              "6be77097-48f0-43b4-96fd-0f6bfa0ed65f"
    ))
    assert response.code != "400"
  end

  def test_create_bill_1
    response = $client.send(Pokepay::Request::CreateBill.new(
                              "10b38e5a-a0a2-4643-b978-0431d3fe12c5",
                              "6be77097-48f0-43b4-96fd-0f6bfa0ed65f",
                              description: "AmGgvgI7Yg"
    ))
    assert response.code != "400"
  end

  def test_create_bill_2
    response = $client.send(Pokepay::Request::CreateBill.new(
                              "10b38e5a-a0a2-4643-b978-0431d3fe12c5",
                              "6be77097-48f0-43b4-96fd-0f6bfa0ed65f",
                              amount: 7044,
                              description: "C9RfQiSpTWZrd0hVSBtTuiSKN3fmfJoVUvvyWz4acD4YN5"
    ))
    assert response.code != "400"
  end

  def test_update_bill_0
    response = $client.send(Pokepay::Request::UpdateBill.new(
                              "f74385dc-54b9-4a04-b397-68b535a93439"
    ))
    assert response.code != "400"
  end

  def test_update_bill_1
    response = $client.send(Pokepay::Request::UpdateBill.new(
                              "f74385dc-54b9-4a04-b397-68b535a93439",
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_update_bill_2
    response = $client.send(Pokepay::Request::UpdateBill.new(
                              "f74385dc-54b9-4a04-b397-68b535a93439",
                              description: "IWGujcTx",
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_update_bill_3
    response = $client.send(Pokepay::Request::UpdateBill.new(
                              "f74385dc-54b9-4a04-b397-68b535a93439",
                              amount: 7494,
                              description: "XyLyMOsteVH8YLvoUoraYyVUvoHuSd144X7ZEq8UGlMat7Q5BMcC1v73v60y8DMLWrlnr061xWZsz1ogogHitDMic7XGDhIwo",
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_create_check_0
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 5442
    ))
    assert response.code != "400"
  end

  def test_create_check_1
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 4924,
                              description: "BCDG7j4DoWkpZIbqBi9TROGFtlR9rLj2Y1ER9gKdUSrcKHlFd3Ur1MCMIUROIYftW7QMsIbzCAj1GsSvfXjxUW5PMdDuBsMe04PTf8v"
    ))
    assert response.code != "400"
  end

  def test_create_check_2
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 7165,
                              is_onetime: false,
                              description: "QwwHu7ykbtkzGPhzROeLpMaUZfjz7mGpF3omDB92rueqlmfnAfu7erS3gFr3FTdQ8rwckpkfwdxwxZ95sfTG55oAI4V"
    ))
    assert response.code != "400"
  end

  def test_create_check_3
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 9795,
                              usage_limit: 6471,
                              is_onetime: false,
                              description: "4sTwcYeFwcP7ZmLygXYRtjxN2aIco6xNkWo0aYr1y1KHCmQGL0IM3EaCDd87kJG01a7GOWj7LV4v5yotPxhlRj2vkjikjfOo5Zy9zD8cfycxdjXF6cmwiKvevzAx7rHin0MHYFpvhqZUg2yG4"
    ))
    assert response.code != "400"
  end

  def test_create_check_4
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 6414,
                              expires_at: "2019-05-03T14:12:01.000000+09:00",
                              usage_limit: 7164,
                              is_onetime: true,
                              description: "L4evFZLjpsodOQD43fZ5T5bk20dIuBp2e25agSXyEGickpeze"
    ))
    assert response.code != "400"
  end

  def test_create_check_5
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 4023,
                              point_expires_at: "2018-03-11T02:38:10.000000+09:00",
                              expires_at: "2022-07-08T12:11:45.000000+09:00",
                              usage_limit: 872,
                              is_onetime: false,
                              description: "ltNB5ed"
    ))
    assert response.code != "400"
  end

  def test_create_check_6
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 1652,
                              point_expires_in_days: 5298,
                              point_expires_at: "2020-07-06T08:37:37.000000+09:00",
                              expires_at: "2024-02-16T01:46:48.000000+09:00",
                              usage_limit: 3355,
                              is_onetime: true,
                              description: "n6abEccTMUOFUG9Fme9wlEEj2gZC8ckmFOzWRdKb11QTIHM0x5oJQ4O2Nwel4rHJTDGFvqXggC9Tcy7ogKmUw0VnsFyzfyt6Bg95FB1a7IFTBkW9tPubyeqITUoc54HWI6lY"
    ))
    assert response.code != "400"
  end

  def test_create_check_7
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 8215,
                              bear_point_account: "526fadb3-fa90-457f-8e5c-0678195e33c1",
                              point_expires_in_days: 5555,
                              point_expires_at: "2018-09-23T16:27:36.000000+09:00",
                              expires_at: "2018-03-05T11:35:21.000000+09:00",
                              usage_limit: 1183,
                              is_onetime: false,
                              description: "6LVyn2dOGJj5BoyL1MgjctfisLuYo4aorOwFrhmbs26EDkzDLnAr7NHvMDZLOk3Kn6N9IKA2DQ0UDl0RkGXqQRpkGArTGUPugetKJLdESdgB4DMlPh"
    ))
    assert response.code != "400"
  end

  def test_create_check_8
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 4341,
                              point_amount: 8453
    ))
    assert response.code != "400"
  end

  def test_create_check_9
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 1819,
                              point_amount: 12,
                              description: "gx6J23S5a4KJH2dJnXOeAy8xYgmSSWd6nFdHza9f0TF30iljDxgSpyfoekUtYXnQ6dyRqDXbojqilSXXfgL13rI1kMYSkzLYWcqyBEPqq6jXoMPoI5dYhtAEAC8MN1MIRbysguh0xXqdkQK8VGfHRzulBqoPAVuBC2EUluqb81O3ZagKE8LcCa8bz2nHShe5Eo"
    ))
    assert response.code != "400"
  end

  def test_create_check_10
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 342,
                              point_amount: 5638,
                              is_onetime: false,
                              description: "dmx1iMacSt3whWHQ5cbR62EyfrAyRxoXmZ8au8D4esSHy55WYfHfvN0QEBe9OUmuQoNyAxdhT65YfaNVM2xjqlPxxy8RqwFWTQ1hvVt9bN2zIxNZx4eE9mHPjq6XCvYjxbcuNA5AOQHru6gAX"
    ))
    assert response.code != "400"
  end

  def test_create_check_11
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 4463,
                              point_amount: 8092,
                              usage_limit: 7440,
                              is_onetime: false,
                              description: "UpOUbFxl1xg8SX1voG8Gydqo4fQ7D47J36mgyKf2pLnur36TYPgxI"
    ))
    assert response.code != "400"
  end

  def test_create_check_12
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 5024,
                              point_amount: 7269,
                              expires_at: "2016-07-06T05:37:37.000000+09:00",
                              usage_limit: 3031,
                              is_onetime: true,
                              description: "JKugM3OQh2JHBnxbiEM0oFGnnvKX9mW4mLerHweV6yDqMFurm2HyY5rxBRsFTyEvnewbYd4rNZJsCq7m7arw2NKYH12xHXaAOFqIwxrvxkxwVYBDQiRCyV"
    ))
    assert response.code != "400"
  end

  def test_create_check_13
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 1083,
                              point_amount: 7854,
                              point_expires_at: "2022-11-09T12:14:18.000000+09:00",
                              expires_at: "2016-07-31T12:05:06.000000+09:00",
                              usage_limit: 7214,
                              is_onetime: false,
                              description: "czNdwQ9LziqjK5MdQ1lZMyA"
    ))
    assert response.code != "400"
  end

  def test_create_check_14
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 1234,
                              point_amount: 8064,
                              point_expires_in_days: 6979,
                              point_expires_at: "2024-08-10T09:35:05.000000+09:00",
                              expires_at: "2018-04-18T08:05:42.000000+09:00",
                              usage_limit: 5344,
                              is_onetime: true,
                              description: "SqVUKE1GN9JqLEvyRdA5j20ws4Z1pnjZ8xWKeN3WKGyHXCKDfS0S9olxtCG8sS34enFyHh"
    ))
    assert response.code != "400"
  end

  def test_create_check_15
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              money_amount: 4553,
                              point_amount: 5773,
                              bear_point_account: "aa1efee2-12fb-4a74-a545-2a0562a1f98f",
                              point_expires_in_days: 5520,
                              point_expires_at: "2018-06-14T19:13:27.000000+09:00",
                              expires_at: "2018-12-04T15:17:40.000000+09:00",
                              usage_limit: 8710,
                              is_onetime: true,
                              description: "OMttUhD0OiwEvovxL7L6kZ3KaNub1zwaCdHgj8ik3dmsSURUNaSg6OcHEmOeQFO3Ox8qDzSQ0YVNC6SfrLsEgbwDrafzykU4qQWwEl9RBh7JkqQ2DDr8e6Qf8fK7SBxethCuCr4dBSWzD3agMTAvZtCmtviHLHOBHoLHZ5Hyso5u9Osjia9h3ovwp1QqOYh"
    ))
    assert response.code != "400"
  end

  def test_create_check_16
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              point_amount: 3558
    ))
    assert response.code != "400"
  end

  def test_create_check_17
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              point_amount: 7124,
                              description: "v94bnDyHKg7jf7TRBDusrb62imeaN035TYhQYVT6897JBIT98Ea3vOiHnJbC3RzxMsGYTRQVbbD"
    ))
    assert response.code != "400"
  end

  def test_create_check_18
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              point_amount: 7755,
                              is_onetime: true,
                              description: "fr7wcTIqfZGa8VmM7LxaafZsEiZ4h1kUtLESZUqCMHUv6WI9WlLqAjFFVtovIA3w7if4YoZJ6xmZ8N4p4uCNZaugRp11iMcrfILoN8ZP7287JaoYb8spv1FcaYx8c7c37K2BoQEomxqdvzxKVxdoit0nsRd"
    ))
    assert response.code != "400"
  end

  def test_create_check_19
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              point_amount: 7999,
                              usage_limit: 6753,
                              is_onetime: false,
                              description: "T9IRy95uKnYj6aDVb3qDkr4zFWttvA7t4NS9wkdOXwioDpfXuzoNbRp"
    ))
    assert response.code != "400"
  end

  def test_create_check_20
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              point_amount: 9565,
                              expires_at: "2017-02-13T22:49:55.000000+09:00",
                              usage_limit: 4769,
                              is_onetime: false,
                              description: "j9znX2XonFzQcO5QEOmdgUm73I2kFchNQksZB6ByT3lVRQ7O823WFeXCsADfveWv5SetJLuZcB6tdcwibyPvTHbjOWbqqVGNOP2f7Fm"
    ))
    assert response.code != "400"
  end

  def test_create_check_21
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              point_amount: 7691,
                              point_expires_at: "2016-03-06T09:52:08.000000+09:00",
                              expires_at: "2021-09-17T16:54:03.000000+09:00",
                              usage_limit: 1206,
                              is_onetime: true,
                              description: "SXXM3Y5XPxnjFhfkfYgvABxRhjV7rXm6F6onhtgkbe1I3fnSrAjiMpnuQgQNZWqLAFAWqZBqyjs43AAjNChMERBnJER6lOBQBwAgsTow2Z3Uka1wds9TY9Bp5VDJiBPB"
    ))
    assert response.code != "400"
  end

  def test_create_check_22
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              point_amount: 2225,
                              point_expires_in_days: 2621,
                              point_expires_at: "2019-10-29T04:38:08.000000+09:00",
                              expires_at: "2023-05-17T07:39:03.000000+09:00",
                              usage_limit: 6629,
                              is_onetime: true,
                              description: "NJcIKtWyeNc1zzlxW2hgOK8NI225RAsUHuuLFS4058hKDGnyjbxrF6zxkmTZedVWeLbSdWlORFkWxf1fgII7vrhxHZrOEIH6HNdDlfIrfFFwUdXhpSi4j72IcAxs47XeIzYlwiQaQGyn4Age91Y1cWNDBnv9RrzZK5"
    ))
    assert response.code != "400"
  end

  def test_create_check_23
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "ce5c4e69-e4c9-47f7-b8e2-81239073ebf5",
                              point_amount: 4479,
                              bear_point_account: "13049eeb-a24c-4638-bceb-db1ea417ee75",
                              point_expires_in_days: 7753,
                              point_expires_at: "2018-05-08T07:35:43.000000+09:00",
                              expires_at: "2023-11-14T12:55:05.000000+09:00",
                              usage_limit: 608,
                              is_onetime: false,
                              description: "oA9Wjz3x"
    ))
    assert response.code != "400"
  end

  def test_list_transactions_0
    response = $client.send(Pokepay::Request::ListTransactions.new(
    ))
    assert response.code != "400"
  end

  def test_list_transactions_1
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_2
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              is_modified: true,
                              types: ["exchange_outflow", "exchange_inflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_3
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              private_money_id: "b3749756-8106-4174-9c3a-2ba298e8ca11",
                              is_modified: true,
                              types: ["exchange_inflow", "topup", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_4
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              organization_code: "I2-2-G9--1",
                              private_money_id: "615f8196-f5f3-4ff6-b715-547504f77f22",
                              is_modified: true,
                              types: ["topup", "exchange_inflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_5
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              transaction_id: "1b5c03a7-3b86-4aa3-a278-768e9bdfec3f",
                              organization_code: "-7d-g-b6iS32WX-gqLu-M-4A-JG--",
                              private_money_id: "b6dcb618-b35a-48b9-8ffa-214edef7544c",
                              is_modified: true,
                              types: ["exchange_inflow", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_6
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              terminal_id: "85fc10ef-c6c1-42a0-9c8c-d48f10a8d575",
                              transaction_id: "c452fd84-b760-46d0-932c-136b1bc38fab",
                              organization_code: "F6rD68Aq",
                              private_money_id: "c2ebb542-b325-4685-b332-deff24cc0e4c",
                              is_modified: false,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_7
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              customer_name: "YYNQ77hNnDgeQkP6BrHNLW2TjgwJkClYsxYjLV6mNckmXWb6cDTOBEvT1fZYocBrt",
                              terminal_id: "ef6d2f8e-61e7-47bf-9777-3a52a35dd4cc",
                              transaction_id: "6df9733d-2e0f-4769-8a78-ba65098fedac",
                              organization_code: "0S9s-b-zSFjOgue-Z",
                              private_money_id: "77f6420b-37e6-4631-8f98-d6a364679511",
                              is_modified: true,
                              types: ["exchange_inflow", "topup", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_8
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              customer_id: "97241719-7d86-4463-b3ef-c4477a3a86a8",
                              customer_name: "3F55uy5",
                              terminal_id: "131ba2dd-bf36-4e66-96cd-83ffed3701ec",
                              transaction_id: "fbbd6597-ee5c-4d26-92b4-94ef052f8776",
                              organization_code: "6K2LE-uqNcy",
                              private_money_id: "e56727b6-f9a2-4dd9-9097-34a697d8e187",
                              is_modified: false,
                              types: ["topup", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_9
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              shop_id: "f1dc9af6-286d-48c4-a022-9add0ad0fc3e",
                              customer_id: "22aa7df1-0e50-47c1-8762-edfd409bf19d",
                              customer_name: "tHJHRtQBqCHsxk71kIOiSHcZ37iojnk7j2j33qMA4N2evwLBNS7QyCEhtgNDuAnxydB9u3o7ZMeTosoRh4S0mExQI1uCwHXvSS9xqXNJMeqv2rRxx8SeYgA5RTAZIE0d3whSKLF4xWXCgQOdSsQVPrApoltrzZbMjGbqCaDUv1CsWTy6z2FdXbfXavW2HwaVVWGcOvRgfjTir1eeHpnGAvFN",
                              terminal_id: "664d6dbc-f235-4f75-95d6-7b484ba0a6fe",
                              transaction_id: "0f45fd4b-0a49-4e16-b79f-5d04dd825aed",
                              organization_code: "t16640PHYa--3",
                              private_money_id: "337159e9-673d-4cea-98b4-717f44b4f160",
                              is_modified: false,
                              types: ["exchange_inflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_10
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              per_page: 6619,
                              shop_id: "a60a02ea-20c8-473d-8df7-9c6818b08862",
                              customer_id: "857192ad-1239-4a6c-9ad6-ab8a1aa9e839",
                              customer_name: "sTjb",
                              terminal_id: "6abace12-a20e-44df-9271-9ba6f099d98e",
                              transaction_id: "b3954460-8538-4284-976f-197fc1b8e2dd",
                              organization_code: "DE---XMxvFoMK8-V6ok2U8mU-vl-",
                              private_money_id: "1944eeef-a05d-4999-bc09-a9bc6ab38f59",
                              is_modified: false,
                              types: ["payment", "topup", "exchange_outflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_11
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              page: 7183,
                              per_page: 1101,
                              shop_id: "92828a74-28bb-44ca-bf79-6a3d730d9f1a",
                              customer_id: "0b558669-a50d-48d7-9862-604411210ad6",
                              customer_name: "6Ss7attO0KDvZ2PuoFKU33PYYZTEIyRndmm72c26Cd6B3OB7swghUIdkqUOY2HAI87h7tC8vMnTzjNmFWDzLZEPN7HQXwymFrbXYvN3cal4RO9jT63dRDxKNVo",
                              terminal_id: "d3085e22-2090-4a65-b7cc-d7ef61ad46e1",
                              transaction_id: "76ba0a1e-5a4a-4184-a767-6dc9536c8ccd",
                              organization_code: "5--66---0",
                              private_money_id: "286b2aff-1133-49bc-b8e7-3fd658419da3",
                              is_modified: true,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_12
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              to: "2024-02-07T00:18:51.000000+09:00",
                              page: 1836,
                              per_page: 8878,
                              shop_id: "0fd3be87-5a46-41cc-850b-5ced1949a5f5",
                              customer_id: "fc9860b9-1785-4e2d-927c-ff565354c9b4",
                              customer_name: "TQ1eFfFoOmA6KgKFTgUMIqeaKPydQtxKkPEiJ9F7s09s2D07ZJtROtnJyz65lsPnpU0js5rsIZ4cWpER3UtPkG2eq1I6SZr9Xo8DUROCVDxPSk72x92MmliF",
                              terminal_id: "c125b0ac-8437-4935-8d5e-ac409e6006a4",
                              transaction_id: "8d65d325-aa46-4b1e-9b68-605ca0b25be2",
                              organization_code: "KvUQCe9g1-pc3n9--z---qEPH-",
                              private_money_id: "19c2ba7f-219f-4a06-b5e3-66342fae0485",
                              is_modified: false,
                              types: ["exchange_outflow", "exchange_inflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_13
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              from: "2019-11-19T13:18:57.000000+09:00",
                              to: "2023-08-17T15:58:28.000000+09:00",
                              page: 7192,
                              per_page: 3376,
                              shop_id: "e40db014-b033-483d-8441-9fee5e06359b",
                              customer_id: "38b979eb-23dc-407e-b6c2-9fd4b9a70ad4",
                              customer_name: "gxHzzgdLIxgPMdYrCUsTg7mFBD5JyTl3OSbQF6o9LFFmkiVCdqahnfY1HR9DfMzD3LCASqee9bY3sHOGNF3Mai4m7no77RN8AasCH56gnyuHFpFsNPJmzuH",
                              terminal_id: "a80df4b1-7b47-471e-9fc8-b659302db327",
                              transaction_id: "e4d8e6a0-634f-4487-80a6-e4234e8c8b8f",
                              organization_code: "v4-u-fJf-2CG7-0",
                              private_money_id: "257b84cc-1ba7-4b5b-a101-6fd8033c3a63",
                              is_modified: true,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_create_transaction_0
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "49bff2c4-6ad4-4d89-8450-c0031314a294",
                              "87352198-3ed2-4548-9e29-338eb9f94f0c",
                              "899befc5-fe6c-4be0-ac9b-ccde0397b840"
    ))
    assert response.code != "400"
  end

  def test_create_transaction_1
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "49bff2c4-6ad4-4d89-8450-c0031314a294",
                              "87352198-3ed2-4548-9e29-338eb9f94f0c",
                              "899befc5-fe6c-4be0-ac9b-ccde0397b840",
                              description: "QrvWUnk17KWAioiFIGH7shpxz5S2r82nr4Char2DsC6IOlQ3ZCa8lZmMT5mAFAIeN7EOzXnRCcbLOsM"
    ))
    assert response.code != "400"
  end

  def test_create_transaction_2
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "49bff2c4-6ad4-4d89-8450-c0031314a294",
                              "87352198-3ed2-4548-9e29-338eb9f94f0c",
                              "899befc5-fe6c-4be0-ac9b-ccde0397b840",
                              point_amount: 6377,
                              description: "4tjoxBAROpiRc0j39oPNkDTFwGmGihFz2z0gAPfWDnSv3peMsqUtDBVf5JNWPBp"
    ))
    assert response.code != "400"
  end

  def test_create_transaction_3
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "49bff2c4-6ad4-4d89-8450-c0031314a294",
                              "87352198-3ed2-4548-9e29-338eb9f94f0c",
                              "899befc5-fe6c-4be0-ac9b-ccde0397b840",
                              money_amount: 2515,
                              point_amount: 6144,
                              description: "QtetKx5V0IU"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_0
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "acb7702b-6828-4fa0-b15e-f39f8c7937c8",
                              "022ec883-88b2-4c71-b560-331159b22dae",
                              "f3d5e6ff-a5f9-4bc8-8277-ce2bf931998b"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_1
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "acb7702b-6828-4fa0-b15e-f39f8c7937c8",
                              "022ec883-88b2-4c71-b560-331159b22dae",
                              "f3d5e6ff-a5f9-4bc8-8277-ce2bf931998b",
                              description: "52367FRSK6ZN3dPGJYhssMJ1c81K9V4uwaN6FqKGuMQEbIhSKLSxcJDAAH0jwIPbMhYlMMXruKsOetb8P3w3wpAlq46MRFhBa1KSFCImukjAtQPb0UOTifX7KrzTtAdseC51TTzGU05VTqLiAQDTT40IDYkIvu0sCcHMaDTHEOIiZjd"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_2
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "acb7702b-6828-4fa0-b15e-f39f8c7937c8",
                              "022ec883-88b2-4c71-b560-331159b22dae",
                              "f3d5e6ff-a5f9-4bc8-8277-ce2bf931998b",
                              point_amount: 9567,
                              description: "QxmayWcgZvBQUAudiHvhALf0xr0YedjAtAhk4Q5ZEYWHc6DIDKem3xaXPio5o0q9x0iUyrfJOMPlYYA9d24g2qlkQeuW1v6Ot04JjRtKJ3Y50yRg"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_3
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "acb7702b-6828-4fa0-b15e-f39f8c7937c8",
                              "022ec883-88b2-4c71-b560-331159b22dae",
                              "f3d5e6ff-a5f9-4bc8-8277-ce2bf931998b",
                              money_amount: 9949,
                              point_amount: 4219,
                              description: "OZb7LyYKRMPV8lVcOO1w2GShMQxP1XNaA4tMwkt9CEIs7P52Qn8Ps6rGg4gxhQEPHlDMgzo7RyqyjDQCvIVLohtP7YX7LIJvkHIDHAM5JdvPW8u4K9jehE0FIX2d1fsIJRaq4cseT3Jr8x9EZ1qV4Ufa8eD"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_4
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "acb7702b-6828-4fa0-b15e-f39f8c7937c8",
                              "022ec883-88b2-4c71-b560-331159b22dae",
                              "f3d5e6ff-a5f9-4bc8-8277-ce2bf931998b",
                              bear_point_shop_id: "124e9c2f-0101-400a-801e-f125bc1ba34b",
                              money_amount: 5399,
                              point_amount: 6143,
                              description: "BhpNX1jWPk8Z43B0y0B9mfs2NjGqIbT9OwqnkaPpwID0eLyZpFNZ79bus52pNLLPoSL84SGwACEhVooVmB4cFvbTIGcXWAqG4BSfipEZMFGhk16I7iXigWOnUAkBWGfv1h3"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_with_check_0
    response = $client.send(Pokepay::Request::CreateTopupTransactionWithCheck.new(
                              "5ac68b02-38ac-4753-a42d-884bb6b3cb5d",
                              "89b9661c-d2d7-4066-a0dd-895b124a1f3f"
    ))
    assert response.code != "400"
  end

  def test_create_payment_transaction_0
    response = $client.send(Pokepay::Request::CreatePaymentTransaction.new(
                              "156d5eb7-7a4d-476b-af36-8d2ab9a4c571",
                              "09176af8-cf6c-408d-897d-8054f41d78fd",
                              "8d7939a0-f115-4d67-bd08-408e9a14a861",
                              1580
    ))
    assert response.code != "400"
  end

  def test_create_payment_transaction_1
    response = $client.send(Pokepay::Request::CreatePaymentTransaction.new(
                              "156d5eb7-7a4d-476b-af36-8d2ab9a4c571",
                              "09176af8-cf6c-408d-897d-8054f41d78fd",
                              "8d7939a0-f115-4d67-bd08-408e9a14a861",
                              1580,
                              description: "sH11ZahWwt0KCw4FDQO05qLTqGDb"
    ))
    assert response.code != "400"
  end

  def test_create_transfer_transaction_0
    response = $client.send(Pokepay::Request::CreateTransferTransaction.new(
                              "a77b6581-23fa-4b1f-9104-52c40b0b0875",
                              "af154061-0546-4ef6-b456-46f30e8cea03",
                              "c429a9e1-84c4-44d5-8d23-d0e7ac255a21",
                              3169
    ))
    assert response.code != "400"
  end

  def test_create_transfer_transaction_1
    response = $client.send(Pokepay::Request::CreateTransferTransaction.new(
                              "a77b6581-23fa-4b1f-9104-52c40b0b0875",
                              "af154061-0546-4ef6-b456-46f30e8cea03",
                              "c429a9e1-84c4-44d5-8d23-d0e7ac255a21",
                              3169,
                              description: "HPHLfj8VAxLQCn6DppPY7uZKs5wMf3MBYDCuFCMBOgtd28MFakoJp4sttlPyu0hLTf3LV1FvqM27O2bqybT3XFSWXNEvBDebROkI568yn3vAdg2WzE6cQfJbdKVhYmdIeaGtyZiVBFtaHsVEu5jHLt1IIKsQ450xUM6O5hfI4vi32RsgmtpDzruBR"
    ))
    assert response.code != "400"
  end

  def test_create_exchange_transaction_0
    response = $client.send(Pokepay::Request::CreateExchangeTransaction.new(
                              "d0a9b5e0-cf3f-45b2-a206-7970e1badb43",
                              "e9593d3f-ad4a-4fe2-85d7-619766aa7d43",
                              "2e386573-4c80-40c6-b158-e44f0f8e3606",
                              760
    ))
    assert response.code != "400"
  end

  def test_create_exchange_transaction_1
    response = $client.send(Pokepay::Request::CreateExchangeTransaction.new(
                              "d0a9b5e0-cf3f-45b2-a206-7970e1badb43",
                              "e9593d3f-ad4a-4fe2-85d7-619766aa7d43",
                              "2e386573-4c80-40c6-b158-e44f0f8e3606",
                              760,
                              description: "OMfbCbRi8MeoObjQBbD5vivOmPF0WWy"
    ))
    assert response.code != "400"
  end

  def test_bulk_create_transaction_0
    response = $client.send(Pokepay::Request::BulkCreateTransaction.new(
                              "Ae43BTjYiVtdGDmgs4Vk2VUx2tI5N4bI",
                              "N",
                              "tWwRJ7taFGOOZNR9womkOYYXss1h0acoAUmA"
    ))
    assert response.code != "400"
  end

  def test_bulk_create_transaction_1
    response = $client.send(Pokepay::Request::BulkCreateTransaction.new(
                              "Ae43BTjYiVtdGDmgs4Vk2VUx2tI5N4bI",
                              "N",
                              "tWwRJ7taFGOOZNR9womkOYYXss1h0acoAUmA",
                              description: "E9DWtANH45sfx8Sg9q1O62IQSAJ63xgskw6yfFQPcXHRn98CcSXK5Zlq5PBZ9vRV0xb"
    ))
    assert response.code != "400"
  end

  def test_get_transaction_0
    response = $client.send(Pokepay::Request::GetTransaction.new(
                              "488e2785-d9e4-4c8b-afc2-d80dbb360dc4"
    ))
    assert response.code != "400"
  end

  def test_refund_transaction_0
    response = $client.send(Pokepay::Request::RefundTransaction.new(
                              "c34bfa2e-9bc5-46aa-b6e4-3a28f9edd396"
    ))
    assert response.code != "400"
  end

  def test_refund_transaction_1
    response = $client.send(Pokepay::Request::RefundTransaction.new(
                              "c34bfa2e-9bc5-46aa-b6e4-3a28f9edd396",
                              description: "HS5KI84n4B4JwtxMbsrynFzleqVzZvPQrwaZ5xfzumz05DAlrcpNez8TuusjLCXuqGq9aXt2RyxOmHZB8Yd9TYL0bkCAVqSRIdac4BtBwC2bbOKrqEvtHSmLf6gZqSXb2Lr55RtyiR"
    ))
    assert response.code != "400"
  end

  def test_list_transfers_0
    response = $client.send(Pokepay::Request::ListTransfers.new(
    ))
    assert response.code != "400"
  end

  def test_list_transfers_1
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              transfer_types: ["topup", "transfer", "payment", "exchange"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_2
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              transaction_types: [],
                              transfer_types: ["transfer", "exchange", "payment", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_3
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              is_modified: true,
                              transaction_types: [],
                              transfer_types: ["transfer", "topup", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_4
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              private_money_id: "368f54fd-1e96-4c50-ba0d-a12f5de9af23",
                              is_modified: true,
                              transaction_types: ["transfer"],
                              transfer_types: ["payment", "topup", "transfer", "exchange"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_5
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              transaction_id: "8241fcb6-d353-4140-8de7-58b4bf444d8d",
                              private_money_id: "c9a7fffa-67cf-482d-a73c-797474cfbc82",
                              is_modified: true,
                              transaction_types: [],
                              transfer_types: ["topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_6
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              customer_name: "0nLBvCfu5QWsdUnRrH9KHVuXFGKt4lw9lRVMCAhIxweHf4mhVFw56RKDemCYdfHKy6kNARZB0e7gSo7Ck5GjWL9QXL9sfwRokQiO2gJLOs7NWiVmOaSDg31Umvi1k0xZepHVlU5UCBk1m",
                              transaction_id: "08e34d43-0f3c-4a32-b611-47b09b9a65fe",
                              private_money_id: "58ec801c-6b00-48d3-a8da-6e491e0e81d0",
                              is_modified: true,
                              transaction_types: ["payment", "transfer", "exchange", "topup"],
                              transfer_types: []
    ))
    assert response.code != "400"
  end

  def test_list_transfers_7
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              customer_id: "50b1b6bd-4942-42c5-b716-6b0691f05a4f",
                              customer_name: "UnBV1wl8i3xQfqNGTjhBSpAIG2GVjRLCF7S26ypTzMExe5LQXN3tfMMeaiTEdRlgPRLO",
                              transaction_id: "37d69ba8-d736-4ebf-a975-2d8af987bb0c",
                              private_money_id: "ac618d34-601c-4499-aff8-e980399e6a28",
                              is_modified: true,
                              transaction_types: ["topup"],
                              transfer_types: ["topup", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_8
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              shop_name: "FskSUixLpvflY8MFYZJvlfPZ9XRs2DjUex8FZcru468uiy2IBQsKNbECUonyUv3nTPZ701h3V5Qywi2pn04JUSx27eVHz2wOx9gOffBCzdPD5lY5ruzs73QnlHzwGBVLp2Vmg3eprOU7ktZcHWsZTpEtZX9770nlSO8H2DCl6imPJgn2XjYsZUpQvLebh65Hdtxmvs4SwxRthVVayjO1th3s3e6fayZ2E32vm3RMvvWttu1PJb3d04",
                              customer_id: "67525409-8bc9-4be6-b305-5b6bb03698fa",
                              customer_name: "Rh2KXDkJqy1UyPaGHVkyMSdmemZcovbEUc9TiM3DTSa7pJlo8JS6mIVfCl8O6XTpGUPEJOaNnRanlNyuKHWuXq7zEzVgAAIhzrVmMQ7zQf4j1Xlnx61iQEXBdwXQXBx9CjvSgZke3VuPIIBeUSxLQqoj9SXP9EgDJcoagTJNb42JvVKNsj3zA7Dw0uibv6O0nFaLFwVLIZnC6rDyYuuG1XnlSIVaCTCoBzc",
                              transaction_id: "e076f30d-b8b3-4883-bcd0-5f6f63474c6c",
                              private_money_id: "bf32907e-7aa9-44fe-b325-4a6432d4c003",
                              is_modified: true,
                              transaction_types: ["exchange", "topup"],
                              transfer_types: ["exchange", "payment", "transfer", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_9
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              shop_id: "325b0ce2-36fe-4113-b054-736b9d27f651",
                              shop_name: "9CA458OFUiC0xNjD1g6ausYOsWjmgSVes0LvRpIOKLgAa2m76DTKceEBbKe1QbzWrTYvHigdBYvKVDdotVdsHD1HarFGRZ0Q28LywVGUz2sIRxtNbAY",
                              customer_id: "fb3046e0-b79d-4340-8dfa-a1c80d5219fc",
                              customer_name: "ePlwRHJLPebYCA3qabphyjXP3xuhhy9uGRsNNOdzmZ5nbPQzPRirLmp7HiQajpl09",
                              transaction_id: "9b146e26-ef95-42a7-a4b6-e5d1137f740c",
                              private_money_id: "10abaa49-b0a4-4669-88a9-8161a01a7d00",
                              is_modified: true,
                              transaction_types: ["topup", "transfer", "payment"],
                              transfer_types: ["payment", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_10
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              per_page: 1324,
                              shop_id: "180f6db0-c1c7-4608-8793-483d48bbb718",
                              shop_name: "i4ivBi3eJhDgAiQ5RhXwEfmyakwCi2K41MKrJ8u3JtJHw13BJLqURa9CDG8z1r52NxmvSo3IMgKOG9RqgqLtsxscDVj4qDxwlIsjYdDsgNzWfMVYN8tFORiCKaN1GSBkTmsnETZgON7wI25XD4LDGgtc1eHQx1a38fcy9G2ru7CIugZBUKc64A8KJDFHDE0sPhVLSmxr0FU3DnW6K",
                              customer_id: "5608c25b-1d92-410e-99f1-9ff3a5830e98",
                              customer_name: "DEeelMkJvsg1mQveiZolVhKjCQVZwzstz19XaUt7HUg2vBtQ3icUlEOMImvGy37aG3VpRlqKVbLVJ59qzi8HFxZtC5ypm8TU2Y6m10oazOnSDRVBADkHpYoJtK8deELoxPb8vCqW8ZrqfNGAkbzmAIScfq8JbwsU",
                              transaction_id: "e6e1826a-238e-4f9f-80c6-601ffb2032e8",
                              private_money_id: "931b2c72-db3a-4f2d-b329-864e46986df7",
                              is_modified: false,
                              transaction_types: ["exchange"],
                              transfer_types: ["payment", "transfer", "exchange"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_11
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              page: 9106,
                              per_page: 2791,
                              shop_id: "e060bcf5-9cca-435b-a9a5-c36f4da811ae",
                              shop_name: "nAr0O5BazmKqHUlvI3TLRDU2wR06BrqE4xR4GA8B6QEvmEtQTqfIDfhF08aWAgYKgMRg4eijui0x4AzukqXii06wz9NdLnaFp0d8NnYZXWwwPUfmYGEVrOM4dkj0diMGxwkBMFBNKhTrrGkGVnz7dW1L5JRcqWGZoB7J2SLBuVTFPFKYeglUQAESlFenRvUgW2C0Pk55puUaBmR66mDvQf3SzEAz6sFhOXUyleHUBygYL",
                              customer_id: "7706d498-d34c-4885-8e4a-db2aaa2caf46",
                              customer_name: "bbjnOxn1Ii4QyBabDj1sJ7k6dP6L13ja9VovumOjMgFfs83kBzSot4H9G2QRAYPymeRfFOHsPVjb9UCbPcYx5YXiYOW0oa5SUOR88F7Ubd6EIlmfbIWBjq1h3aM3MFSn6Z9Xp0dYAIwKPnm62HiK775FUjJKUwWsCFULHC5xu9xwKzEEFrv0p5VC2XFSxIKMXYPxeKc6v3uyZaCEMZ2Ju8UbXHSU9E0Qlg3gebv",
                              transaction_id: "8a480fc1-4577-4907-9d6a-c87cf26f7afa",
                              private_money_id: "a387e891-8847-4c38-9559-5e87acab0e1d",
                              is_modified: true,
                              transaction_types: ["exchange", "transfer", "payment"],
                              transfer_types: ["topup", "payment", "exchange"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_12
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              to: "2019-11-11T08:12:33.000000+09:00",
                              page: 1333,
                              per_page: 7237,
                              shop_id: "8795a258-99ce-4774-aa73-f5e7e833cbb9",
                              shop_name: "PgQkXqYPn4dGIxCAVXu8wPFdMI0g8RX9GwTm1EaeDH0runis",
                              customer_id: "8c96adbc-8bae-4d9f-8c56-901c04e72a3f",
                              customer_name: "A8D7RtvLwRN8QmXijHIyMGxrgTxrmP2c2b7AqdqrRaU4tsNqOUthYSxSa5qYfKcdpEzIZoGgQ8JT7nM2XSRS8qzeJVaYua2WPHw1UTjf1quigD2l2JnK33Y2PKkmhgdj1RbwEdGAkTKdkw",
                              transaction_id: "faa5b900-9944-428f-9a2a-b745b058a667",
                              private_money_id: "de760078-73fb-4ab5-8577-64070047582e",
                              is_modified: false,
                              transaction_types: ["exchange", "transfer"],
                              transfer_types: ["exchange"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_13
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              from: "2022-04-19T07:02:50.000000+09:00",
                              to: "2024-12-17T08:41:43.000000+09:00",
                              page: 9221,
                              per_page: 2642,
                              shop_id: "a11be964-42a4-4ea5-9a9f-225fd2da3f6f",
                              shop_name: "RUOUAciXVcpzKCMcrOD6Emk2wkp2iXzqZDQWG9JIPYO9QhKjYAAaWngq9PQfQxKRvEszf3mWAEHwNafuFelOU7xCAyi0eUz4xXH5OLhVoB1lIuiOfxpiSD0ualUMr1aiXbRr0Yt6Ont0eqhymEV4KDx3FmD9kbbli1vOnH69EFivIjA6JEHCCuKlnfNVTWFTkh4YZxFDhr8QjYlB42oGAhylpmFOwCdKPABZdrg",
                              customer_id: "4861db91-7698-4d9d-a8b9-d21c6724cbb8",
                              customer_name: "RslDBuoJSIFUrTRne91u8KmONYXCce6NgXmM6SU8mT9N7YdoyhvIOK96oQgvpt3OE4bGWfPwqWxwC3DU0ZYNIFrYHkTuOzrywGRNkAeSHinr7X7r9y8K62vZdczxzKDF7OzztIRdIBCYTSHrtKwD",
                              transaction_id: "8a61d083-aedd-4920-92e2-9dc648949c5e",
                              private_money_id: "29ab12ff-fe4a-4c78-9ab9-f6be43528871",
                              is_modified: false,
                              transaction_types: ["payment", "transfer", "topup"],
                              transfer_types: ["exchange", "payment", "transfer", "topup"]
    ))
    assert response.code != "400"
  end

  def test_create_organization_0
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "qJMjy6rf4CluMJ3q8UHdGY9c6av2in",
                              "Qmoszzzj7gjncZRjG49ZyE9dB8fCGfTM2Oyolj4kfEe2uvMtiKxUivt9MIJ97msI3tBe6ti0SO07EXHC5hQ61pWDcVyEH0QvPCR5IiYZhX71qxxC",
                              ["b59cb597-c346-447d-aa5e-abd741577908", "6ca2ef06-38f4-47c7-a2ba-8b73c7e88ff3", "5dea01e2-5eb8-4f0c-b6c4-b57fc67a7ea4", "fd2d0fb9-3996-45d8-885a-850d5c673ca3", "0e88aee6-acef-4605-8c7b-c388346e7a0e"],
                              "8j2fPJCGzV@Ydoh.com",
                              "DRxcepsSsd@ecsp.com"
    ))
    assert response.code != "400"
  end

  def test_create_organization_1
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "qJMjy6rf4CluMJ3q8UHdGY9c6av2in",
                              "Qmoszzzj7gjncZRjG49ZyE9dB8fCGfTM2Oyolj4kfEe2uvMtiKxUivt9MIJ97msI3tBe6ti0SO07EXHC5hQ61pWDcVyEH0QvPCR5IiYZhX71qxxC",
                              ["b59cb597-c346-447d-aa5e-abd741577908", "6ca2ef06-38f4-47c7-a2ba-8b73c7e88ff3", "5dea01e2-5eb8-4f0c-b6c4-b57fc67a7ea4", "fd2d0fb9-3996-45d8-885a-850d5c673ca3", "0e88aee6-acef-4605-8c7b-c388346e7a0e"],
                              "8j2fPJCGzV@Ydoh.com",
                              "DRxcepsSsd@ecsp.com",
                              contact_name: "EcH6zAIM8ju98Xf3eDqYA5vYg7TRPpd99WNI7yrXSKnnTIb76zTEtm8AaIiuGx9L9HalOMU5vigXX7Icn5jXA5QxJPbbGkUILhTXtRtmknLVk7hQOvzRC9zFhAU2LnJOGL09rr"
    ))
    assert response.code != "400"
  end

  def test_create_organization_2
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "qJMjy6rf4CluMJ3q8UHdGY9c6av2in",
                              "Qmoszzzj7gjncZRjG49ZyE9dB8fCGfTM2Oyolj4kfEe2uvMtiKxUivt9MIJ97msI3tBe6ti0SO07EXHC5hQ61pWDcVyEH0QvPCR5IiYZhX71qxxC",
                              ["b59cb597-c346-447d-aa5e-abd741577908", "6ca2ef06-38f4-47c7-a2ba-8b73c7e88ff3", "5dea01e2-5eb8-4f0c-b6c4-b57fc67a7ea4", "fd2d0fb9-3996-45d8-885a-850d5c673ca3", "0e88aee6-acef-4605-8c7b-c388346e7a0e"],
                              "8j2fPJCGzV@Ydoh.com",
                              "DRxcepsSsd@ecsp.com",
                              bank_account_holder_name: ".",
                              contact_name: "BaBOdWWGJsxArgIuumMVdl31leH5Dl7ZUHzS51rJLdw2n2tQfnXr078yWrpzKRIJrBD5D7CpKjeG53Xpalhw5eupOSaoLetupiLJGKA08kULtDXm7mGq20CccqYOFtqhMLy1fSrOZfn"
    ))
    assert response.code != "400"
  end

  def test_create_organization_3
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "qJMjy6rf4CluMJ3q8UHdGY9c6av2in",
                              "Qmoszzzj7gjncZRjG49ZyE9dB8fCGfTM2Oyolj4kfEe2uvMtiKxUivt9MIJ97msI3tBe6ti0SO07EXHC5hQ61pWDcVyEH0QvPCR5IiYZhX71qxxC",
                              ["b59cb597-c346-447d-aa5e-abd741577908", "6ca2ef06-38f4-47c7-a2ba-8b73c7e88ff3", "5dea01e2-5eb8-4f0c-b6c4-b57fc67a7ea4", "fd2d0fb9-3996-45d8-885a-850d5c673ca3", "0e88aee6-acef-4605-8c7b-c388346e7a0e"],
                              "8j2fPJCGzV@Ydoh.com",
                              "DRxcepsSsd@ecsp.com",
                              bank_account: "04",
                              bank_account_holder_name: "(",
                              contact_name: "7HbtOFrcDL7mosyloW0gLyNig5qU771SYwG9bLFfHIbs98VpOgmc8pS7WZiumuB2TNJcJGvSmksA1MuW1A79SIV4QucaCTIuwp4PaSBE0QhobjzNQVW3hP0Ve0rN3Em7q1SjNjatjjDZX7RIKgDX3b9oA142xLkpis0qy5MfISyoLqEQKhMnAGBrL3Keptreugp"
    ))
    assert response.code != "400"
  end

  def test_create_organization_4
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "qJMjy6rf4CluMJ3q8UHdGY9c6av2in",
                              "Qmoszzzj7gjncZRjG49ZyE9dB8fCGfTM2Oyolj4kfEe2uvMtiKxUivt9MIJ97msI3tBe6ti0SO07EXHC5hQ61pWDcVyEH0QvPCR5IiYZhX71qxxC",
                              ["b59cb597-c346-447d-aa5e-abd741577908", "6ca2ef06-38f4-47c7-a2ba-8b73c7e88ff3", "5dea01e2-5eb8-4f0c-b6c4-b57fc67a7ea4", "fd2d0fb9-3996-45d8-885a-850d5c673ca3", "0e88aee6-acef-4605-8c7b-c388346e7a0e"],
                              "8j2fPJCGzV@Ydoh.com",
                              "DRxcepsSsd@ecsp.com",
                              bank_account_type: "current",
                              bank_account: "8",
                              bank_account_holder_name: " ",
                              contact_name: "kvKQdinTisU7JGahMN0pspm5VBpWaMfH3OlTb5uoxVylmhf3ESdF"
    ))
    assert response.code != "400"
  end

  def test_create_organization_5
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "qJMjy6rf4CluMJ3q8UHdGY9c6av2in",
                              "Qmoszzzj7gjncZRjG49ZyE9dB8fCGfTM2Oyolj4kfEe2uvMtiKxUivt9MIJ97msI3tBe6ti0SO07EXHC5hQ61pWDcVyEH0QvPCR5IiYZhX71qxxC",
                              ["b59cb597-c346-447d-aa5e-abd741577908", "6ca2ef06-38f4-47c7-a2ba-8b73c7e88ff3", "5dea01e2-5eb8-4f0c-b6c4-b57fc67a7ea4", "fd2d0fb9-3996-45d8-885a-850d5c673ca3", "0e88aee6-acef-4605-8c7b-c388346e7a0e"],
                              "8j2fPJCGzV@Ydoh.com",
                              "DRxcepsSsd@ecsp.com",
                              bank_branch_code: "",
                              bank_account_type: "other",
                              bank_account: "805",
                              bank_account_holder_name: "G",
                              contact_name: "9g89rUgV81h6fR4XXAReVSL8MjPf2nDJncUb7prKqWXHoSFTkZLdy8B9WWqNrXVXI1wRTqwqzVsahBGWwps3iARDJTRZkOOEQFC19Wtss23YjQBhHozeYJjV02y90GWowMI3ASCsApxBJptaJJRDQ6YTYkiFEIISprQ3cmpI6bh8YrVsWGSghDCw1Un7nnaTSFczRArCskatgTSAk3a8TcT02JvhzyAvEGRwH1gqt79bzapcrIrLur4lrAgRY4"
    ))
    assert response.code != "400"
  end

  def test_create_organization_6
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "qJMjy6rf4CluMJ3q8UHdGY9c6av2in",
                              "Qmoszzzj7gjncZRjG49ZyE9dB8fCGfTM2Oyolj4kfEe2uvMtiKxUivt9MIJ97msI3tBe6ti0SO07EXHC5hQ61pWDcVyEH0QvPCR5IiYZhX71qxxC",
                              ["b59cb597-c346-447d-aa5e-abd741577908", "6ca2ef06-38f4-47c7-a2ba-8b73c7e88ff3", "5dea01e2-5eb8-4f0c-b6c4-b57fc67a7ea4", "fd2d0fb9-3996-45d8-885a-850d5c673ca3", "0e88aee6-acef-4605-8c7b-c388346e7a0e"],
                              "8j2fPJCGzV@Ydoh.com",
                              "DRxcepsSsd@ecsp.com",
                              bank_branch_name: "qmYCDpX8Ny7Ex4zLyYmVuuwRZjnfS",
                              bank_branch_code: "169",
                              bank_account_type: "other",
                              bank_account: "",
                              bank_account_holder_name: ".",
                              contact_name: "Ev5pCv1ztILSktq1cNxb1w0fAXCRcSE6z5QHSLVITcWyXkWwNeThLpKI1N6RIMY7t0u9TuR54ZsbCHGDImjW34z4jE8W9hhkpYWEzZLn5uyvbNkfkqdGOYba42tK1ETZVrimXQx2toEzw7Z1gM6fgx4uEjyIUvTVKqmlOa23scUcryj4GBWTbDzAVeKXVT"
    ))
    assert response.code != "400"
  end

  def test_create_organization_7
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "qJMjy6rf4CluMJ3q8UHdGY9c6av2in",
                              "Qmoszzzj7gjncZRjG49ZyE9dB8fCGfTM2Oyolj4kfEe2uvMtiKxUivt9MIJ97msI3tBe6ti0SO07EXHC5hQ61pWDcVyEH0QvPCR5IiYZhX71qxxC",
                              ["b59cb597-c346-447d-aa5e-abd741577908", "6ca2ef06-38f4-47c7-a2ba-8b73c7e88ff3", "5dea01e2-5eb8-4f0c-b6c4-b57fc67a7ea4", "fd2d0fb9-3996-45d8-885a-850d5c673ca3", "0e88aee6-acef-4605-8c7b-c388346e7a0e"],
                              "8j2fPJCGzV@Ydoh.com",
                              "DRxcepsSsd@ecsp.com",
                              bank_code: "2561",
                              bank_branch_name: "Up6ljdawfubjQ03lDRu1dHypEu4pqRk9KXyywxfAsv",
                              bank_branch_code: "",
                              bank_account_type: "current",
                              bank_account: "",
                              bank_account_holder_name: "｣",
                              contact_name: "tPfKAW4UwDxtqXzHNdytk1inQrWiktMK0FHLyLnvzTdFf0Y1JODoBhEEJFs7RURiJHf6mnglgKA3t551AWYy2EKxgIvudVQKM3ivlyVYA6fe68jtm2G7nC3SW8MPeFKTYT7eEYLwvHQFKDImV0W8uMWRziTXMumFeaEHdh8PePoMZwnAEmuUL6pb761IWS7zT"
    ))
    assert response.code != "400"
  end

  def test_create_organization_8
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "qJMjy6rf4CluMJ3q8UHdGY9c6av2in",
                              "Qmoszzzj7gjncZRjG49ZyE9dB8fCGfTM2Oyolj4kfEe2uvMtiKxUivt9MIJ97msI3tBe6ti0SO07EXHC5hQ61pWDcVyEH0QvPCR5IiYZhX71qxxC",
                              ["b59cb597-c346-447d-aa5e-abd741577908", "6ca2ef06-38f4-47c7-a2ba-8b73c7e88ff3", "5dea01e2-5eb8-4f0c-b6c4-b57fc67a7ea4", "fd2d0fb9-3996-45d8-885a-850d5c673ca3", "0e88aee6-acef-4605-8c7b-c388346e7a0e"],
                              "8j2fPJCGzV@Ydoh.com",
                              "DRxcepsSsd@ecsp.com",
                              bank_name: "jmF3XMzgKDKO5o6UqQsbMF41dYUnemzRdROKbGph7rDrumGN6tQ3",
                              bank_code: "",
                              bank_branch_name: "wFKRF7w7plclcWB9bNRwQ0LABzL",
                              bank_branch_code: "351",
                              bank_account_type: "other",
                              bank_account: "9367327",
                              bank_account_holder_name: "ﾐ",
                              contact_name: "pN21EzYv53e8C68gL6nh3hboA1VaXQqYz47H8v5OYX2Bb7kgjpYtpWxkJ26TN1VktFjJy7P4SbKkoz4u4vqNtkYjPXUyJ1V0r5CHRNT2ecfLdc33OSn94wpSCBGnb27KI1Ko9Ro9P2UOPHKcZd7kJ0a09BOfpTrIxahzBDxgf0eAPjokEVHRFLghiMn2sJjV2bGnLruRc9c27Gpu"
    ))
    assert response.code != "400"
  end

  def test_list_shops_0
    response = $client.send(Pokepay::Request::ListShops.new(
    ))
    assert response.code != "400"
  end

  def test_list_shops_1
    response = $client.send(Pokepay::Request::ListShops.new(
                              per_page: 3616
    ))
    assert response.code != "400"
  end

  def test_list_shops_2
    response = $client.send(Pokepay::Request::ListShops.new(
                              page: 4202,
                              per_page: 177
    ))
    assert response.code != "400"
  end

  def test_list_shops_3
    response = $client.send(Pokepay::Request::ListShops.new(
                              external_id: "bIXfazIWogjdxJNEfM7Zph",
                              page: 251,
                              per_page: 2784
    ))
    assert response.code != "400"
  end

  def test_list_shops_4
    response = $client.send(Pokepay::Request::ListShops.new(
                              email: "x62f8FNzaD@el7r.com",
                              external_id: "o4JT6XY3Y33ek4ahxmsrZJPb5B",
                              page: 7684,
                              per_page: 7244
    ))
    assert response.code != "400"
  end

  def test_list_shops_5
    response = $client.send(Pokepay::Request::ListShops.new(
                              tel: "025-3743899",
                              email: "0D5go4dBLd@UCSZ.com",
                              external_id: "Vd4cTqnNfSRiXL",
                              page: 3355,
                              per_page: 6745
    ))
    assert response.code != "400"
  end

  def test_list_shops_6
    response = $client.send(Pokepay::Request::ListShops.new(
                              address: "xof4N3bX72yEerLNEKMYsRf9vriYiP8HndtLKgFWIeB413C8zcpa0a0ipuLt3I",
                              tel: "011-467678",
                              email: "U3XBigR3jy@a01c.com",
                              external_id: "7edhmrVi5NIsb",
                              page: 4950,
                              per_page: 8995
    ))
    assert response.code != "400"
  end

  def test_list_shops_7
    response = $client.send(Pokepay::Request::ListShops.new(
                              postal_code: "5414590",
                              address: "L8YRreNoLAWMJdywYSICtYcbHl2ktF16gpa54attROZcBbejZS9wdnnNKINI7vj8qEDPsdJ8JkL6K4fbUt",
                              tel: "0399394-305",
                              email: "vhUXmrc210@VozY.com",
                              external_id: "z4wR",
                              page: 7482,
                              per_page: 1244
    ))
    assert response.code != "400"
  end

  def test_list_shops_8
    response = $client.send(Pokepay::Request::ListShops.new(
                              name: "Gfv1ooHMcqzJF0zVNZ8zHF5mnetJol0g7uhhZVwBBSB9NQuG198o4cE8ye8xiCptr8X3OQSs9cvMVMzYpfEHHq4AVCPhpF",
                              postal_code: "628-6437",
                              address: "2NE9OohrFLhvABt92YjeNGkeRyZCxDwnyuzPdWfYw482S6oHFsZh9ksnqTSKQYaLtgBF21Mao0iMx72McbAtuQfbwPK5Ol2Udeu5ClBnNsqGtwvAjO8SQrjpTlUKU7ix6vD3BTnNcaIv4Cy2qiGNeSDJueWNAF2iLhkB08mWoSEw",
                              tel: "033552184",
                              email: "ANGzSZe49q@KV1r.com",
                              external_id: "h",
                              page: 1687,
                              per_page: 9628
    ))
    assert response.code != "400"
  end

  def test_list_shops_9
    response = $client.send(Pokepay::Request::ListShops.new(
                              private_money_id: "a234dbec-dc4c-4c28-ac8a-a5a3f83b86a4",
                              name: "fHAgpNJKDDEjuzSmETPUL6TDRxNmjKWPDEzen9VEh9JKwUlzsxb9tQKSZdMATJHlP3s2aiyvcn732KUYpvpwWJTv2DUcmsWBTf3SfgLVNlOhNoRUioebBno3HZhnyNZ5Q77U04aLs4hmy4C28WnCRfz2leovb1R7O6QOgboW2zpcaLxa2QZma6CRo8nyJO9Y3f9djMgk8QSZwJ1udEIb7zDJ6KZTEk0mDRGqd8jGihF2zo2",
                              postal_code: "7933713",
                              address: "YDG6CZS1PVe5LZzi2NmWBluHrzflOytNd3ROmH9nMfAHnX3LOs6P3dxLhDjrt4CFESWJnPCLUxGLtrgoghS3pPHE574eeX1ksH4R2MgyW6z149JBRZmQUgzecqWdDVSstoEtPVoykbtA6l7WDayqQLAKXyhWYdlIHfSBBKI1KQl4cK6HLesoN7AsxjaX4bkzo",
                              tel: "05-3136-165",
                              email: "E829PJZq44@v95w.com",
                              external_id: "TBAsM3ixdWcd35lz",
                              page: 2504,
                              per_page: 2536
    ))
    assert response.code != "400"
  end

  def test_list_shops_10
    response = $client.send(Pokepay::Request::ListShops.new(
                              organization_code: "--6",
                              private_money_id: "625749dd-6e5c-40cc-b01c-10b52d65e7db",
                              name: "RSiRG2UPRPUxcw9rvtxOfCP20hUm1E2Nlz5V1CO5TSFyNtopqI6bCrDgQTiBz8hopleWuv10dzqDmxXKufPIjjJpzSXKPSRMVYMVxniANdM0yy6srRZNC9bYJUFWp4SJDd9Vw0ghvUwHY4GPMgqa4p3NBV6jnDEmNinmBAkCQlWqd4VgtaT7nx9nCCSGOYqsqY",
                              postal_code: "325-4012",
                              address: "7j8S1LcJM99jV6h5DQ4TL9sXbFiutZ4wFjGxBLsRpox6uXLc6he8Kxv6FPaZ8I6AxiybIUdjn2JlMSQ6V8dRYSFDiggsas4Nm4Pbqn0MLycuAIyd8Tc91YrDumA0BEPaxu5hz8quH88gYqQC45YQs",
                              tel: "05-3989808",
                              email: "VorEq6zLZy@g3cE.com",
                              external_id: "Ps9b",
                              page: 5756,
                              per_page: 7247
    ))
    assert response.code != "400"
  end

  def test_create_shop_0
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "7e1DJRmWCvXV5f7NFxRTTWOKh4cp2t8rtdj0F82hhuu2d72PSRBNNGTP71wc"
    ))
    assert response.code != "400"
  end

  def test_create_shop_1
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "7e1DJRmWCvXV5f7NFxRTTWOKh4cp2t8rtdj0F82hhuu2d72PSRBNNGTP71wc",
                              organization_code: "3--a58FP-e"
    ))
    assert response.code != "400"
  end

  def test_create_shop_2
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "7e1DJRmWCvXV5f7NFxRTTWOKh4cp2t8rtdj0F82hhuu2d72PSRBNNGTP71wc",
                              shop_external_id: "HHuXDOcuycPW2WYY40yWZt9ZjH",
                              organization_code: "86h2gJ6nU-9"
    ))
    assert response.code != "400"
  end

  def test_create_shop_3
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "7e1DJRmWCvXV5f7NFxRTTWOKh4cp2t8rtdj0F82hhuu2d72PSRBNNGTP71wc",
                              shop_email: "o4hVc0u6tz@aZ3s.com",
                              shop_external_id: "YKCNybmAlkaNJiOvuRswwQSmiJco3Kwhjqp",
                              organization_code: "-wj5gb75f95uL"
    ))
    assert response.code != "400"
  end

  def test_create_shop_4
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "7e1DJRmWCvXV5f7NFxRTTWOKh4cp2t8rtdj0F82hhuu2d72PSRBNNGTP71wc",
                              shop_tel: "050020-026",
                              shop_email: "8O3WzYFSGY@9bWV.com",
                              shop_external_id: "NBEz14f9BIpTXI2luGWaGy1CoCYoYmaLr1B",
                              organization_code: "Il571zI"
    ))
    assert response.code != "400"
  end

  def test_create_shop_5
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "7e1DJRmWCvXV5f7NFxRTTWOKh4cp2t8rtdj0F82hhuu2d72PSRBNNGTP71wc",
                              shop_address: "Atf2GPfHYeeJWiJLn1TOWVNqKCYgaN6maSZWJn127yVjYZzSkjksojB4PnV9sBfF1BkHf1A87wLQ9bOIRS2WYI5ck8HRSP5FHw4UX4tGWi4N1WpwhPzDe8V1DYdcKn6nAl4cEX71br7jv7EDkwXN76HyKk1SGbd2fzw9nBi",
                              shop_tel: "089587-4148",
                              shop_email: "cXyEVzhZku@2OJw.com",
                              shop_external_id: "UM0ktk1yse4CdNhZgpKbkXWC5tLF",
                              organization_code: "z-az-l-eJrYIdo"
    ))
    assert response.code != "400"
  end

  def test_create_shop_6
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "7e1DJRmWCvXV5f7NFxRTTWOKh4cp2t8rtdj0F82hhuu2d72PSRBNNGTP71wc",
                              shop_postal_code: "5543208",
                              shop_address: "4K7ompotaJBLyz8KN17fLxPU1GvU5oJnH6hOfBgmDSuxOmphkziTG6p4HsLeIcNrFvlQBIX1JBgnrD1yLFlL5kbgs6xUgxf5sOofYseOtl3ilNOPpyIVjtUkLTSkOKux630Id9YuKsTGECV",
                              shop_tel: "05311512113",
                              shop_email: "rWWdK2ybDt@XJii.com",
                              shop_external_id: "kZzBktm983ksDdKfbC96DBMvuC0QTf",
                              organization_code: "J2-S---8Ew61X7---5S6-pZ"
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_0
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2e520760-4acd-45ae-9c6f-036650786ca4"
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_1
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2e520760-4acd-45ae-9c6f-036650786ca4",
                              page: 8928
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_2
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2e520760-4acd-45ae-9c6f-036650786ca4",
                              per_page: 1178,
                              page: 6386
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_3
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2e520760-4acd-45ae-9c6f-036650786ca4",
                              from: "2022-03-03T06:55:14.000000+09:00",
                              to: "2020-08-09T04:55:26.000000+09:00"
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_4
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2e520760-4acd-45ae-9c6f-036650786ca4",
                              from: "2016-03-11T09:00:10.000000+09:00",
                              to: "2022-06-07T11:17:08.000000+09:00",
                              page: 7881
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_5
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2e520760-4acd-45ae-9c6f-036650786ca4",
                              from: "2016-05-17T02:25:00.000000+09:00",
                              to: "2019-03-22T00:52:22.000000+09:00",
                              per_page: 5676,
                              page: 6566
    ))
    assert response.code != "400"
  end

  def test_list_customer_transactions_0
    response = $client.send(Pokepay::Request::ListCustomerTransactions.new(
                              "422ed98d-62d2-4517-8531-10711846fb87"
    ))
    assert response.code != "400"
  end

  def test_list_customer_transactions_1
    response = $client.send(Pokepay::Request::ListCustomerTransactions.new(
                              "422ed98d-62d2-4517-8531-10711846fb87",
                              per_page: 3210
    ))
    assert response.code != "400"
  end

  def test_list_customer_transactions_2
    response = $client.send(Pokepay::Request::ListCustomerTransactions.new(
                              "422ed98d-62d2-4517-8531-10711846fb87",
                              page: 6031,
                              per_page: 8401
    ))
    assert response.code != "400"
  end

  def test_list_customer_transactions_3
    response = $client.send(Pokepay::Request::ListCustomerTransactions.new(
                              "422ed98d-62d2-4517-8531-10711846fb87",
                              to: "2019-11-20T02:14:38.000000+09:00",
                              page: 4763,
                              per_page: 7717
    ))
    assert response.code != "400"
  end

  def test_list_customer_transactions_4
    response = $client.send(Pokepay::Request::ListCustomerTransactions.new(
                              "422ed98d-62d2-4517-8531-10711846fb87",
                              from: "2023-04-06T22:20:35.000000+09:00",
                              to: "2015-11-28T02:32:52.000000+09:00",
                              page: 2030,
                              per_page: 6273
    ))
    assert response.code != "400"
  end

  def test_list_customer_transactions_5
    response = $client.send(Pokepay::Request::ListCustomerTransactions.new(
                              "422ed98d-62d2-4517-8531-10711846fb87",
                              is_modified: false,
                              from: "2020-10-20T09:05:15.000000+09:00",
                              to: "2024-08-07T01:15:21.000000+09:00",
                              page: 625,
                              per_page: 769
    ))
    assert response.code != "400"
  end

  def test_list_customer_transactions_6
    response = $client.send(Pokepay::Request::ListCustomerTransactions.new(
                              "422ed98d-62d2-4517-8531-10711846fb87",
                              type: "khaasWI8",
                              is_modified: true,
                              from: "2017-10-05T13:18:59.000000+09:00",
                              to: "2016-02-28T04:44:44.000000+09:00",
                              page: 595,
                              per_page: 9627
    ))
    assert response.code != "400"
  end

  def test_list_customer_transactions_7
    response = $client.send(Pokepay::Request::ListCustomerTransactions.new(
                              "422ed98d-62d2-4517-8531-10711846fb87",
                              receiver_customer_id: "d84a35b6-54b2-4adf-8703-78078f35232b",
                              type: "e0ne6pcNR",
                              is_modified: false,
                              from: "2021-02-21T22:29:24.000000+09:00",
                              to: "2016-05-20T21:53:53.000000+09:00",
                              page: 5835,
                              per_page: 8049
    ))
    assert response.code != "400"
  end

  def test_list_customer_transactions_8
    response = $client.send(Pokepay::Request::ListCustomerTransactions.new(
                              "422ed98d-62d2-4517-8531-10711846fb87",
                              sender_customer_id: "442c42a5-23a6-41f2-a62f-0f46a7a56e44",
                              receiver_customer_id: "72c26cdd-99be-480a-b407-2bb7a1fc6e7f",
                              type: "gNL9",
                              is_modified: true,
                              from: "2019-12-31T16:11:29.000000+09:00",
                              to: "2022-02-04T22:57:25.000000+09:00",
                              page: 394,
                              per_page: 8404
    ))
    assert response.code != "400"
  end

end
