# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

require 'minitest/autorun'
require "pokepay_partner_ruby_sdk"
require "inifile"

$client = Pokepay::Client.new(File.expand_path("~/.pokepay/test-config.ini"))
$inifile = IniFile.load(File.expand_path("~/.pokepay/test-config.ini"))

class PokepayTest < Minitest::Test

  def test_that_it_has_a_version_number
    refute_nil ::Pokepay::VERSION
  end

  def test_get_ping_0
    response = $client.send(Pokepay::Request::GetPing.new(
    ))
    assert response.code != "400"
  end

  def test_send_echo_0
    response = $client.send(Pokepay::Request::SendEcho.new(
                              "PdzRpofhC"
    ))
    assert response.code != "400"
  end

  def test_get_user_0
    response = $client.send(Pokepay::Request::GetUser.new(
    ))
    assert response.code != "400"
  end

  def test_list_user_accounts_0
    response = $client.send(Pokepay::Request::ListUserAccounts.new(
                              "17c47d8d-70c6-4697-8f19-b7dae5693b35"
    ))
    assert response.code != "400"
  end

  def test_get_account_0
    response = $client.send(Pokepay::Request::GetAccount.new(
                              "28bd1cfd-e8ed-4e72-a28c-02b9e4d603f4"
    ))
    assert response.code != "400"
  end

  def test_update_account_0
    response = $client.send(Pokepay::Request::UpdateAccount.new(
                              "1dccee4d-5768-432a-a9b4-6c518bf9c687"
    ))
    assert response.code != "400"
  end

  def test_update_account_1
    response = $client.send(Pokepay::Request::UpdateAccount.new(
                              "1dccee4d-5768-432a-a9b4-6c518bf9c687",
                              is_suspended: false
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_0
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "dae10b8f-8fae-4719-b1f7-ad96bdbb4bba"
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_1
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "dae10b8f-8fae-4719-b1f7-ad96bdbb4bba",
                              per_page: 3188
    ))
    assert response.code != "400"
  end

  def test_list_account_balances_2
    response = $client.send(Pokepay::Request::ListAccountBalances.new(
                              "dae10b8f-8fae-4719-b1f7-ad96bdbb4bba",
                              page: 3509,
                              per_page: 3569
    ))
    assert response.code != "400"
  end

  def test_create_customer_account_0
    response = $client.send(Pokepay::Request::CreateCustomerAccount.new(
                              "44c4325c-4709-4a81-b732-a687b2a88b17"
    ))
    assert response.code != "400"
  end

  def test_create_customer_account_1
    response = $client.send(Pokepay::Request::CreateCustomerAccount.new(
                              "44c4325c-4709-4a81-b732-a687b2a88b17",
                              account_name: "ZgUTboP4f1Mga65qjhzBo6j2yfXAfhS3mGi4l1ccag9YvnMUJYtHxM8PWTaJSDC6sUNoYilAgtegug9azcU7ciyw2zH4jxeWhGBLAJ9KWbacAYT9JvsQ6VrA5RDTw9pPlpazLDqI0dfA5mql"
    ))
    assert response.code != "400"
  end

  def test_create_customer_account_2
    response = $client.send(Pokepay::Request::CreateCustomerAccount.new(
                              "44c4325c-4709-4a81-b732-a687b2a88b17",
                              user_name: "RKv1xZu7VHJ3sMsX18hWNeMna95jEDLXkYT4h0NZSfwZMNoxDVLcJFwQWYf9stzhEOq3ygdRObm9arwmkDefZjr79GBkarTrRv2PKdEgS8z3qp5V3rzxKoXcmdeAx643yfZWu0x",
                              account_name: "HZ3FsTordqjNt7iJxCLOxRgbTdQLC499IrJz1yD84gcVyMqhet76jOnZ1VnBdWJesvvzErEJFKg7LEuRcH6K3nqJQFWUZbzIcuTnRj5d4l04lrf5ePGIoAeDMQmdDUVaRY1hpzcMw6i9Rt8MgM9OYZH7gteUIZ2f24vFeRJi3nWbSdMBfULQMgiWfdsFe7wwtZ6OYrWgTydNW8GOO35lxK3AAqgqX"
    ))
    assert response.code != "400"
  end

  def test_list_bills_0
    response = $client.send(Pokepay::Request::ListBills.new(
    ))
    assert response.code != "400"
  end

  def test_list_bills_1
    response = $client.send(Pokepay::Request::ListBills.new(
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_2
    response = $client.send(Pokepay::Request::ListBills.new(
                              upper_limit_amount: 3829,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_3
    response = $client.send(Pokepay::Request::ListBills.new(
                              lower_limit_amount: 6508,
                              upper_limit_amount: 2498,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_4
    response = $client.send(Pokepay::Request::ListBills.new(
                              shop_id: "e09c382a-700f-4ed8-8ee3-07e6aec8e4a1",
                              lower_limit_amount: 2396,
                              upper_limit_amount: 29,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_5
    response = $client.send(Pokepay::Request::ListBills.new(
                              shop_name: "i36yaEeb0rlweR88nbvnAtOtUwwvAuUOsOSuXGyuaHs8Xix4eHYvrdsZA9DstdzMDyZCDgta82dHuzDidjJ5gDZdGUN8KacNjujsMxhdM7q9ZgVE7EO9C5ojOjSFgA9b8aMJxz9nMUzmy4QXYUacEFM5sebL9jTV2GT7JMwg3B9SCXDlVHfLCIszjzZv0FcqUi6U3mCKZeYAxilSjJANsSEQlR1Mna3nFXkueyRDmRvtbsFqHo9VA9Z",
                              shop_id: "dd7b568a-6f8d-4786-b07a-f60b89ecec6c",
                              lower_limit_amount: 6235,
                              upper_limit_amount: 6118,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_6
    response = $client.send(Pokepay::Request::ListBills.new(
                              created_to: "2023-05-31T21:18:30.000000+09:00",
                              shop_name: "WfM92SOYnc0UEreny1cPC5zdVliAoV1itV6r0YRP5uXQB3YHa9OKVwqrw30UWauv3GSRJi7DdWn99DEH5vD89XGtsdge9XqMEsg3TuyebHcZxRZDyId97HqHP0l2YfU7uScu3KBUcZqXE4EAdIZl",
                              shop_id: "e2240ae7-a5da-45a4-85f3-a3d92716dfa3",
                              lower_limit_amount: 2955,
                              upper_limit_amount: 2998,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_7
    response = $client.send(Pokepay::Request::ListBills.new(
                              created_from: "2018-09-05T10:58:18.000000+09:00",
                              created_to: "2021-08-29T01:20:31.000000+09:00",
                              shop_name: "vd0px8qeG7ytV1y3yKI1zikUvmQSfz9",
                              shop_id: "6923b461-73ff-4c70-9206-0ac0cab51dee",
                              lower_limit_amount: 5056,
                              upper_limit_amount: 3565,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_8
    response = $client.send(Pokepay::Request::ListBills.new(
                              description: "vFtNRLjH7RmuZoIYxDprwLDQyyKYsmR1rgNTgNzmm4v",
                              created_from: "2017-06-07T02:11:30.000000+09:00",
                              created_to: "2024-08-21T14:24:57.000000+09:00",
                              shop_name: "d7QPD2lPhX2ikP70KhSRsW35YrNs1C4WZ7JExK3jgeC6GAbEkYcwKFYanSjHEEgD6pipdQ488hKPZgtsqNx9op8QiFnFQyRhQsuygpAQ5zqMDZvtxhLmnft0KKD2IFSzlrZgeFbn9iHKBZg6KpB17HRW7chyhaTPveea8RuEi0SxhS010ZfV3jyvv8iowjiV4j0hVdgGhIGXfiYO5FJYl6nNDCxGRQqw",
                              shop_id: "0f2ca3d9-a94c-4b66-a6f2-9afdee11d136",
                              lower_limit_amount: 9348,
                              upper_limit_amount: 8949,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_9
    response = $client.send(Pokepay::Request::ListBills.new(
                              organization_code: "d08oTqO-c-98",
                              description: "q4j7Tugmmzlevei51CJI3OLUh5qrtaRfsEQq59AOwIQMrcI",
                              created_from: "2022-02-17T15:42:33.000000+09:00",
                              created_to: "2023-08-19T23:48:57.000000+09:00",
                              shop_name: "QOpNXr7xo1TwSZtLYKbna6rHsBwzeC654So7QivwF73DaQOaHJAo74vj5",
                              shop_id: "41ec8489-2a8d-46ca-83b1-1446baae9bb2",
                              lower_limit_amount: 3817,
                              upper_limit_amount: 5243,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_10
    response = $client.send(Pokepay::Request::ListBills.new(
                              private_money_id: "8d813ab7-83e4-4e01-bfe3-e7cf97304106",
                              organization_code: "--Cy-dCw-X-",
                              description: "XlCSQzD8rGwmnCDqWs59rPuq9P7e0yncGC5n7DB9L3ZC4gLn2nszUa3rOrTOSj9q6whBOG8zWAvCHcguvdgAXGAswMbVMyuTW7jcms14g7Jm5NjYpuOivn2Go8XNjUM554m02EQ9m2rQBpVeirJoNIQPmoEc2xepGRvHrMmRkks4a9g8",
                              created_from: "2018-04-15T11:31:53.000000+09:00",
                              created_to: "2016-03-13T04:33:49.000000+09:00",
                              shop_name: "o0oDYA13h0ahD99ZLOMXaQN8",
                              shop_id: "b584e005-6723-4674-8088-423892823107",
                              lower_limit_amount: 193,
                              upper_limit_amount: 3931,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_11
    response = $client.send(Pokepay::Request::ListBills.new(
                              bill_id: "NgzXeJ9Av",
                              private_money_id: "63af492b-265d-4c03-aeba-eabb0bdf3a6c",
                              organization_code: "-1gq-26--101-qd5-Qw---5-z-OI6--5",
                              description: "F1MiKBV6XqZig07OF3BOfGPA5qGt81CpQyFDriVESRXhfF9HL759WboZxRCI3BFllvoYWRZFSJU1s6SLQKICePyV0BLQKaAGhbXfs8pkTxOxTryatFlPA90D5",
                              created_from: "2020-11-03T14:01:07.000000+09:00",
                              created_to: "2023-10-29T20:22:44.000000+09:00",
                              shop_name: "1j8Zhs2SUD71aJFdn0O3J8cHqlCkSijJvw2S0fU0ZWEWaimY2Im0eQtl1A31gBgiecEI2u4f0Tjzkg0uAR9KrklBM7vJ0CTJHOpsTJTqaLx2OUgaOs3T",
                              shop_id: "4dfdc737-f7a5-4238-96f6-a32e28bfd7ed",
                              lower_limit_amount: 9505,
                              upper_limit_amount: 9661,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_list_bills_12
    response = $client.send(Pokepay::Request::ListBills.new(
                              per_page: 8642,
                              bill_id: "qJRne",
                              private_money_id: "34e49e0d-100c-45ad-b204-5f5ebe38f592",
                              organization_code: "-7-AWlz7ao-gscR3---A",
                              description: "d6dN8T46VYOByHIShbtVXRzSvNZ2ydWUhpFuHm5WHb0TofF7EL2n7XdcHw2qAkZlg5S9i036I2oToUN4brf4qEcvkDNmonZmRbieBkCaNWuqsyBIUMEorqvOor2ZzWQ79uSIwEwRdMUuQGZu",
                              created_from: "2019-03-29T23:50:47.000000+09:00",
                              created_to: "2019-04-26T15:23:26.000000+09:00",
                              shop_name: "EmZxjFI3CYCV1gpI9rQbALnMToyJJOUSARCM3UhIq38pWNwsIhpqpVJhqkdRCDj56TS9y7pR3FH3fGpnSiABcZ7z4DlGI57wlC6BVR3gOaph",
                              shop_id: "a5f8629b-6c05-4b1e-8b78-1ec83f730545",
                              lower_limit_amount: 1815,
                              upper_limit_amount: 9081,
                              is_disabled: false
    ))
    assert response.code != "400"
  end

  def test_list_bills_13
    response = $client.send(Pokepay::Request::ListBills.new(
                              page: 1126,
                              per_page: 5077,
                              bill_id: "v5g",
                              private_money_id: "f1b35c0e-529c-4207-b551-e98bf9f394a0",
                              organization_code: "-87-m8O5--3-79a5sBvHA-2-qwHe",
                              description: "pKMVmIXJYmoYC98vL1jeTxmIWN4yIuKPW6occhpb1MoMf5COBvj4AIWmYKY7",
                              created_from: "2023-04-14T04:05:29.000000+09:00",
                              created_to: "2018-11-16T02:30:13.000000+09:00",
                              shop_name: "YTweCuDaHTFsk4sUbTT0ORjvBm5fDd567UtWPdzBvarifCd3tmnDN9LdIaJu7ojVxd22p1xPsp2butjmHhiJ",
                              shop_id: "87d067ce-4a8b-41a3-92dd-f958c636ab21",
                              lower_limit_amount: 3295,
                              upper_limit_amount: 4964,
                              is_disabled: true
    ))
    assert response.code != "400"
  end

  def test_create_check_0
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 9260
    ))
    assert response.code != "400"
  end

  def test_create_check_1
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 9491,
                              description: "7k"
    ))
    assert response.code != "400"
  end

  def test_create_check_2
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 1820,
                              is_onetime: false,
                              description: "gN4l2goxnHJWTi4kqq7MwoHQjxDXxz01W"
    ))
    assert response.code != "400"
  end

  def test_create_check_3
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 7373,
                              usage_limit: 9797,
                              is_onetime: false,
                              description: "WRG5Mac6rOuLVftdqNKI2yPqKdIpYVAkgmHeJN7m0CUF3lNMPxCUQV24"
    ))
    assert response.code != "400"
  end

  def test_create_check_4
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 5099,
                              expires_at: "2025-05-28T10:06:03.000000+09:00",
                              usage_limit: 2818,
                              is_onetime: false,
                              description: "LAKJzcTi4dzVRf6oOvHUJHEsj5hqRWno3tkKdKM0zy5rycRl0yDvARpmwdAUo0f9esErPFYcbOWZKy2wv733dPwAsJNP9lZ5DPaMNtlnWFFly7DuwyefVdLBfAj3cYXxmG0bjWx8W8R9QyEn3AIm5l"
    ))
    assert response.code != "400"
  end

  def test_create_check_5
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 3148,
                              point_expires_at: "2024-06-21T21:11:43.000000+09:00",
                              expires_at: "2020-06-12T12:35:26.000000+09:00",
                              usage_limit: 6623,
                              is_onetime: true,
                              description: "Ty2glwESjyWQMv2vaNJJKhEc7ptekpPY9SMdi0KCj9Uhuahq61OBlUv6A0VvCREVfnWkvrpOJk7yemE"
    ))
    assert response.code != "400"
  end

  def test_create_check_6
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 4428,
                              point_expires_in_days: 3115,
                              point_expires_at: "2025-02-08T13:31:18.000000+09:00",
                              expires_at: "2017-12-06T16:54:48.000000+09:00",
                              usage_limit: 1260,
                              is_onetime: false,
                              description: "bjsz7hLy6B2ISJYYXncMekKdlJ2jC0a"
    ))
    assert response.code != "400"
  end

  def test_create_check_7
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 9562,
                              bear_point_account: "5cbcc568-76e1-46da-a791-f5c255041c05",
                              point_expires_in_days: 9240,
                              point_expires_at: "2018-05-14T18:43:33.000000+09:00",
                              expires_at: "2020-12-19T21:33:59.000000+09:00",
                              usage_limit: 4566,
                              is_onetime: false,
                              description: "kV063IWfBGefW6SZwfAm99KsyHbyQDT6H5r8OUiQPPqNSjwjUFsXSCyF8yryfimE6EzUlikp88d30FrA1aGpBZKdbGzkJdOq34fYHxGpO6yE8tJcNrXQvTq3fpSwd82WHkcuTzWza7c57EU2UyILj9o0jMYA6KaaNSYzzTZ"
    ))
    assert response.code != "400"
  end

  def test_create_check_8
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 4264,
                              point_amount: 2063
    ))
    assert response.code != "400"
  end

  def test_create_check_9
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 5714,
                              point_amount: 6039,
                              description: "8nTGlcKpVHwl9A5IBsUvSSmkElLlfvclm3eXH9GORV0kvxrmUxPGMVsq7n9NXgVqwgW9eydZ4pwCFhJLAKoIWk3kL"
    ))
    assert response.code != "400"
  end

  def test_create_check_10
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 711,
                              point_amount: 6336,
                              is_onetime: false,
                              description: "Nns1niQKgs8xpK9b26454yQaJrgoe1R9TF9uCp871g6mpznejEJfv7apiwATC9RasL3linvaXb0Y2XTsSja"
    ))
    assert response.code != "400"
  end

  def test_create_check_11
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 9469,
                              point_amount: 8872,
                              usage_limit: 576,
                              is_onetime: true,
                              description: "G12NUuq7wN1nIW743wJHa0qcYY883mAW0"
    ))
    assert response.code != "400"
  end

  def test_create_check_12
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 7905,
                              point_amount: 7788,
                              expires_at: "2021-09-10T18:49:38.000000+09:00",
                              usage_limit: 847,
                              is_onetime: true,
                              description: "KUsPGc6cksUamvUYoWab5yaEUMtw2NykkyLDWB0dvRg90UMPfwUcTZTkYj5tMyu5HST2t6rtcp3B7kSS1rYteqidESjI8vkZlOy8iSvADmv4Hl62klUzZlbzL5nDTT3xZVkBtcMsN6WDlUF0270drVZ4qr5LqZodLCN9VbUBe59BgBE6mIh2ZB9Knxg7"
    ))
    assert response.code != "400"
  end

  def test_create_check_13
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 954,
                              point_amount: 4026,
                              point_expires_at: "2017-11-20T16:31:21.000000+09:00",
                              expires_at: "2019-03-20T21:36:11.000000+09:00",
                              usage_limit: 6135,
                              is_onetime: true,
                              description: "yZhdOaiG9iStD12DEk0qDzOhswUTpSzLSQqADkAl11JZYFPtIBfINRnEURyZAQI177J2WV2jn85xQBUNAe5X3QEOGjRht0KqbHMKN4Ui5wsR5TKMY5ehr"
    ))
    assert response.code != "400"
  end

  def test_create_check_14
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 485,
                              point_amount: 5517,
                              point_expires_in_days: 1127,
                              point_expires_at: "2020-03-05T07:54:47.000000+09:00",
                              expires_at: "2022-02-26T17:08:00.000000+09:00",
                              usage_limit: 3881,
                              is_onetime: true,
                              description: "gCyJsa7dAHTfeOt6EeBYqyNMPn8pR2p9d9swF7kyPRXuUgHaDMuimjwnujWZWrcnFkJtfx5kqYmmLrAXnXePfUZHlhKf7wfGkxf0dS1UoqnR4WUtx"
    ))
    assert response.code != "400"
  end

  def test_create_check_15
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              money_amount: 452,
                              point_amount: 5620,
                              bear_point_account: "83dd9774-94d4-4363-862d-5e5a874f601a",
                              point_expires_in_days: 2717,
                              point_expires_at: "2020-01-07T10:29:13.000000+09:00",
                              expires_at: "2021-01-19T19:33:07.000000+09:00",
                              usage_limit: 1629,
                              is_onetime: true,
                              description: "ekk8MWsgwhbssM7CQvZslXpgabtrbE2lZWLY6ZFU1Z1kEVx0wzh85MTLImDUoaufoODaSVAERBurZqymXHjb4Q3IuhVjpYDjMg4trVWW96j13z"
    ))
    assert response.code != "400"
  end

  def test_create_check_16
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              point_amount: 8228
    ))
    assert response.code != "400"
  end

  def test_create_check_17
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              point_amount: 4302,
                              description: "O0gEOetGq0zAfIBdaQv3LieHyhwWfAXrW50TyI8CFsFmexGFXZqLNhaTcUSPfdVxAdjNsEe9c0k5SXvQjqonf6Z0ABqt2le7tUz1Uhx2htzytpn3bPJLjSAwKKeSnTVrpa6JsBAkOl5pdee5y34OompY2QiDodnrIdulCtUhdnXiH8diolVq0vF3"
    ))
    assert response.code != "400"
  end

  def test_create_check_18
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              point_amount: 7636,
                              is_onetime: false,
                              description: "rIk9XQf1tNVwZYXWQL49bD1SA5Lk2MrAqI1lizKSue2fd6luB0E1faKOkzNd1Nd0mbg39OF03O9ZABK8DJOH7svRSk8GdzAB6uNfOXgR1sigFlpKAYRbX8UMgWamzleDsIxnBwEPiVGr3lK5tziC1Z0B6YXgzOhR88tI1swCU9rU"
    ))
    assert response.code != "400"
  end

  def test_create_check_19
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              point_amount: 4021,
                              usage_limit: 7160,
                              is_onetime: false,
                              description: "UMUtD0zdllfzgmTnRBzVs5DP5RsHER0jRZKgFyx9ZLwsi8JdZcUHD2rgg7Gze3gvRWMWsQQrshhR4CDya"
    ))
    assert response.code != "400"
  end

  def test_create_check_20
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              point_amount: 5508,
                              expires_at: "2025-01-01T03:13:18.000000+09:00",
                              usage_limit: 4319,
                              is_onetime: false,
                              description: "0Lwv00FtXMCX2IlAmDKahkhlpZw0ZA06SDh8UL3hHFKAv5JYuAiSQuhXumKisULFXo37U3r81mJBjG9eAC7aGEhGLTRGVWKDeEtqUuAilf"
    ))
    assert response.code != "400"
  end

  def test_create_check_21
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              point_amount: 4975,
                              point_expires_at: "2018-06-19T13:29:44.000000+09:00",
                              expires_at: "2016-01-12T13:32:48.000000+09:00",
                              usage_limit: 1698,
                              is_onetime: true,
                              description: "GOxoCkSww5U77MLqG5z8rJ81G1U39JU4nt3IEpgT4HMbTUyizW2jjcy85ThZO1ic0WHEor7AURDL"
    ))
    assert response.code != "400"
  end

  def test_create_check_22
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              point_amount: 8461,
                              point_expires_in_days: 8219,
                              point_expires_at: "2020-10-27T06:27:26.000000+09:00",
                              expires_at: "2016-04-23T05:22:33.000000+09:00",
                              usage_limit: 4147,
                              is_onetime: true,
                              description: "fnlQZE4wr1TaUvDxBw6ihfGehDqb8p3ztMbZWRxAUySLzShAIVQ3Z"
    ))
    assert response.code != "400"
  end

  def test_create_check_23
    response = $client.send(Pokepay::Request::CreateCheck.new(
                              "f69a5036-be9c-4f38-b6b9-0d335d64513f",
                              point_amount: 4673,
                              bear_point_account: "5f168d42-2421-4bc4-b616-7e12cfbc9feb",
                              point_expires_in_days: 9701,
                              point_expires_at: "2025-03-13T19:45:24.000000+09:00",
                              expires_at: "2024-04-13T15:10:13.000000+09:00",
                              usage_limit: 6416,
                              is_onetime: false,
                              description: "hNXjL5CMVSRGAorimtuQUUi4KVzIUhLHPvXYiQiAFKujrPeyCFGVUauJZe7oNoAq0QmBz2toqo33Zcb1bxQPGIUoYcsN"
    ))
    assert response.code != "400"
  end

  def test_list_transactions_0
    response = $client.send(Pokepay::Request::ListTransactions.new(
    ))
    assert response.code != "400"
  end

  def test_list_transactions_1
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              types: ["payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_2
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              is_modified: true,
                              types: ["exchange_outflow", "topup", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_3
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              private_money_id: "a30be6c5-111b-4f9d-a5d3-c1390b90a752",
                              is_modified: true,
                              types: ["exchange_outflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_4
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              organization_code: "5-N3BKu-KB",
                              private_money_id: "4ceec640-f69a-4ed2-86f0-c592af53c097",
                              is_modified: false,
                              types: ["topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_5
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              transaction_id: "d753ca0c-dbb7-4998-abb0-f57f697e5271",
                              organization_code: "9z-9LG7D-V00Z9054--at1",
                              private_money_id: "32b6dd3b-7062-4b1c-8708-f257df05e238",
                              is_modified: false,
                              types: ["exchange_inflow", "payment", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_6
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              terminal_id: "93905710-2749-4ae0-b953-35b924fe0f47",
                              transaction_id: "1e44a4b5-c01e-4ed2-ba0e-a74ff2f692d6",
                              organization_code: "wMF-TVac-F5BGX5-3y5-M-Ruwl-IYJV7",
                              private_money_id: "32df5240-000c-43eb-97a1-a228facca30b",
                              is_modified: true,
                              types: ["exchange_inflow", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_7
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              customer_name: "KM9jdtQMZmUuTRno7xreo2JPbkY7IKliL7LCaOGyqjz6noJHO9wjIayuQXGXiEuvx8J3GJaBeeA3EpSndEvdxN3z93ErAhk6TYFjrH7ylLLz5OakBU",
                              terminal_id: "c4e4c6aa-1683-4089-b12a-48e8ec2f990c",
                              transaction_id: "37d5d3fc-d6fb-41c8-b42c-55290f2366f3",
                              organization_code: "6V7688lNL",
                              private_money_id: "fd3148ec-cc00-4ef2-9f15-0b6c8754178b",
                              is_modified: false,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_8
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              customer_id: "447b050f-7a72-4af1-ba9d-c57f9da9eac3",
                              customer_name: "vs3bxQzzrWCLiQM1uJW6CcGT0G7LugfECHBc9WgB5m2yznG9MItU7ulPb8XyusAwJsV",
                              terminal_id: "7ecfe995-11e8-4eb4-9c16-68df3b31146a",
                              transaction_id: "beb517c9-d6e7-48d8-aca8-54a66868147d",
                              organization_code: "6-3--Z--xQG--Jd0o8--8-",
                              private_money_id: "e2ae051c-0f24-4a20-94b6-3c0b09ebaeda",
                              is_modified: true,
                              types: ["exchange_outflow", "payment", "exchange_inflow"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_9
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              shop_id: "b0b55885-3314-4e93-a9c3-2e370849327a",
                              customer_id: "3a375406-5759-490e-881d-73e96cee1062",
                              customer_name: "U390kYojSxdoIf2W6YceRUPViVfRcKWiz1nNcjyrsVE5oraXxLOnfx1Ni9lvC52gee3WZarbFuaq0ZSqnF59SaxDA1j8jbbIQZQ39qyLKiq1suFM6KE9p4NRzZEBV4eVPLHPkU4YDuoIyAGUYva7RYnAsau294amEH3S1BkzVMjY6ILz8fWweVM",
                              terminal_id: "52fb096f-f428-412e-85cb-ef6532b82e44",
                              transaction_id: "52ba2384-d590-4c3d-93c1-0ec17106720a",
                              organization_code: "qI-g-Xy9v3-C-PW4o-Om",
                              private_money_id: "972fe732-7726-4865-b03b-db693557d3ee",
                              is_modified: true,
                              types: ["exchange_inflow", "exchange_outflow", "payment", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transactions_10
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              per_page: 2516,
                              shop_id: "2562dedc-c555-4c4b-a4c5-98b726c9799d",
                              customer_id: "80a25311-30d6-4ec3-8100-30cc110d9ca6",
                              customer_name: "Hnn2ANLNEa0UlR8MJqrS9k7OBl8eQGaOIf8bDivwTZlA2sVVNLDiB3voG269NxmBhQYKBuXAdbcrjJH1WEufloJ6Wki5FuxhTiCDSscCDIW0kFVVu46CLvz3xR85bVPEme0PFAi5GyVkO2yy10CblfYPMoDOgHFtkFQbtlr0Y3apv2NrQV5J4lodK4rZsThF9mMABArmeNAOpzVf2LMNqEy0lFE6GKFBY54AMINU7Tf7Y9MslfFQiHbHG60DJQ5",
                              terminal_id: "18bc5088-7763-4afa-b23a-39a6a6cf7fa1",
                              transaction_id: "f1240ed9-8abd-42ff-a6c1-5d98bcdbbc9c",
                              organization_code: "n-o3-Z-OT-",
                              private_money_id: "14812c5e-1e78-4c5a-83e6-bd3ee4485f76",
                              is_modified: false,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_11
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              page: 9260,
                              per_page: 8137,
                              shop_id: "df30c85a-c7e0-4444-8887-f4dbfeac5db7",
                              customer_id: "af7ba68f-abd6-4590-bc4d-01f8af76933e",
                              customer_name: "p2oT6rmGXSGnNry2a4Nf4NNt7mxQTOaobyBF6UDeGq3bV6855Qm05OR78oDCrwOPa3Y8Uwevh9lSKhYTz7v1cctji85WPfjJXeAX0Vz0yvvvxyx4w408xUSIpwJggiIww9H7bxmBn55TL4Jhcr8lTJ5Gdf7CqRo7wtxwIzSrGk0uNsMeAmUSPHAlLbvTQ7TZZbHNTg8ZLFhnhumm14lK8LxbjDrC2kpiR2pteSjQ4SyFj6sEBDvG53nXT2SSSmsQ",
                              terminal_id: "957d05cd-2615-4e75-ba4d-c8eacc5d1473",
                              transaction_id: "ff82e984-44cb-48ba-bee7-3f99e12de4c6",
                              organization_code: "aP-80b-LJW7a-hdn0-2----5W3--",
                              private_money_id: "7bc692b4-e56e-4976-b04f-29cf4fb4b31a",
                              is_modified: true,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_12
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              to: "2023-09-28T22:24:46.000000+09:00",
                              page: 8664,
                              per_page: 1879,
                              shop_id: "1348c4b2-6a16-4581-b68d-a4ef7779e332",
                              customer_id: "e0f83610-f889-4e12-b835-dfe29265a41b",
                              customer_name: "t9Sp7L31APdNizie1HpvCJKe75pCaN5vhIBaRpmeZvYISFk7ukgN6l39dmA4AYxCoemAkqL6zgvyw8CGw7CUnGkylz3qsRIcFgdOndiPRsIWXvVpvLgb3KXMMMugn",
                              terminal_id: "c8441b8d-1ba2-44ac-a133-3137c0b71f04",
                              transaction_id: "de7c5733-94ab-4a47-9efb-a6536ccf8411",
                              organization_code: "TQ44-eV-W--Rt3kf9H-GS-",
                              private_money_id: "4a4304f7-ded7-4c7a-8c30-41ec681c0233",
                              is_modified: false,
                              types: []
    ))
    assert response.code != "400"
  end

  def test_list_transactions_13
    response = $client.send(Pokepay::Request::ListTransactions.new(
                              from: "2019-10-24T06:48:13.000000+09:00",
                              to: "2020-12-06T06:34:34.000000+09:00",
                              page: 6610,
                              per_page: 2220,
                              shop_id: "6951a496-b2b0-4edb-aa2c-5cbdb01e4035",
                              customer_id: "a0e458d6-c7e4-4d48-b6b6-1fbcc126aea9",
                              customer_name: "pYj8JTk1VF2eLeGQcZ5NzMu07FvtJEo5VGiRwMPTNE0NCLfog1wPMQHyufZk1nlK9j6MGAXtTJRABMzSuk5RIhEex3PMj0O4TnVUzausJq1s9p3h8mDI4z3mbA3xTatO1jcJF3nBDKMpDFtFQKMVZ7cyB4msf0njVl3AySikMUO9JIVV5p2Va9kZEEdpYEoIes1MNQYlRxS52dTaiB0mqWx3WWe2ERNlHmLkSVm",
                              terminal_id: "4b21758a-1855-41a7-a9cb-acc65a0ed5e5",
                              transaction_id: "2fd7e3c0-3b6a-412c-b0f8-12b79e1f3e29",
                              organization_code: "-",
                              private_money_id: "37591edc-4dee-42a6-99a8-76be7a2c9cd6",
                              is_modified: true,
                              types: ["payment", "topup", "exchange_outflow"]
    ))
    assert response.code != "400"
  end

  def test_create_transaction_0
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "dacbc703-e902-4219-918a-782f3b370b83",
                              "e422f510-788c-459c-a0af-88bbfa84eef2",
                              "f02796ab-27b0-4dfa-992a-2c89f1164dfb"
    ))
    assert response.code != "400"
  end

  def test_create_transaction_1
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "dacbc703-e902-4219-918a-782f3b370b83",
                              "e422f510-788c-459c-a0af-88bbfa84eef2",
                              "f02796ab-27b0-4dfa-992a-2c89f1164dfb",
                              description: "dfjnTOvNZ0Bsf3pTfeTq8s6BqWPslnalZoEHXHnNFP4UjeH8pwHLJQog39BW3e5uUTgvfxLCV6b04MFhoD02rz7oeu8hgizU4qz4BaXvj4knCHKPDJ7YNe58XECiQyixLraYIkXppy5VTSD9UpS1BvyA0NhHTUnwaRn7en8Roa0VJY35"
    ))
    assert response.code != "400"
  end

  def test_create_transaction_2
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "dacbc703-e902-4219-918a-782f3b370b83",
                              "e422f510-788c-459c-a0af-88bbfa84eef2",
                              "f02796ab-27b0-4dfa-992a-2c89f1164dfb",
                              point_amount: 4250,
                              description: "xlMcu0TKM5ZyDYbaLF8qHW2hoQKU4UPdR0YJtkQiidt9XfJZzIZS5zAZRhAwMO3KIA57yL26FJDtwhB59B7fJ2"
    ))
    assert response.code != "400"
  end

  def test_create_transaction_3
    response = $client.send(Pokepay::Request::CreateTransaction.new(
                              "dacbc703-e902-4219-918a-782f3b370b83",
                              "e422f510-788c-459c-a0af-88bbfa84eef2",
                              "f02796ab-27b0-4dfa-992a-2c89f1164dfb",
                              money_amount: 3036,
                              point_amount: 3008,
                              description: "vv05jLZKTYFx2BAiyI10oKlPPOa5uE5U1hIwHQkR3XylRTXl3k6pqSyX7UGD6XBTu6iQGehBrfLx"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_0
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "d4c31626-994e-4c52-a0a7-d85f334e0de0",
                              "d3778205-e077-49f8-b588-59205b0da221",
                              "8ce3d7a0-e1fe-4de4-a7df-660f593a990f"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_1
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "d4c31626-994e-4c52-a0a7-d85f334e0de0",
                              "d3778205-e077-49f8-b588-59205b0da221",
                              "8ce3d7a0-e1fe-4de4-a7df-660f593a990f",
                              description: "PIhSYz8lBuswr0t9rwjhTAdaLc0Nizistl7tjQpPFAVTHXwT8HddO2BElskvygL0VmKEa"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_2
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "d4c31626-994e-4c52-a0a7-d85f334e0de0",
                              "d3778205-e077-49f8-b588-59205b0da221",
                              "8ce3d7a0-e1fe-4de4-a7df-660f593a990f",
                              point_amount: 2087,
                              description: "OHs9VEsA7CS9V264O1xKEeWC3J3RIgJipFNFowdk0O2BC5pDWztRFy6EOK2KG6IS4HIou6PpUCpgN0qRy2N00wNz5tm8SVPndSwnk4M"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_3
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "d4c31626-994e-4c52-a0a7-d85f334e0de0",
                              "d3778205-e077-49f8-b588-59205b0da221",
                              "8ce3d7a0-e1fe-4de4-a7df-660f593a990f",
                              money_amount: 798,
                              point_amount: 8806,
                              description: "fyyYegaUMBGf0GE1WjtTpnmbx5zbu8p4oaSdT1iLDvb6B0nXAssK0Gh465yV3fVqwVEePbHcvaXEzarOVhGPxIGrAmIzVyvSbG3Q5F3jgfmqz6At2BHKwt8LxJcOcKy57WaUyEIbbi9s"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_4
    response = $client.send(Pokepay::Request::CreateTopupTransaction.new(
                              "d4c31626-994e-4c52-a0a7-d85f334e0de0",
                              "d3778205-e077-49f8-b588-59205b0da221",
                              "8ce3d7a0-e1fe-4de4-a7df-660f593a990f",
                              bear_point_shop_id: "9cb4a592-c567-4891-833b-5214e9163d89",
                              money_amount: 4215,
                              point_amount: 8821,
                              description: "CqUb0urj4Kdlvqe434UFu48UqWNqagaLCpXbZLN39alkXt7kmDq3g1koCcXVmYwIlC5hOQT9NiFnfPRzCucvaGbxK6YqEEvolpQHJIHSxXSGMfCp3B202l4UxeFgMlxJxVOhbPEHz"
    ))
    assert response.code != "400"
  end

  def test_create_topup_transaction_with_check_0
    response = $client.send(Pokepay::Request::CreateTopupTransactionWithCheck.new(
                              "3bfe0ab3-d1d6-465f-a5dd-9d6b748a0ffe",
                              "97ff17b1-5c20-426f-9aa4-a156ee048561"
    ))
    assert response.code != "400"
  end

  def test_create_payment_transaction_0
    response = $client.send(Pokepay::Request::CreatePaymentTransaction.new(
                              "192a92ba-c14b-4194-9152-cda874f8ac31",
                              "6c1e860c-6b2a-44fe-ade9-0c4cb054ac92",
                              "da2b73c1-bbc8-4572-956a-012aed2984b0",
                              6532
    ))
    assert response.code != "400"
  end

  def test_create_payment_transaction_1
    response = $client.send(Pokepay::Request::CreatePaymentTransaction.new(
                              "192a92ba-c14b-4194-9152-cda874f8ac31",
                              "6c1e860c-6b2a-44fe-ade9-0c4cb054ac92",
                              "da2b73c1-bbc8-4572-956a-012aed2984b0",
                              6532,
                              description: "KwNpqDHcwnqcelBBRJn"
    ))
    assert response.code != "400"
  end

  def test_create_transfer_transaction_0
    response = $client.send(Pokepay::Request::CreateTransferTransaction.new(
                              "df004037-0940-4d4e-afe2-e61ef07eee22",
                              "e4f3d429-b2d2-44df-b79a-5bda6536d659",
                              "2193bf24-442c-49ac-8f88-826476ea1e35",
                              7508
    ))
    assert response.code != "400"
  end

  def test_create_transfer_transaction_1
    response = $client.send(Pokepay::Request::CreateTransferTransaction.new(
                              "df004037-0940-4d4e-afe2-e61ef07eee22",
                              "e4f3d429-b2d2-44df-b79a-5bda6536d659",
                              "2193bf24-442c-49ac-8f88-826476ea1e35",
                              7508,
                              description: "P"
    ))
    assert response.code != "400"
  end

  def test_create_exchange_transaction_0
    response = $client.send(Pokepay::Request::CreateExchangeTransaction.new(
                              "7b0dbca1-7e95-4c3f-a217-7ea832f7ce06",
                              "12c16849-b31a-46f1-8791-08f0124fc4ca",
                              "08bdb0a2-0b7b-440f-8f15-14f9264926fe",
                              9338
    ))
    assert response.code != "400"
  end

  def test_create_exchange_transaction_1
    response = $client.send(Pokepay::Request::CreateExchangeTransaction.new(
                              "7b0dbca1-7e95-4c3f-a217-7ea832f7ce06",
                              "12c16849-b31a-46f1-8791-08f0124fc4ca",
                              "08bdb0a2-0b7b-440f-8f15-14f9264926fe",
                              9338,
                              description: "z7FUMSmxg3b90TRFi20ErJflop0GWCJJyY27haLUnx55RrEzCBjzVtzaEpZE0esn1K1WJAfyvxuXa"
    ))
    assert response.code != "400"
  end

  def test_get_transaction_0
    response = $client.send(Pokepay::Request::GetTransaction.new(
                              "450b5871-8db0-4094-b3fe-04d943d85eea"
    ))
    assert response.code != "400"
  end

  def test_refund_transaction_0
    response = $client.send(Pokepay::Request::RefundTransaction.new(
                              "b1985c6d-3c44-4085-a129-8e47fae745bf"
    ))
    assert response.code != "400"
  end

  def test_refund_transaction_1
    response = $client.send(Pokepay::Request::RefundTransaction.new(
                              "b1985c6d-3c44-4085-a129-8e47fae745bf",
                              description: "wxE9d7WJPSnQSA9FEkaJY9J4reru3QcC8scUDL2NA53PRo109moTt4zRh86WIX1bING9xaYuPgzYbsbHc39O0ZAwP0KjMWyCJDf68aOl8wJF72NbaAlkiUcqizk"
    ))
    assert response.code != "400"
  end

  def test_list_transfers_0
    response = $client.send(Pokepay::Request::ListTransfers.new(
    ))
    assert response.code != "400"
  end

  def test_list_transfers_1
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              transfer_types: ["topup", "transfer"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_2
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              transaction_types: ["payment", "topup", "transfer", "exchange"],
                              transfer_types: ["transfer", "payment", "exchange"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_3
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              is_modified: true,
                              transaction_types: [],
                              transfer_types: ["topup", "transfer", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_4
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              private_money_id: "9a13f6c6-c238-46a4-8b8b-7e782aa362a6",
                              is_modified: true,
                              transaction_types: ["exchange", "payment"],
                              transfer_types: ["topup", "exchange", "transfer", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_5
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              transaction_id: "3afc7fd0-cedf-4533-84bb-ea00359b993f",
                              private_money_id: "0f440ea5-fcef-4b4d-b90e-f5ffe8705169",
                              is_modified: true,
                              transaction_types: ["transfer", "payment"],
                              transfer_types: ["payment", "topup", "transfer"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_6
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              customer_name: "L75UjfrMKuxct2LZU2vch8TZhBj3ZkBgbxKZRdsdjqYxYKdtBt5gDK97xKpVZLD9ALFjJCeyHPcQbDs17Qv5hQck9TO0rMeqYDcg6Ve64V3NnkcUrV8eVUulMFGJJIzsuqaJpUyCIxkbyXs86xyaqeC6QHfGSmo9bHh",
                              transaction_id: "563655d6-c0d5-4b5d-8e2d-d1ef2eac68de",
                              private_money_id: "de0fdc4d-2112-43aa-aeda-354a2e7c48e2",
                              is_modified: true,
                              transaction_types: [],
                              transfer_types: ["transfer", "topup", "exchange", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_7
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              customer_id: "78b5dc3e-ead4-42ac-aaed-0265d7a10faf",
                              customer_name: "F6WSOM1UoIeMwkoA4Gpvg9PBu54YwUIsqusTrP1BLiAMaJR3lufIHbLVbeom7UjWoHcRclXC0OypgrCBmJgyZqRrNoIbQJeKMmhONIu56USN9nM2fq3Jj9cGE7SjySuZSG0bIcMF0IXLcSERg",
                              transaction_id: "c3bd3d5a-493d-4c2f-a27e-74432665b733",
                              private_money_id: "e160cbb8-9e65-45fe-ae56-d16619b8d4e1",
                              is_modified: true,
                              transaction_types: ["payment", "exchange"],
                              transfer_types: ["exchange", "transfer", "topup", "payment"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_8
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              shop_name: "iHpfIDN73G81LBIA1X1S7LDjY5H53thyj3L6bbFpHp44h6tlIS5tPEfWVE8U5rShzr4afnrGEyIhyo9Qdo3gAk9Pw6qPCBSvKR1417HSiMVylK2zsbHXEsxUTTKOGm3SkhFlqb5D9pKfMfGlVjUncGT3sqpb59dlCE9hJVHlm8UYW2zeNmakiNpXEikJPsN8QgK8vkPPsxyMlTKjdoJKU0GY7IQuLvr8XMYLtq9FdQxjar0db3lZ5c4Yat",
                              customer_id: "8985355c-b8b7-4820-986b-58a6c502e1cd",
                              customer_name: "zNHA3CkiRXQwD0lDVoifNMHNSW5KiU1ybJqF1lnUTKQpXWkyxkerojxDtEZLta4fkG30TMCO2gxLXYvAymG9tp7ZNELPZtXysYbnqo0om2wklXB8iA7O8X6mQnMEyNqIwlDmIkoCbwKFekDkh2Ao7cd8r5vziR6ykamWjLdqG8IqpZR1bSTPJ3anvxmPSYSELIDMckdvDbqrVlojG0nIpNXF4yr2EYpKiUZ4L53mbnYPXf9Wj04I9ojRRdYPC4",
                              transaction_id: "ec6ba9ed-6351-4d83-a4fc-67a17a3c95f7",
                              private_money_id: "6f311016-ee2b-4e58-9d5c-566a53ace012",
                              is_modified: false,
                              transaction_types: [],
                              transfer_types: ["exchange", "payment", "topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_9
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              shop_id: "15190a86-b631-4546-9779-b651d0444b97",
                              shop_name: "7mhNyzkvVpNH89Duazp",
                              customer_id: "a0cce7c0-9750-4238-9196-75744d37dee6",
                              customer_name: "NX7LdHctmVYUmbyQJy2TUELg359GSGEobRycQBxPLy38DFC15PAiXPXVjNyKYNw312ThYWR2po1Hp4BRr4qahuRheRCVrzcxFMExpGj70w0cVgMjJunm8hbVONIrRvRsTMxXTUcOnKq6REbZ7RVlUmM0WcK0Lg3h3wQjOHqGAhubxgk7DOWLiOwqT3D9mUQ0gVcYTpYqU2H6iDFobgukKHHXlQvb",
                              transaction_id: "772fc909-b9b4-4acc-a113-5fe34ed0f34c",
                              private_money_id: "d08ac186-faa0-433f-98a2-34b43f2bbaf4",
                              is_modified: false,
                              transaction_types: [],
                              transfer_types: ["payment", "exchange", "transfer"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_10
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              per_page: 5888,
                              shop_id: "6ebd2165-2823-41f6-ae23-918195082a90",
                              shop_name: "vLx",
                              customer_id: "fc424333-f558-40ef-8f73-40bf42599f19",
                              customer_name: "uY6B7qjiFO4eD4bzYmByTDHObPs2rnbxdN",
                              transaction_id: "95504480-6a6c-46cf-824a-457f23f322f1",
                              private_money_id: "b7e83527-45b8-4f3f-93ec-3bb480fd175b",
                              is_modified: false,
                              transaction_types: [],
                              transfer_types: ["topup", "exchange", "transfer"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_11
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              page: 7731,
                              per_page: 4937,
                              shop_id: "afbaea9a-e75d-4f3e-9b40-965edce5decc",
                              shop_name: "Iq1igyClhO5mbJdiP74tPbJBNuOShjaWgLcOKB0",
                              customer_id: "440ceb65-8cc0-47f2-9e58-96d766dbbfdd",
                              customer_name: "nCh4CYVH6l1wicDlGjKasoj7kQPRRKdFEbDpIdoV5mIqEyWUvS48uigMJPbZwHbT7yIJ4NMcy51dfcHWentW5E05WvJqAWAy6iWPNe4e5YfGX54JJ5aq5NObbNbxyAZJ6ZmOU6N4dxp050TUOL5uIZSa1rkliDGBg2cdVA",
                              transaction_id: "efd444c8-763b-4b51-a298-975553692b71",
                              private_money_id: "318e700b-acb8-4047-a035-37c586e36caa",
                              is_modified: false,
                              transaction_types: ["payment", "topup"],
                              transfer_types: ["exchange"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_12
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              to: "2020-03-21T09:56:57.000000+09:00",
                              page: 4120,
                              per_page: 6014,
                              shop_id: "8490d3f0-9519-40e6-ab20-c2dce578ff5b",
                              shop_name: "tDVO",
                              customer_id: "0c255a72-7247-4089-961b-3676b9ae5b3e",
                              customer_name: "bmArkLdrJTSeyLjlRnUHD3L4Z8vaM1TtamMXpIXpN5Ts4jCb9xhJinTAuL6e0f9MgtMJ9NP7S5bhDDI9NBwEGB0U7uwUTdvfOBRbZ3CjuMU5Re5zqLTImFVfa2UYDE9DOP8e",
                              transaction_id: "151a744b-4f3d-4dad-8dcc-1b0177edd1ea",
                              private_money_id: "84b38d57-7eff-4218-a41c-5c280db7fe4a",
                              is_modified: false,
                              transaction_types: ["exchange", "topup"],
                              transfer_types: ["topup"]
    ))
    assert response.code != "400"
  end

  def test_list_transfers_13
    response = $client.send(Pokepay::Request::ListTransfers.new(
                              from: "2019-05-29T05:40:41.000000+09:00",
                              to: "2016-11-03T01:26:05.000000+09:00",
                              page: 2395,
                              per_page: 2083,
                              shop_id: "40c5432b-558d-4313-a1f9-31cecdc0c2d3",
                              shop_name: "tQWktnHTS8v",
                              customer_id: "b708b319-1356-48e0-8c79-080a001b23ac",
                              customer_name: "Jh5QE5CxKm9E88gOKpQpz",
                              transaction_id: "4aaf1db5-1f7c-4e91-85ec-7a1c762da34d",
                              private_money_id: "2a450ac0-7a9c-4dc8-b967-f0e366d56724",
                              is_modified: false,
                              transaction_types: ["transfer", "topup", "payment", "exchange"],
                              transfer_types: ["payment"]
    ))
    assert response.code != "400"
  end

  def test_create_organization_0
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "THmuSfgK",
                              "VjvdOgg52mGTXiGNJ4sCu59wYVYzsePAc20LhvUuquUGddyl51Bag3k36Dc34V6P7AiRwD19rn0KHLR9HqAJyXA33sZs6HSYvwiQWFCjBuy09XNpZTkD54IL00Ewp",
                              ["f9760eef-3a83-4838-81f2-42988f44d528", "7abfa23d-f29b-49e8-bb88-a768a1cdbb09", "f23837b8-e7ad-49cd-8fe4-33eae85779e9"],
                              "MmJFmzaafI@xknW.com",
                              "ol5AdxYNHe@JhlW.com"
    ))
    assert response.code != "400"
  end

  def test_create_organization_1
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "THmuSfgK",
                              "VjvdOgg52mGTXiGNJ4sCu59wYVYzsePAc20LhvUuquUGddyl51Bag3k36Dc34V6P7AiRwD19rn0KHLR9HqAJyXA33sZs6HSYvwiQWFCjBuy09XNpZTkD54IL00Ewp",
                              ["f9760eef-3a83-4838-81f2-42988f44d528", "7abfa23d-f29b-49e8-bb88-a768a1cdbb09", "f23837b8-e7ad-49cd-8fe4-33eae85779e9"],
                              "MmJFmzaafI@xknW.com",
                              "ol5AdxYNHe@JhlW.com",
                              contact_name: "d9vRjLOYy6sLX936N4Way82PgrSxDVNCyZO7RZzpYcp3xISQhcYBNudtEbn2gpW3cD84KKP7ciIACowL3QDlta1HcID08ddso4DaBmL1cYOSQeugGAwKolmxEfzhaD2PXtHgwomaTFEWInvUBeLPwZEWNEzVP1KVXAziyb"
    ))
    assert response.code != "400"
  end

  def test_create_organization_2
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "THmuSfgK",
                              "VjvdOgg52mGTXiGNJ4sCu59wYVYzsePAc20LhvUuquUGddyl51Bag3k36Dc34V6P7AiRwD19rn0KHLR9HqAJyXA33sZs6HSYvwiQWFCjBuy09XNpZTkD54IL00Ewp",
                              ["f9760eef-3a83-4838-81f2-42988f44d528", "7abfa23d-f29b-49e8-bb88-a768a1cdbb09", "f23837b8-e7ad-49cd-8fe4-33eae85779e9"],
                              "MmJFmzaafI@xknW.com",
                              "ol5AdxYNHe@JhlW.com",
                              bank_account_holder_name: "ﾝ",
                              contact_name: "ImuKahtd9dk4Esb2oiZiqfySZHxSp0Cjz00vc2XJhgae6r4Get3aihmuyFN3AiTRqhAY04U5IVhYyymmgmSF2yBTlWlPd8HKlPApphFAyUzas7uOLolx2ns1PU6y6PfG9fX56ITAp5hp9zIEeqJBfwyqGu2uC7Z7toAQBZMuoOThw8PZYrDlRWBF19gvkcSEs1"
    ))
    assert response.code != "400"
  end

  def test_create_organization_3
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "THmuSfgK",
                              "VjvdOgg52mGTXiGNJ4sCu59wYVYzsePAc20LhvUuquUGddyl51Bag3k36Dc34V6P7AiRwD19rn0KHLR9HqAJyXA33sZs6HSYvwiQWFCjBuy09XNpZTkD54IL00Ewp",
                              ["f9760eef-3a83-4838-81f2-42988f44d528", "7abfa23d-f29b-49e8-bb88-a768a1cdbb09", "f23837b8-e7ad-49cd-8fe4-33eae85779e9"],
                              "MmJFmzaafI@xknW.com",
                              "ol5AdxYNHe@JhlW.com",
                              bank_account: "0778",
                              bank_account_holder_name: "｣",
                              contact_name: "ONb6UDEqcT44bE9i0xuej7G9gBLZob4TJIDVlo5V93UPeVhaseXhtVrPKgUJmlDNrcUp0rWh9kSE3GBhEqA4fehN8M1PskqXKsHh1ECvx8k3CYjM3mQWa6TL8aNj01NSPpfTYS9UHahMWnBKQ1nlbwYejLu4cEuSziS2q16Z0dKZ8hoGxqqpXW1LBTIOUaKCBAXYzsZoL7qEO0i7o4myu42iBmR0xqM7ihDkVZm7b0zbCrNjkn"
    ))
    assert response.code != "400"
  end

  def test_create_organization_4
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "THmuSfgK",
                              "VjvdOgg52mGTXiGNJ4sCu59wYVYzsePAc20LhvUuquUGddyl51Bag3k36Dc34V6P7AiRwD19rn0KHLR9HqAJyXA33sZs6HSYvwiQWFCjBuy09XNpZTkD54IL00Ewp",
                              ["f9760eef-3a83-4838-81f2-42988f44d528", "7abfa23d-f29b-49e8-bb88-a768a1cdbb09", "f23837b8-e7ad-49cd-8fe4-33eae85779e9"],
                              "MmJFmzaafI@xknW.com",
                              "ol5AdxYNHe@JhlW.com",
                              bank_account_type: "current",
                              bank_account: "38529",
                              bank_account_holder_name: "｢",
                              contact_name: "a4ZX27H8JFdCvGwAdEt6FEXV3iQD7I8Ibi2KVlfKI6Onrg8sHU5ML3Vushn8vEJYpJo0Ovlz8BSZVMppVK2OAv2T72gug2LiT4"
    ))
    assert response.code != "400"
  end

  def test_create_organization_5
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "THmuSfgK",
                              "VjvdOgg52mGTXiGNJ4sCu59wYVYzsePAc20LhvUuquUGddyl51Bag3k36Dc34V6P7AiRwD19rn0KHLR9HqAJyXA33sZs6HSYvwiQWFCjBuy09XNpZTkD54IL00Ewp",
                              ["f9760eef-3a83-4838-81f2-42988f44d528", "7abfa23d-f29b-49e8-bb88-a768a1cdbb09", "f23837b8-e7ad-49cd-8fe4-33eae85779e9"],
                              "MmJFmzaafI@xknW.com",
                              "ol5AdxYNHe@JhlW.com",
                              bank_branch_code: "724",
                              bank_account_type: "saving",
                              bank_account: "7240",
                              bank_account_holder_name: " ",
                              contact_name: "7V1DRK4FtbV7L1uxeG2GYBf3cO2jAVJ2XpkiupXA1gn6O5ZO4ASgD0xppR424sdSx0Jvy7dWUO0TZvCzoECdLLSHXTE60qadAXgeicik20e1mx2bHaHYtpu2XoadouhEroy8WUuwOkBdIHv6iKm1vr36BtvX68FUGrHjV08GfKv5arpRcmjD2DtrsicjzHe0G3B8MCfdvJdJeWodfPzN619qBeKwWA1VKILrC1XN"
    ))
    assert response.code != "400"
  end

  def test_create_organization_6
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "THmuSfgK",
                              "VjvdOgg52mGTXiGNJ4sCu59wYVYzsePAc20LhvUuquUGddyl51Bag3k36Dc34V6P7AiRwD19rn0KHLR9HqAJyXA33sZs6HSYvwiQWFCjBuy09XNpZTkD54IL00Ewp",
                              ["f9760eef-3a83-4838-81f2-42988f44d528", "7abfa23d-f29b-49e8-bb88-a768a1cdbb09", "f23837b8-e7ad-49cd-8fe4-33eae85779e9"],
                              "MmJFmzaafI@xknW.com",
                              "ol5AdxYNHe@JhlW.com",
                              bank_branch_name: "9DQnUjX0R",
                              bank_branch_code: "307",
                              bank_account_type: "saving",
                              bank_account: "778556",
                              bank_account_holder_name: ".",
                              contact_name: "Cbfg6nyabitfxGKQJo8fTXmgJecNnhRgcG00GVhbmn9VQNFcbLSPZYvpcTvEYUxc1aFQ13xyyV96bA0ZoCbimyUNqQD083pJ7WvCUzhySP3dOdgfluR4y0rgxtorwnwmTECa09QBi3YRqFBbyI4ic5a6fy7Dcmnq7vZ1S"
    ))
    assert response.code != "400"
  end

  def test_create_organization_7
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "THmuSfgK",
                              "VjvdOgg52mGTXiGNJ4sCu59wYVYzsePAc20LhvUuquUGddyl51Bag3k36Dc34V6P7AiRwD19rn0KHLR9HqAJyXA33sZs6HSYvwiQWFCjBuy09XNpZTkD54IL00Ewp",
                              ["f9760eef-3a83-4838-81f2-42988f44d528", "7abfa23d-f29b-49e8-bb88-a768a1cdbb09", "f23837b8-e7ad-49cd-8fe4-33eae85779e9"],
                              "MmJFmzaafI@xknW.com",
                              "ol5AdxYNHe@JhlW.com",
                              bank_code: "",
                              bank_branch_name: "kni4zVWyGfL7bejmqiMocAkYi33Z1SO68GzFX924NJnp3EheHxv",
                              bank_branch_code: "635",
                              bank_account_type: "current",
                              bank_account: "48025",
                              bank_account_holder_name: ")",
                              contact_name: "YKiNAaaGuynujsbEP8prKpxWGN1znt9K882mcRT2QPizxSidl065CTcWraKye6rEYOAn0u3KdiAfIDjn3iU6mIt5BQHKDCqGAFRymvh6N4HVFZkq4HdASyKlrexujVCNnDlH7S5hMkOt2koOnjQkCSMqRzxqB57eL7KSYXfGCIfjrchVdGCoXNeVuYLJYVNgLqNcAR7JnjSIWVF4UkfSJAuHAVNaDx"
    ))
    assert response.code != "400"
  end

  def test_create_organization_8
    response = $client.send(Pokepay::Request::CreateOrganization.new(
                              "THmuSfgK",
                              "VjvdOgg52mGTXiGNJ4sCu59wYVYzsePAc20LhvUuquUGddyl51Bag3k36Dc34V6P7AiRwD19rn0KHLR9HqAJyXA33sZs6HSYvwiQWFCjBuy09XNpZTkD54IL00Ewp",
                              ["f9760eef-3a83-4838-81f2-42988f44d528", "7abfa23d-f29b-49e8-bb88-a768a1cdbb09", "f23837b8-e7ad-49cd-8fe4-33eae85779e9"],
                              "MmJFmzaafI@xknW.com",
                              "ol5AdxYNHe@JhlW.com",
                              bank_name: "cM5PFREb4przGRYKOZWwTWZoMtZDdKfYoBcYuLqNA04Im",
                              bank_code: "0665",
                              bank_branch_name: "OXc4LsIdLlazEXdEAfjOWHGAvd",
                              bank_branch_code: "",
                              bank_account_type: "saving",
                              bank_account: "6005152",
                              bank_account_holder_name: "\\",
                              contact_name: "VKmmJEOQxpR7vpM6qJgb0nFg0R2rWjlbdAujrGgPCMunAl1SnPtTKBqtFmJeolcKD5eKEsQ0BAIbh47kWpUn9tsUeLCaIJCVTZ5Hgt5"
    ))
    assert response.code != "400"
  end

  def test_list_shops_0
    response = $client.send(Pokepay::Request::ListShops.new(
    ))
    assert response.code != "400"
  end

  def test_list_shops_1
    response = $client.send(Pokepay::Request::ListShops.new(
                              per_page: 1667
    ))
    assert response.code != "400"
  end

  def test_list_shops_2
    response = $client.send(Pokepay::Request::ListShops.new(
                              page: 3667,
                              per_page: 4148
    ))
    assert response.code != "400"
  end

  def test_list_shops_3
    response = $client.send(Pokepay::Request::ListShops.new(
                              private_money_id: "cf483e56-4f2e-41a3-98cb-0ca14d2820c5",
                              page: 8828,
                              per_page: 7959
    ))
    assert response.code != "400"
  end

  def test_list_shops_4
    response = $client.send(Pokepay::Request::ListShops.new(
                              organization_code: "J3-Ewgaz1-A51-l",
                              private_money_id: "d8ff15c0-cd4f-4057-98e1-64e687c4e191",
                              page: 4916,
                              per_page: 7166
    ))
    assert response.code != "400"
  end

  def test_create_shop_0
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "fe5e46BcHsmXbFuWwG3XlR0kMptCsVUpfDLBsXLkvcPCxtN"
    ))
    assert response.code != "400"
  end

  def test_create_shop_1
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "fe5e46BcHsmXbFuWwG3XlR0kMptCsVUpfDLBsXLkvcPCxtN",
                              organization_code: "--RTC-0DYtUArs---K-dw3-A--"
    ))
    assert response.code != "400"
  end

  def test_create_shop_2
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "fe5e46BcHsmXbFuWwG3XlR0kMptCsVUpfDLBsXLkvcPCxtN",
                              shop_external_id: "9oVa900419xwQJzn9JBXEftR0w9b",
                              organization_code: "59Hj--"
    ))
    assert response.code != "400"
  end

  def test_create_shop_3
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "fe5e46BcHsmXbFuWwG3XlR0kMptCsVUpfDLBsXLkvcPCxtN",
                              shop_email: "lkKMSB1QdU@oCPi.com",
                              shop_external_id: "UjaCgs6LoKt7ybAYXdwAO255cHZ3mAcHDfiN",
                              organization_code: "-xS--m-0wZ5-8BK2m5Y-T-g---934-dy"
    ))
    assert response.code != "400"
  end

  def test_create_shop_4
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "fe5e46BcHsmXbFuWwG3XlR0kMptCsVUpfDLBsXLkvcPCxtN",
                              shop_tel: "03-67-447",
                              shop_email: "Bgz3uBEXkO@Ecbr.com",
                              shop_external_id: "0cyEINPN9o5I7fKWWZmMY9Ie2O3rXss0",
                              organization_code: "c677-NUx-1-HY3pPq-8ax0t"
    ))
    assert response.code != "400"
  end

  def test_create_shop_5
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "fe5e46BcHsmXbFuWwG3XlR0kMptCsVUpfDLBsXLkvcPCxtN",
                              shop_address: "EVffnu8tYzwePhhVnlApQFWXfr0M2vOjVr6C4nrkMxPAxpsomcedlZZ",
                              shop_tel: "0510-9501-182",
                              shop_email: "uFFEwxdWeX@Uy4A.com",
                              shop_external_id: "kL38ay",
                              organization_code: "0"
    ))
    assert response.code != "400"
  end

  def test_create_shop_6
    response = $client.send(Pokepay::Request::CreateShop.new(
                              "fe5e46BcHsmXbFuWwG3XlR0kMptCsVUpfDLBsXLkvcPCxtN",
                              shop_postal_code: "0240060",
                              shop_address: "A3BJBBcVRpeIXO6Sp45vVZGQLzq2HnscYJ04Nv5QQilEEPXXyq0Gnh8gqHPQQFqVeKq7lUUCRAww0cUdFVbNh7WEorn7msNFpPUAPN2J2gCpY8iBEq87HzJs0609P06zw3cgAvG7Ms3vdp7AKbpuVwNOfDNeEe1kwHDRb4TGDCDUDrZRxMFqiojs5O4KeQLb3JwABqXT8Y8s7ZcOP7hlG1YDNSP8f8LiSs57V0wksK27V6m0V",
                              shop_tel: "042-72-364",
                              shop_email: "ztsn0j8XEd@BlFP.com",
                              shop_external_id: "nzYTk8gWegJgpL1F5gt",
                              organization_code: "CE11s287R6-VJu6Ps4-fF2r4"
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_0
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2acace5a-e1ef-4971-86a0-1c841ec55c02"
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_1
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2acace5a-e1ef-4971-86a0-1c841ec55c02",
                              page: 277
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_2
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2acace5a-e1ef-4971-86a0-1c841ec55c02",
                              per_page: 1517,
                              page: 4712
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_3
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2acace5a-e1ef-4971-86a0-1c841ec55c02",
                              from: "2025-03-03T23:01:00.000000+09:00",
                              to: "2018-05-07T11:06:20.000000+09:00"
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_4
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2acace5a-e1ef-4971-86a0-1c841ec55c02",
                              from: "2016-10-31T12:25:19.000000+09:00",
                              to: "2021-11-24T10:34:37.000000+09:00",
                              page: 8810
    ))
    assert response.code != "400"
  end

  def test_get_private_money_organization_summaries_5
    response = $client.send(Pokepay::Request::GetPrivateMoneyOrganizationSummaries.new(
                              "2acace5a-e1ef-4971-86a0-1c841ec55c02",
                              from: "2019-12-21T14:41:14.000000+09:00",
                              to: "2016-06-23T00:31:42.000000+09:00",
                              per_page: 7179,
                              page: 729
    ))
    assert response.code != "400"
  end

end
