# coding: utf-8
# DO NOT EDIT: File is generated by code generator.

require 'minitest/autorun'
require 'securerandom'
require "pokepay_partner_ruby_sdk"
require "inifile"

$client = Pokepay::Client.new(File.expand_path("~/.pokepay/test-config.ini"))
$inifile = IniFile.load(File.expand_path("~/.pokepay/test-config.ini"))

class SendEchoTest < Minitest::Test
  def simpleTest
    response = $client.send(Pokepay::Request::SendEcho.new(
      "Hello"
    ))
    assert_equal("ok", response.status)
    assert_equal("Hello", response.message)
  end
end
