# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/private_money"
require "pokepay_partner_ruby_sdk/response/user"

module Pokepay::Response
  class AccountDetail
    def initialize(row)
      @id = row["id"]
      @name = row["name"]
      @is_suspended = row["is_suspended"]
      @status = row["status"]
      @balance = row["balance"]
      @money_balance = row["money_balance"]
      @point_balance = row["point_balance"]
      @point_debt = row["point_debt"]
      @private_money = PrivateMoney.new(row["private_money"])
      @user = User.new(row["user"])
      @external_id = row["external_id"]
    end
    attr_reader :id
    attr_reader :name
    attr_reader :is_suspended
    attr_reader :status
    attr_reader :balance
    attr_reader :money_balance
    attr_reader :point_balance
    attr_reader :point_debt
    attr_reader :private_money
    attr_reader :user
    attr_reader :external_id
  end
end
