# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_status"
require "pokepay_partner_ruby_sdk/response/user"

module Pokepay::Response
  class AccountWithoutPrivateMoneyDetail
    def initialize(row)
      @id = row["id"]
      @name = row["name"]
      @is_suspended = row["is_suspended"]
      @status = AccountStatus.new(row["status"])
      @private_money_id = row["private_money_id"]
      @user = User.new(row["user"])
    end
    attr_reader :id
    attr_reader :name
    attr_reader :is_suspended
    attr_reader :status
    attr_reader :private_money_id
    attr_reader :user
  end
end
