# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class AccountTransferSummary
    def initialize(row)
      @summaries = row["summaries"]
    end
    attr_reader :summaries
  end
end
