# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class AccountTransferSummaryElement
    def initialize(row)
      @transfer_type = row["transfer_type"]
      @money_amount = row["money_amount"]
      @point_amount = row["point_amount"]
      @count = row["count"]
    end
    attr_reader :transfer_type
    attr_reader :money_amount
    attr_reader :point_amount
    attr_reader :count
  end
end
