# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class Banks
    def initialize(row)
      @rows = row["rows"]
      @count = row["count"]
    end
    attr_reader :rows
    attr_reader :count
  end
end
