# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/private_money"

module Pokepay::Response
  class Bank
    def initialize(row)
      @id = row["id"]
      @private_money = PrivateMoney.new(row["private_money"])
      @bank_name = row["bank_name"]
      @bank_code = row["bank_code"]
      @branch_number = row["branch_number"]
      @branch_name = row["branch_name"]
      @deposit_type = row["deposit_type"]
      @masked_account_number = row["masked_account_number"]
      @account_name = row["account_name"]
    end
    attr_reader :id
    attr_reader :private_money
    attr_reader :bank_name
    attr_reader :bank_code
    attr_reader :branch_number
    attr_reader :branch_name
    attr_reader :deposit_type
    attr_reader :masked_account_number
    attr_reader :account_name
  end
end
