# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class BankRegisteringInfo
    def initialize(row)
      @redirect_url = row["redirect_url"]
      @paytree_customer_number = row["paytree_customer_number"]
    end
    attr_reader :redirect_url
    attr_reader :paytree_customer_number
  end
end
