# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_with_user"

module Pokepay::Response
  class Bill
    def initialize(row)
      @id = row["id"]
      @amount = row["amount"]
      @max_amount = row["max_amount"]
      @min_amount = row["min_amount"]
      @description = row["description"]
      @account = AccountWithUser.new(row["account"])
      @is_disabled = row["is_disabled"]
    end
    attr_reader :id
    attr_reader :amount
    attr_reader :max_amount
    attr_reader :min_amount
    attr_reader :description
    attr_reader :account
    attr_reader :is_disabled
  end
end
