# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/transaction"
require "pokepay_partner_ruby_sdk/response/bill"

module Pokepay::Response
  class BillTransaction
    def initialize(row)
      @transaction = Transaction.new(row["transaction"])
      @bill = Bill.new(row["bill"])
    end
    attr_reader :transaction
    attr_reader :bill
  end
end
