# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/bulk_transaction"

module Pokepay::Response
  class BulkTransactionJob
    def initialize(row)
      @id = row["id"]
      @bulk_transaction = BulkTransaction.new(row["bulk_transaction"])
      @type = row["type"]
      @sender_account_id = row["sender_account_id"]
      @receiver_account_id = row["receiver_account_id"]
      @money_amount = row["money_amount"]
      @point_amount = row["point_amount"]
      @description = row["description"]
      @bear_point_account_id = row["bear_point_account_id"]
      @point_expires_at = row["point_expires_at"]
      @status = row["status"]
      @error = row["error"]
      @lineno = row["lineno"]
      @transaction_id = row["transaction_id"]
      @created_at = row["created_at"]
      @updated_at = row["updated_at"]
    end
    attr_reader :id
    attr_reader :bulk_transaction
    attr_reader :type
    attr_reader :sender_account_id
    attr_reader :receiver_account_id
    attr_reader :money_amount
    attr_reader :point_amount
    attr_reader :description
    attr_reader :bear_point_account_id
    attr_reader :point_expires_at
    attr_reader :status
    attr_reader :error
    attr_reader :lineno
    attr_reader :transaction_id
    attr_reader :created_at
    attr_reader :updated_at
  end
end
