# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class BulkTransaction
    def initialize(row)
      @request_id = row["request_id"]
      @name = row["name"]
      @description = row["description"]
      @status = row["status"]
      @submitted_at = row["submitted_at"]
      @updated_at = row["updated_at"]
    end
    attr_reader :request_id
    attr_reader :name
    attr_reader :description
    attr_reader :status
    attr_reader :submitted_at
    attr_reader :updated_at
  end
end
