# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class CampaignShopLabelUserTagGroup
    def initialize(row)
      @id = row["id"]
      @name_en = row["name_en"]
      @name_ja = row["name_ja"]
    end
    attr_reader :id
    attr_reader :name_en
    attr_reader :name_ja
  end
end
