# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/campaign_shop_label_user_tag_group"

module Pokepay::Response
  class CampaignShopLabel
    def initialize(row)
      @id = row["id"]
      @name_en = row["name_en"]
      @name_ja = row["name_ja"]
      @user_tag_group = CampaignShopLabelUserTagGroup.new(row["user_tag_group"])
    end
    attr_reader :id
    attr_reader :name_en
    attr_reader :name_ja
    attr_reader :user_tag_group
  end
end
