# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class CapturedCreditSession
    def initialize(row)
      @session_id = row["session_id"]
    end
    attr_reader :session_id
  end
end
