# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_with_user"

module Pokepay::Response
  class Cashtray
    def initialize(row)
      @id = row["id"]
      @amount = row["amount"]
      @description = row["description"]
      @account = AccountWithUser.new(row["account"])
      @expires_at = row["expires_at"]
      @canceled_at = row["canceled_at"]
      @token = row["token"]
    end
    attr_reader :id
    attr_reader :amount
    attr_reader :description
    attr_reader :account
    attr_reader :expires_at
    attr_reader :canceled_at
    attr_reader :token
  end
end
