# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_with_user"

module Pokepay::Response
  class CashtrayAttempt
    def initialize(row)
      @account = AccountWithUser.new(row["account"])
      @status_code = row["status_code"]
      @error_type = row["error_type"]
      @error_message = row["error_message"]
      @created_at = row["created_at"]
    end
    attr_reader :account
    attr_reader :status_code
    attr_reader :error_type
    attr_reader :error_message
    attr_reader :created_at
  end
end
