# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/user"

module Pokepay::Response
  class Coupon
    def initialize(row)
      @id = row["id"]
      @name = row["name"]
      @issued_shop = User.new(row["issued_shop"])
      @description = row["description"]
      @discount_amount = row["discount_amount"]
      @discount_percentage = row["discount_percentage"]
      @discount_upper_limit = row["discount_upper_limit"]
      @starts_at = row["starts_at"]
      @ends_at = row["ends_at"]
      @display_starts_at = row["display_starts_at"]
      @display_ends_at = row["display_ends_at"]
      @usage_limit = row["usage_limit"]
      @min_amount = row["min_amount"]
      @is_shop_specified = row["is_shop_specified"]
      @is_hidden = row["is_hidden"]
      @is_public = row["is_public"]
      @code = row["code"]
      @is_disabled = row["is_disabled"]
      @token = row["token"]
    end
    attr_reader :id
    attr_reader :name
    attr_reader :issued_shop
    attr_reader :description
    attr_reader :discount_amount
    attr_reader :discount_percentage
    attr_reader :discount_upper_limit
    attr_reader :starts_at
    attr_reader :ends_at
    attr_reader :display_starts_at
    attr_reader :display_ends_at
    attr_reader :usage_limit
    attr_reader :min_amount
    attr_reader :is_shop_specified
    attr_reader :is_hidden
    attr_reader :is_public
    attr_reader :code
    attr_reader :is_disabled
    attr_reader :token
  end
end
