# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class CreditSession
    def initialize(row)
      @id = row["id"]
      @expires_at = row["expires_at"]
    end
    attr_reader :id
    attr_reader :expires_at
  end
end
