# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/individual_number_identification"

module Pokepay::Response
  class CustomerListRow
    def initialize(row)
      @id = row["id"]
      @name = row["name"]
      @tel = row["tel"]
      @email = row["email"]
      @registered_at = row["registered_at"]
      @last_transaction_done_at = row["last_transaction_done_at"]
      @money_balance = row["money_balance"]
      @point_balance = row["point_balance"]
      @account_uuid = row["account_uuid"]
      @account_is_suspended = row["account_is_suspended"]
      @account_status = row["account_status"]
      @external_id = row["external_id"]
      @individual_number_identification = IndividualNumberIdentification.new(row["individual_number_identification"])
    end
    attr_reader :id
    attr_reader :name
    attr_reader :tel
    attr_reader :email
    attr_reader :registered_at
    attr_reader :last_transaction_done_at
    attr_reader :money_balance
    attr_reader :point_balance
    attr_reader :account_uuid
    attr_reader :account_is_suspended
    attr_reader :account_status
    attr_reader :external_id
    attr_reader :individual_number_identification
  end
end
