# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_detail"
require "pokepay_partner_ruby_sdk/response/user"

module Pokepay::Response
  class CvsAuthorization
    def initialize(row)
      @account = AccountDetail.new(row["account"])
      @user = User.new(row["user"])
      @order_id = row["order_id"]
      @transaction_id = row["transaction_id"]
      @pay_limit = row["pay_limit"]
      @tel = row["tel"]
      @name1 = row["name1"]
      @name2 = row["name2"]
      @amount = row["amount"]
      @service_option_type = row["service_option_type"]
      @haraikomi_url = row["haraikomi_url"]
      @receipt_no = row["receipt_no"]
      @done_at = row["done_at"]
      @canceled_at = row["canceled_at"]
    end
    attr_reader :account
    attr_reader :user
    attr_reader :order_id
    attr_reader :transaction_id
    attr_reader :pay_limit
    attr_reader :tel
    attr_reader :name1
    attr_reader :name2
    attr_reader :amount
    attr_reader :service_option_type
    attr_reader :haraikomi_url
    attr_reader :receipt_no
    attr_reader :done_at
    attr_reader :canceled_at
  end
end
