# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class IndividualNumberIdentification
    def initialize(row)
      @is_identified = row["is_identified"]
      @last_identified_at = row["last_identified_at"]
      @expires_at = row["expires_at"]
      @is_resident = row["is_resident"]
    end
    attr_reader :is_identified
    attr_reader :last_identified_at
    attr_reader :expires_at
    attr_reader :is_resident
  end
end
