# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class OrganizationWorkerTaskWebhook
    def initialize(row)
      @id = row["id"]
      @organization_code = row["organization_code"]
      @task = row["task"]
      @url = row["url"]
      @content_type = row["content_type"]
      @is_active = row["is_active"]
    end
    attr_reader :id
    attr_reader :organization_code
    attr_reader :task
    attr_reader :url
    attr_reader :content_type
    attr_reader :is_active
  end
end
