# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class Pagination
    def initialize(row)
      @current = row["current"]
      @per_page = row["per_page"]
      @max_page = row["max_page"]
      @has_prev = row["has_prev"]
      @has_next = row["has_next"]
    end
    attr_reader :current
    attr_reader :per_page
    attr_reader :max_page
    attr_reader :has_prev
    attr_reader :has_next
  end
end
