# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class PaginatedTransfersV2
    def initialize(row)
      @rows = row["rows"]
      @per_page = row["per_page"]
      @count = row["count"]
      @next_page_cursor_id = row["next_page_cursor_id"]
      @prev_page_cursor_id = row["prev_page_cursor_id"]
    end
    attr_reader :rows
    attr_reader :per_page
    attr_reader :count
    attr_reader :next_page_cursor_id
    attr_reader :prev_page_cursor_id
  end
end
