# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class PaginatedCvsAuthorizations
    def initialize(row)
      @per_page = row["per_page"]
      @count = row["count"]
      @items = row["items"]
      @prev = row["prev"]
      @next = row["next"]
    end
    attr_reader :per_page
    attr_reader :count
    attr_reader :items
    attr_reader :prev
    attr_reader :next
  end
end
