# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class PrivateMoneySummary
    def initialize(row)
      @topup_amount = row["topup_amount"]
      @refunded_topup_amount = row["refunded_topup_amount"]
      @payment_amount = row["payment_amount"]
      @refunded_payment_amount = row["refunded_payment_amount"]
      @added_point_amount = row["added_point_amount"]
      @refunded_added_point_amount = row["refunded_added_point_amount"]
      @exchange_inflow_amount = row["exchange_inflow_amount"]
      @exchange_outflow_amount = row["exchange_outflow_amount"]
      @transaction_count = row["transaction_count"]
    end
    attr_reader :topup_amount
    attr_reader :refunded_topup_amount
    attr_reader :payment_amount
    attr_reader :refunded_payment_amount
    attr_reader :added_point_amount
    attr_reader :refunded_added_point_amount
    attr_reader :exchange_inflow_amount
    attr_reader :exchange_outflow_amount
    attr_reader :transaction_count
  end
end
