# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_detail"
require "pokepay_partner_ruby_sdk/response/transaction"

module Pokepay::Response
  class SevenBankATMSession
    def initialize(row)
      @qr_info = row["qr_info"]
      @account = AccountDetail.new(row["account"])
      @amount = row["amount"]
      @transaction = row["transaction"] and Transaction.new(row["transaction"])
      @seven_bank_customer_number = row["seven_bank_customer_number"]
      @atm_id = row["atm_id"]
      @audi_id = row["audi_id"]
      @issuer_code = row["issuer_code"]
      @issuer_name = row["issuer_name"]
      @money_name = row["money_name"]
    end
    attr_reader :qr_info
    attr_reader :account
    attr_reader :amount
    attr_reader :transaction
    attr_reader :seven_bank_customer_number
    attr_reader :atm_id
    attr_reader :audi_id
    attr_reader :issuer_code
    attr_reader :issuer_name
    attr_reader :money_name
  end
end
