# DO NOT EDIT: File is generated by code generator.

require "pokepay_partner_ruby_sdk/response/account_without_private_money_detail"
require "pokepay_partner_ruby_sdk/response/account_without_private_money_detail"

module Pokepay::Response
  class Transfer
    def initialize(row)
      @id = row["id"]
      @sender_account = AccountWithoutPrivateMoneyDetail.new(row["sender_account"])
      @receiver_account = AccountWithoutPrivateMoneyDetail.new(row["receiver_account"])
      @amount = row["amount"]
      @money_amount = row["money_amount"]
      @point_amount = row["point_amount"]
      @done_at = row["done_at"]
      @type = row["type"]
      @description = row["description"]
      @transaction_id = row["transaction_id"]
    end
    attr_reader :id
    attr_reader :sender_account
    attr_reader :receiver_account
    attr_reader :amount
    attr_reader :money_amount
    attr_reader :point_amount
    attr_reader :done_at
    attr_reader :type
    attr_reader :description
    attr_reader :transaction_id
  end
end
