# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class TransactionGroup
    def initialize(row)
      @id = row["id"]
      @name = row["name"]
      @created_at = row["created_at"]
      @updated_at = row["updated_at"]
      @transactions = row["transactions"]
    end
    attr_reader :id
    attr_reader :name
    attr_reader :created_at
    attr_reader :updated_at
    attr_reader :transactions
  end
end
