# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class UserStatsOperation
    def initialize(row)
      @id = row["id"]
      @from = row["from"]
      @to = row["to"]
      @status = row["status"]
      @error_reason = row["error_reason"]
      @done_at = row["done_at"]
      @file_url = row["file_url"]
      @requested_at = row["requested_at"]
    end
    attr_reader :id
    attr_reader :from
    attr_reader :to
    attr_reader :status
    attr_reader :error_reason
    attr_reader :done_at
    attr_reader :file_url
    attr_reader :requested_at
  end
end
