# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class UserStatsOperationServiceUnavailable
    def initialize(row)
      @type = row["type"]
      @message = row["message"]
    end
    attr_reader :type
    attr_reader :message
  end
end
