# DO NOT EDIT: File is generated by code generator.


module Pokepay::Response
  class UserCard
    def initialize(row)
      @id = row["id"]
      @card_number = row["card_number"]
      @registered_at = row["registered_at"]
    end
    attr_reader :id
    attr_reader :card_number
    attr_reader :registered_at
  end
end
