# encoding: utf-8

require "pokepay_partner_ruby_sdk/version"
require "pokepay_partner_ruby_sdk/client"
require "pokepay_partner_ruby_sdk/request/request"
require "pokepay_partner_ruby_sdk/request/get_private_money_organization_summaries"
require "pokepay_partner_ruby_sdk/request/create_shop"
require "pokepay_partner_ruby_sdk/request/create_organization"
require "pokepay_partner_ruby_sdk/request/create_cpm_transaction"
require "pokepay_partner_ruby_sdk/request/get_transaction"
require "pokepay_partner_ruby_sdk/request/create_transaction"
require "pokepay_partner_ruby_sdk/request/list_transactions"
require "pokepay_partner_ruby_sdk/request/create_check"
require "pokepay_partner_ruby_sdk/request/get_user"
require "pokepay_partner_ruby_sdk/request/create_echo"
require "pokepay_partner_ruby_sdk/request/get_ping"
require "pokepay_partner_ruby_sdk/response/pong"
require "pokepay_partner_ruby_sdk/response/echo"
require "pokepay_partner_ruby_sdk/response/pagination"
require "pokepay_partner_ruby_sdk/response/admin_user_with_shops_and_private_moneys"
require "pokepay_partner_ruby_sdk/response/account"
require "pokepay_partner_ruby_sdk/response/check"
require "pokepay_partner_ruby_sdk/response/user"
require "pokepay_partner_ruby_sdk/response/private_money"
require "pokepay_partner_ruby_sdk/response/organization"
require "pokepay_partner_ruby_sdk/response/transaction"
require "pokepay_partner_ruby_sdk/response/user_transaction"
require "pokepay_partner_ruby_sdk/response/invalid_parameters"
require "pokepay_partner_ruby_sdk/parameter/product"
require "pokepay_partner_ruby_sdk/response/organization_summary"
require "pokepay_partner_ruby_sdk/response/private_money_organization_summary"
require "pokepay_partner_ruby_sdk/response/paginated_private_money_organization_summaries"
require "pokepay_partner_ruby_sdk/response/paginated_transaction"

module Pokepay
  class Error < StandardError; end
end
